-- ═══════════════════════════════════════════════════════════════════════════
-- BLOG — RUNDA A SAPTEA DE AUDIT, 31.08.2026
-- ═══════════════════════════════════════════════════════════════════════════
--
-- ⚠ ADEVARUL REPRODUCTIBIL E `migrations/000-schema-baseline.sql`. Invariantele
-- sunt probate de `scripts/tests/blog-integrare.sql`, sectiunea R.
--
-- Auditul a retras de la sine doua constatari din runda trecuta — rotirea
-- jetonului de dezabonare si plafonul durabil — dupa ce a citit motivele scrise
-- in migratia rundei a sasea. Notele „ce s-a verificat si nu s-a schimbat" isi
-- fac treaba: cine le citeste nu mai cere aceeasi schimbare a doua oara.
--
--
-- ═══ 1. RETENTIA ABONARILOR NECONFIRMATE ═══
--
-- Dubla confirmare spune pe fata: nu socotim pe nimeni abonat pana nu apasa. Dar
-- randul ramanea in baza oricum — cu adresa, cu sursa, cu amprenta jetonului —
-- desi nu poate primi nimic si jetonul lui e demult stins.
--
-- ⚠ CE E DE FAPT: o adresa de email pastrata fara temei. Si nu neaparat a celui
-- care a scris-o: oricine poate tasta adresa altcuiva in formular. Exact de aceea
-- exista dubla confirmare — dar daca pastram randul oricum, jumatate din motivul
-- ei se pierde.
--
-- `blog_curata_abonari_neconfirmate(p_zile default 30)`, chemata din cronul orar
-- `discount-release`. ⚠ NU E UN CRON NOU: fisierul acela gazduieste deja
-- `curata_limite`, cu motivul scris — „cronul orar cel mai usor". Se urmeaza
-- tiparul casei, nu se inventeaza altul.
--
-- ⚠ CELE PATRU AFIRMATII DE „RAMANE" SUNT MIEZUL PROBEI, nu cea de „se sterge":
--   * abonatul CONFIRMAT ramane (evident, dar o conditie prea larga ar goli lista
--     fara ca nimeni sa afle pana la prima campanie, si nu se mai poate lua inapoi)
--   * DEZABONATUL ramane — nu e o abonare esuata, e o hotarare a omului si
--     singura dovada ca a cerut sa nu mai primeasca; sters, s-ar putea reabona
--     din greseala la primul import
--   * cel RECENT ramane
--   * cel cu `created_at` vechi dar JETON PROASPAT ramane — a reincercat ieri,
--     deci e o confirmare in curs, nu un rest
--
-- ⚠ CELE 30 DE ZILE SUNT O ALEGERE DE POLITICA, nu una tehnica. Trebuie sa se
-- potriveasca cu ce scrie in politica de confidentialitate. Se schimba dintr-un
-- singur loc: argumentul din `discount-release/route.ts`.
--
--
-- ═══ 2. SITEMAPUL NU MAI INVENTEAZA `lastModified` ═══
--
-- Auditul semnala `/blog`. Masurat, erau DOUAZECI SI TREI de adrese: tot ce trece
-- prin `paginiDeSite()`, plus pagina de start, preturile, termenii, si tot centrul
-- de ajutor. Toate spuneau, la FIECARE generare a sitemapului, ca s-au schimbat azi.
--
-- ⚠ PAGUBA NU E LOCALA, SI ASTA E MOTIVUL ADEVARAT AL REPARATIEI. Un `lastmod`
-- care se misca zilnic fara temei il invata pe Google sa nu mai creada campul pe
-- domeniul asta — deci ieftineste chiar datele pe care le-am facut corecte cu
-- greu: `content_updated_at` pe articole (runda a doua) si cel pus pe rubrici si
-- autori (runda a sasea). O minciuna repetata pe 23 de adrese scade pretul
-- adevarului de pe celelalte.
--
-- Google spune limpede ca daca nu poti afla data reala a unei pagini, e mai bine
-- sa NU trimiti `lastmod` decat sa trimiti unul inventat. Paginile astea traiesc
-- in cod si se schimba la desfasurare; n-avem de unde sti cand.
--
-- `changeFrequency` ramane: e o sugestie despre viitor, nu o afirmatie despre
-- trecut. Ce ARE data adevarata si-o pastreaza.
--
-- Plasa: `src/app/sitemap.test.ts` cade daca revine vreun `lastModified: new Date()`.
--
--
-- ═══ 3. UN DEFECT DE-AL MEU, DIN RUNDELE 5 SI 6 ═══
--
-- ⚠ SECTIUNEA J DIN `blog-integrare.sql` NU MAI ERA SQL VALID, si nu de azi.
--
-- Numaratoarea finala („nimic nu a ramas in urma") aduna subinterogari cu `+`.
-- Adaugand randuri in runda 5 si iar in runda 6, am uitat de doua ori operatorul
-- dintre ele. Deci blocul ar fi picat la parsare, nu la afirmatie.
--
-- ⚠ DE CE N-AM PRINS-O: am rulat de fiecare data sectiunile NOI (M, N, T, G) si
-- niciodata J. Iar J e tocmai bucata care spune daca probele si-au facut
-- curatenia — adica singura care apara productia de resturile lor.
--
-- Reparat, rulat, si CONFRUNTAT: cu un rand de proba ramas, J chiar pica.
--
--
-- ═══ CE NU S-A FACUT, SI DE CE ═══
--
--   * MFA OBLIGATORIU PENTRU ADMIN. Ramane optional dinadins: adminul e
--     proprietarul, si o poarta prost pusa l-ar incuia singur afara din panou.
--     Pentru REDACTOR s-a facut — vezi adaosul de la capatul fisierului.
--
--   * IMAGINILE DIN CORPUL ARTICOLULUI fara `width`/`height`/`srcset`. E polish
--     de performanta, atinge editorul si conducta de incarcare, si nu are niciun
--     articol pe care sa se vada azi (blogul e gol). Se face cu primele articole
--     adevarate, cand se poate si masura.
--
--   * URCAREA LUI `sanitize-html`. Motivul intreg e in migratia rundei a sasea:
--     `htmlparser2` 12 e doar-ESM, iar pachetul e in `serverExternalPackages`.
--     Auditul e acum de acord ca nu se face orbeste.
--
--
-- ═══════════════════════════════════════════════════════════════════════════
-- ADAOS: AL DOILEA FACTOR, OBLIGATORIU PENTRU REDACTOR
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Clientul a ales varianta de mijloc, si e o alegere buna: obligatoriu pentru
-- REDACTOR, neschimbat pentru ADMIN.
--
-- ⚠ DE CE ASA. Adminul e proprietarul; o poarta prost pusa l-ar incuia singur
-- afara din panou, si atunci n-ar mai avea de unde sa o repare. Redactorul e
-- rolul pe care il dai unui OM DIN AFARA — contul lui scrie continut public, iar
-- actiunile de acolo lucreaza cu cheia de serviciu. Riscul de auto-blocare:
-- zero, fiindca astazi exista un singur cont, si acela e admin.
--
-- Pusa la AMANDOUA portile: `requireBlogEditor` (ecran) si `requireBlogEditorApi`
-- (actiuni). O poarta de actiune mai slaba decat cea de pagina e o usa lasata
-- deschisa in spate: actiunile se pot chema direct, fara niciun ecran.
--
-- ⚠ USA DIN DOS SE INCHIDE SINGURA. Auditul cerea si interzicerea dezactivarii
-- MFA pentru rolurile privilegiate. N-a fost nevoie: paza ruleaza la FIECARE
-- cerere, deci un redactor care isi stinge MFA-ul din Setari pierde blogul la
-- urmatoarea pagina. O a doua regula ar fi fost inca un loc care poate ramane in
-- urma fata de prima.
--
-- ⚠ REGULA E O FUNCTIE PURA, `opritFiindcaNareMfa`, in `lib/auth/mfa.ts`. Scrisa
-- in linie intr-o paza care are nevoie de Supabase, ar fi fost o regula de acces
-- pe care n-o verifica nimeni. Are 6 probe, confruntate.
--
-- ⚠ SI REDIRECTAREA AJUNGE UNDE SPUNE. Fila „Securitate" din Setari nu se putea
-- deschide din adresa; acum se poate (`?sectiune=securitate`), iar `?mfa=cerut`
-- arata si de ce a fost adus omul acolo. Altfel ar fi aterizat intr-o pagina
-- fara sa stie ce sa caute — greseala pe care am facut-o deja de doua ori.
--
--
-- ═══════════════════════════════════════════════════════════════════════════
-- ADAOS (runda 8): NICIUN `lastModified` INVENTAT, NICAIERI
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Auditul semnala UN singur loc ramas: eticheta, cu `e.ultima ? ... : new Date()`.
-- Masurat, erau ZECE — aceeasi forma la magazine, la produse, la paginile
-- personalizate si la etichete: „daca nu stiu data, spun ca e azi".
--
-- E forma mai mica a aceleiasi minciuni pentru care s-a scos `lastModified` de pe
-- cele 23 de pagini scrise in cod. Se repara la fel: cand data lipseste, campul
-- LIPSESTE. `dataDacaOStim()` intoarce chei de imprastiat, nu `undefined`.
--
-- ⚠ SI CELE DOUA AJUTOARE DE DATA intorc acum `null` in loc de `new Date()`:
-- `candSaSchimbat` si `ceaMaiProaspata`. Erau ultimele locuri de unde putea iesi
-- o data inventata fara ca cineva sa o scrie anume.
--
-- ⚠ PLASA S-A AGATAT DE PROPRIILE MELE VORBE. Proba care cauta
-- `lastModified: new Date()` in sursa a picat pe COMENTARIUL care citeaza
-- tiparul ca sa explice de ce l-am scos. Scoate comentariile intai — altfel e o
-- plasa pe care al doilea om o dezactiveaza, si pe buna dreptate.
--
--
-- ═══════════════════════════════════════════════════════════════════════════
-- ADMINUL RAMANE FARA MFA OBLIGATORIU — HOTARARE ASUMATA, NU SCAPARE
-- ═══════════════════════════════════════════════════════════════════════════
--
-- ⚠ SE SCRIE AICI CA SA NU MAI FIE CERUTA. Auditul a ridicat-o ca singurul lucru
-- care tine sistemul sub 10/10, si o va ridica din nou daca nu gaseste raspunsul.
-- Raspunsul e: proprietarul a ales asa, de doua ori, dupa ce i s-au spus faptele.
--
-- ═══ FAPTELE, MASURATE INAINTE DE HOTARARE ═══
--
--   * exista UN SINGUR cont cu rol `admin`, si NU are `mfa_email_enabled`
--   * `requireBlogEditor()` e chemata din `(admin)/layout.tsx`, deci pazeste
--     TOT `/admin`, nu doar blogul — auditul nu vede asta, si de aceea
--     subestimeaza consecinta: schimbarea n-ar inchide blogul, ci comenzile,
--     produsele, utilizatorii, tot panoul
--   * ar fi fost recuperabil: `/dashboard/settings` are alta paza, deci MFA se
--     putea activa de acolo — dar cu o fereastra in care nu se intra nicaieri,
--     pe o platforma cu 130 de magazine si comenzi care intra in timpul zilei
--
-- ═══ CE RAMANE ADEVARAT DESPRE SECURITATE ═══
--
-- Nu e „admin fara al doilea factor" in sensul ca mecanismul lipseste:
--
--   * adminul POATE activa MFA, si daca il activeaza, `sesiuneCurentaNeconfirmata`
--     ii cere confirmarea sesiunii la fel ca oricui
--   * claimul semnat `app_metadata.role` apara impotriva ridicarii de rol —
--     dar e o alta paza, nu un al doilea factor, si auditul are dreptate sa
--     spuna ca nu tine locul MFA
--   * REDACTORUL, adica rolul dat unui om din afara, are MFA OBLIGATORIU
--
-- Deci riscul asumat e ingust si numit: contul proprietarului poate ramane
-- doar-cu-parola. Auditul insusi spune ca, fata de o specificatie in care asta e
-- ales explicit, sistemul e 10/10 — si asta e specificatia.
--
-- ⚠ DACA SE RAZGANDESTE CINEVA, se schimba O SINGURA LINIE in `lib/auth/mfa.ts`:
--   `return rol === "editor";`  ->  `return rol === "editor" || rol === "admin";`
-- Ambele porti o folosesc deja. ⚠ DAR INTAI SE ACTIVEAZA MFA PE CONTUL DE ADMIN,
-- si abia apoi se schimba linia — altfel exista o fereastra fara acces la panou.
