// Curated subset of the Google Product Taxonomy (full-path strings — Google
// accepts the path string directly for `googleProductCategory`). Covers the
// common verticals for Romanian e-commerce. Searchable in the mapping UI.

export const GOOGLE_CATEGORIES: string[] = [
  // Apparel & Accessories
  "Apparel & Accessories",
  "Apparel & Accessories > Clothing",
  "Apparel & Accessories > Clothing > Shirts & Tops",
  "Apparel & Accessories > Clothing > Dresses",
  "Apparel & Accessories > Clothing > Pants",
  "Apparel & Accessories > Clothing > Skirts",
  "Apparel & Accessories > Clothing > Shorts",
  "Apparel & Accessories > Clothing > Outerwear > Coats & Jackets",
  "Apparel & Accessories > Clothing > Underwear & Socks",
  "Apparel & Accessories > Clothing > Sleepwear & Loungewear",
  "Apparel & Accessories > Clothing > Activewear",
  "Apparel & Accessories > Clothing > Baby & Toddler Clothing",
  "Apparel & Accessories > Shoes",
  "Apparel & Accessories > Jewelry",
  "Apparel & Accessories > Jewelry > Watches",
  "Apparel & Accessories > Handbags, Wallets & Cases > Handbags",
  "Apparel & Accessories > Clothing Accessories",
  "Apparel & Accessories > Clothing Accessories > Sunglasses",
  "Apparel & Accessories > Clothing Accessories > Hats",
  "Apparel & Accessories > Clothing Accessories > Belts",
  // Health & Beauty
  "Health & Beauty",
  "Health & Beauty > Personal Care",
  "Health & Beauty > Personal Care > Cosmetics",
  "Health & Beauty > Personal Care > Cosmetics > Makeup",
  "Health & Beauty > Personal Care > Cosmetics > Skin Care",
  "Health & Beauty > Personal Care > Cosmetics > Bath & Body",
  "Health & Beauty > Personal Care > Hair Care",
  "Health & Beauty > Personal Care > Fragrances",
  "Health & Beauty > Personal Care > Oral Care",
  "Health & Beauty > Health Care > Vitamins & Supplements",
  // Home & Garden
  "Home & Garden",
  "Home & Garden > Kitchen & Dining",
  "Home & Garden > Kitchen & Dining > Cookware & Bakeware",
  "Home & Garden > Kitchen & Dining > Tableware",
  "Home & Garden > Kitchen & Dining > Kitchen Appliances",
  "Home & Garden > Decor",
  "Home & Garden > Linens & Bedding > Bedding",
  "Home & Garden > Bathroom Accessories",
  "Home & Garden > Lighting",
  "Home & Garden > Household Supplies",
  "Furniture",
  "Furniture > Chairs",
  "Furniture > Tables",
  "Furniture > Sofas",
  "Furniture > Beds & Accessories",
  "Furniture > Cabinets & Storage",
  // Electronics
  "Electronics",
  "Electronics > Communications > Telephony > Mobile Phones",
  "Electronics > Communications > Telephony > Mobile Phone Accessories",
  "Electronics > Computers > Laptops",
  "Electronics > Computers > Computer Accessories",
  "Electronics > Audio > Audio Components > Headphones",
  "Electronics > Audio > Audio Components > Speakers",
  "Electronics > Video > Televisions",
  "Electronics > Electronics Accessories > Power > Batteries",
  "Electronics > Electronics Accessories > Cables",
  "Electronics > Video Game Consoles",
  "Electronics > Computers > Tablet Computers",
  "Electronics > Cameras & Optics > Cameras",
  // Toys, Baby, Sports
  "Toys & Games > Toys",
  "Toys & Games > Games",
  "Baby & Toddler",
  "Baby & Toddler > Baby Toys & Activity Equipment",
  "Baby & Toddler > Diapering",
  "Baby & Toddler > Nursing & Feeding",
  "Sporting Goods",
  "Sporting Goods > Exercise & Fitness",
  "Sporting Goods > Outdoor Recreation",
  // Food
  "Food, Beverages & Tobacco > Food Items",
  "Food, Beverages & Tobacco > Beverages",
  // Other common
  "Animals & Pet Supplies > Pet Supplies",
  "Office Supplies",
  "Arts & Entertainment > Hobbies & Creative Arts",
  "Media > Books",
  "Hardware > Tools",
  "Luggage & Bags",
  "Vehicles & Parts > Vehicle Parts & Accessories",
];
