/* ═══════════════════════════════════════════════════════════════════════════
   eMAG: id-ul ofertei e unic PE MAGAZIN, nu pe toata baza
   ═══════════════════════════════════════════════════════════════════════════

   Repara doua defecte din `2026-09-18-emag-marketplace.sql` care, luate impreuna,
   ar fi oprit importul celui de-al DOILEA comerciant care isi leaga contul.

   ═══ 1. UNICUL ERA GLOBAL ═══

   Tabelul se crease cu `constraint emag_offers_emag_id_key unique (emag_id)`.
   Corect atat timp cat toate id-urile ies din sirul nostru — dar importul din eMAG
   nu inventeaza id-uri, le PRELUA pe cele care exista deja in contul comerciantului.

   Iar `emag_id` e, prin chiar definitia lor, „seller internal product id": fiecare
   vanzator si-l alege singur. Doi comercianti au voie sa aiba amandoi oferta 1. Cel
   mai probabil chiar o au, fiindca cine numeroteaza de mana incepe de la 1.

   Deci: primul comerciant importa, ii intra ofertele 1..400. Al doilea importa, si
   toate randurile lui cad pe `duplicate key`. Nu cade cu un mesaj despre magazine —
   cade cu „Key (emag_id)=(1) already exists", care arata ca un defect al importului.
   Al doilea comerciant pur si simplu nu poate folosi integrarea.

   Unicul adevarat e `(business_id, emag_id)`: id-ul e al ofertei IN CONTUL ACELA.

   ═══ 2. SIRUL PORNEA DE UNDE PORNESC SI EI ═══

   Al doilea defect e mai tacut si nu se repara cu o constrangere.

   `emag_id bigint generated by default as identity` pornea de la 1. Adica exact de
   unde incep si numerotarile facute de mana in panourile eMAG. Un comerciant care
   intai publica din Edinio doua produse (iau 1 si 2) si abia dupa aceea porneste
   importul, ca sa-si aduca si ofertele vechi, s-ar fi lovit de propriile lui id-uri:
   oferta 1 din eMAG nu mai are unde sa intre, fiindca 1 e deja luat in magazinul lui.

   Si asta E ordinea fireasca a lucrurilor, nu una exotica: omul incearca intai cu un
   produs, se convinge ca merge, si abia dupa aceea aduce restul.

   Sirul nostru porneste de la 1.000.000.000. Sub prag stau numai id-uri PRELUATE de
   la ei, peste prag numai id-uri facute de noi. Un miliard nu e o cifra frumoasa
   aleasa la intamplare: e cu mult peste orice numerotare pe care si-o tine un
   vanzator de mana, si `bigint` mai are noua miliarde de miliarde deasupra, deci nu
   se ingusteaza nimic.

   ⚠ Pragul e o desprindere, nu o garantie. Daca un comerciant chiar are la eMAG o
   oferta cu id peste prag, `public.emag_ridica_sirul()` de mai jos impinge sirul
   deasupra ei. De aceea importul TREBUIE sa o cheme dupa ce scrie ofertele preluate.

   ⚠ Tabelul e gol la data acestei migratii (verificat: 0 randuri, sirul la 1), deci
   nu se rescrie nimic si nu se pierde nimic.
   ═══════════════════════════════════════════════════════════════════════════ */

begin;

/* ─── 1. Unicul, mutat pe magazin ─────────────────────────────────────────── */

alter table public.emag_offers
  drop constraint if exists emag_offers_emag_id_key;

alter table public.emag_offers
  add constraint emag_offers_business_emag_key unique (business_id, emag_id);

comment on constraint emag_offers_business_emag_key on public.emag_offers is
  'Id-ul ofertei e unic IN CONTUL comerciantului, nu in toata baza: la eMAG fiecare '
  'vanzator isi alege singur numerotarea, iar importul o preia asa cum e. Unic global, '
  'al doilea comerciant care importa ar fi cazut pe „duplicate key" la fiecare rand.';

/* ─── 2. Sirul, ridicat peste numerotarile facute de mana ─────────────────── */

alter table public.emag_offers
  alter column emag_id restart with 1000000000;

/* ─── 3. Impingerea sirului, pentru id-urile preluate de deasupra pragului ── */

/* ═══ ⚠ SIRUL NU SE DA INAPOI LA ROLLBACK, SI ASA TREBUIE SA RAMANA ═══

   Masurat pe proiectul real, nu presupus: proba de mai jos a rulat intr-o tranzactie
   incheiata cu `raise exception`. Randurile s-au dat inapoi (0 randuri dupa), dar
   sirul a ramas la 5.000.000.001 si a trebuit repornit de mana.

   Asa lucreaza sirurile in Postgres, dinadins: daca s-ar da inapoi, doua tranzactii
   care merg deodata ar putea primi acelasi id.

   Pentru noi inseamna ca un import cazut la jumatate lasa sirul ridicat degeaba. E
   pretul CORECT: se pierd niste id-uri dintr-un `bigint`, si nu se ciocneste nimic.
   Cine ar „repara" asta punand sirul inapoi ar da acelasi `emag_id` la doua oferte,
   iar la eMAG a doua ar suprascrie-o pe prima fara sa spuna nimic. */

/* ═══ ⚠ IN `public`, NU IN `privat`, SI E O SILA IMPUSA DE POSTGREST ═══

   Prima forma o pusese in `privat`, unde stau lucrurile pe care nu le atinge nimeni
   din afara. Dar functia asta o cheama IMPORTUL, prin PostgREST — iar PostgREST nu
   vede decat schemele expuse. `admin.schema("privat").rpc(...)` nici macar nu se
   compileaza: tipurile generate din baza n-au schema aceea.

   Deci sta in `public`, dar cu drepturile retrase de la `anon` si `authenticated`.
   Verificat pe productie, nu presupus:

       anon: false | authenticated: false | service_role: true

   Adica se poate chema numai cu cheia de serviciu, ceea ce era si rostul lui
   `privat`. ⚠ Cine adauga aici alte functii sa nu uite `revoke`-ul: fara el, orice
   vizitator al magazinului ar putea impinge sirul unde vrea. */
create or replace function public.emag_ridica_sirul(p_pana_la bigint)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_acum bigint;
begin
  if p_pana_la is null or p_pana_la < 1 then
    return null;
  end if;

  select last_value into v_acum from public.emag_offers_emag_id_seq;

  /* ⚠ SE COMPARA CU `>=`, SI E DINADINS PRUDENT.

     `last_value` inseamna doua lucruri diferite, dupa `is_called`: la un sir abia
     repornit e URMATOAREA valoare care va iesi, iar la unul folosit e ULTIMA iesita.
     Cu `>=` amandoua ies bine — in cel mai rau caz se pierde un id dintr-un sir de
     noua miliarde de miliarde. Cu `>`, cazul „sir abia repornit" ar fi dat aceeasi
     valoare de doua ori.

     `false` la al treilea argument al lui `setval`: urmatorul `nextval` intoarce
     CHIAR valoarea pusa, nu una peste ea. De aceea se scrie `p_pana_la + 1`. */
  if p_pana_la >= v_acum then
    perform setval('public.emag_offers_emag_id_seq', p_pana_la + 1, false);
    return p_pana_la + 1;
  end if;

  return v_acum;
end;
$$;

comment on function public.emag_ridica_sirul(bigint) is
  'Impinge sirul lui `emag_offers.emag_id` deasupra unui id PRELUAT din eMAG. Se cheama '
  'de import, dupa ce scrie ofertele adoptate, cu cel mai mare id adus. Fara ea, un '
  'comerciant cu numerotare proprie peste 1.000.000.000 s-ar ciocni cu id-urile noastre.';

revoke all on function public.emag_ridica_sirul(bigint) from public, anon, authenticated;

commit;

notify pgrst, 'reload schema';
