/**
 * Appendix G al documentatiei MyGLS (ver. 25.12.11, paginile 44-46), copiat
 * MECANIC din PDF-ul oficial — nu transcris de mana.
 *
 * ⚠ Exista ca sa se poata compara automat cu multimile din `statusuri.ts`.
 * Fara asa ceva, verificarea „le-am acoperit pe toate?" se face pe ochi, si
 * exact asa au ramas 23 de coduri necunoscute — printre ele `92`, care inseamna
 * chiar „The parcel has been delivered.": o livrare adevarata care nu inchidea
 * comanda si nu declansa facturarea.
 *
 * Se reface descarcand `https://api.mygls.ro/docs/MyGLS_API.pdf` si extragand
 * tabelul. NU se completeaza de mana cu coduri auzite de undeva.
 */
export const APPENDIX_G: Record<number, string> = {
  1: "The parcel was handed over to GLS.",
  2: "The parcel has left the parcel center.",
  3: "The parcel has reached the parcel center.",
  4: "The parcel is expected to be delivered during the day.",
  5: "The parcel has been delivered.",
  6: "The parcel is stored in the parcel center.",
  7: "The parcel is stored in the parcel center.",
  8: "The parcel is stored in the GLS parcel center. The consignee has",
  9: "The parcel is stored in the parcel center to be delivered at a new",
  10: "Check scan normal.",
  11: "The parcel could not be delivered as the consignee is on holidays.",
  12: "The parcel could not be delivered as the consignee was absent.",
  13: "Sorting error at the depot.",
  14: "The parcel could not be delivered as the reception was closed.",
  15: "Not delivered lack of time.",
  16: "The parcel could not be delivered as the consignee had no cash",
  17: "The parcel could not be delivered as the recipient refused",
  18: "The parcel could not be delivered as further address information",
  19: "The parcel could not be delivered due to the weather condition.",
  20: "The parcel could not be delivered due to wrong or incomplete",
  21: "Forwarded sorting error.",
  22: "Parcel is sent from the depot to sorting center.",
  23: "The parcel has been returned to sender.",
  24: "The changed delivery option has been saved in the GLS system",
  25: "Forwarded misrouted.",
  26: "The parcel has reached the parcel center.",
  27: "The parcel has reached the parcel center.",
  28: "Disposed.",
  29: "Parcel is under investigation.",
  30: "Inbound damaged.",
  31: "Parcel was completely damaged.",
  32: "The parcel will be delivered in the evening.",
  33: "The parcel could not be delivered due to exceeded time frame.",
  34: "The parcel could not be delivered as acceptance has been",
  35: "Parcel was refused because the goods was not ordered.",
  36: "Consignee was not in, contact card couldn´t be left.",
  37: "Change delivery for shipper´s request.",
  38: "The parcel could not be delivered due to missing delivery note.",
  39: "Delivery note not signed.",
  40: "The parcel has been returned to sender.",
  41: "Forwarded normal.",
  42: "The parcel was disposed upon shipper´s request.",
  43: "Parcel is not to locate.",
  44: "Parcel is excluded from General Terms and Conditions.",
  46: "Change completed for Delivery address.",
  47: "The parcel has left the parcel center.",
  51: "The parcel data was entered into the GLS IT system; the parcel",
  52: "The COD data was entered into the GLS IT system.",
  53: "Depot transit.",
  54: "The parcel has been delivered to the parcel box.",
  55: "The parcel has been delivered at the ParcelShop (see ParcelShop",
  56: "Parcel is stored in GLS ParcelShop.",
  57: "The parcel has reached the maximum storage time in the",
  58: "The parcel has been delivered at the neighbour’s (see signature).",
  59: "Parcelshop pickup.",
  60: "Customs clearance is delayed due to a missing invoice.",
  61: "The customs documents are being prepared.",
  62: "Customs clearance is delayed as the consignee´s phone number is",
  64: "The parcel was released by customs.",
  65: "The parcel was released by customs. Customs clearance is carried",
  66: "Customs clearance is delayed until the consignee´s approval is",
  67: "The customs documents are being prepared.",
  68: "The parcel could not be delivered as the consignee refused to pay",
  69: "The parcel is stored in the parcel center. It cannot be delivered as",
  70: "Customs clearance is delayed due to incomplete documents.",
  71: "Customs clearance is delayed due to missing or inaccurate",
  72: "Customs data must be recorded.",
  73: "Customs parcel locked in origin country.",
  74: "Customs clearance is delayed due to a customs inspection.",
  75: "Parcel was confiscated by the Customs authorities.",
  76: "Customs data recorded, parcel can be sent do final location.",
  80: "The parcel has been forwarded to the desired address to be",
  83: "The parcel data for Pickup-Service was entered into the GLS",
  84: "The parcel label for the pickup has been produced.",
  85: "The driver has received the order to pick up the parcel during the",
  86: "The parcel has reached the parcel center.",
  87: "The pickup request has been cancelled as there were no goods to",
  88: "The parcel could not be picked up as the goods to be picked up",
  89: "The parcel could not be picked up as the customer was not",
  90: "The pickup request has been cancelled as the goods were sent by",
  91: "Pick and Ship/Return cancelled.",
  92: "The parcel has been delivered.",
  93: "Signature confirmed.",
  97: "Parcel is placed to parcellocker.",
  99: "Consignee contacted Email delivery notification.",
  401: "Parcellocker capacity problem",
  402: "Parcellocker oversized",
  403: "Parcel damaged",
  404: "Parcellocker technical issue",
  420: "Defect box",
};
