import { Store } from "lucide-react";
import type { CategorieAjutor } from "../ajutor-tipuri";

/**
 * Categoria „Marketplace” din centrul de ajutor.
 *
 * ⚠ TEXTELE SUNT CIORNĂ, scrise dintr-un audit al codului panoului, nu din cap.
 * Vezi `../ajutor.ts` pentru cum s-a făcut auditul și ce reguli de scriere se
 * aplică. Clientul le corectează.
 */
export const MARKETPLACE: CategorieAjutor = {
  slug: "marketplace",
  titlu: "Marketplace",
  descriere: "Vânzare pe eMAG, OLX, Trendyol, AboutYou și altele.",
  icon: Store,
  grupuri: [
    /*
     * ⚠ eMAG A LIPSIT CU TOTUL PÂNĂ PE 30.08, deși e canalul cel mai activ din
     * producție. Motivul: auditul din 19.08 a citit panoul de pe ramura de
     * redesign, iar integrarea eMAG trăiește pe `main`, adăugată după. S-a văzut
     * abia când căutarea a fost măsurată: „emag” întorcea zero rezultate, iar
     * cuvântul apărea o singură dată în tot centrul, în descrierea categoriei.
     *
     * Ghidurile de aici sunt scrise din codul de pe `main`, nu din cel de pe
     * ramura asta: `components/dashboard/Emag*.tsx` și `lib/emag/`. Denumirile
     * citate au fost verificate una câte una în sursa aceea.
     *
     * ⚠ „Copiaza adresa” și „Comenzi instant (optional)” se citează FĂRĂ
     * diacritice fiindcă exact așa scrie pe ecran. Un ghid care le „îndreaptă”
     * trimite omul să caute un buton care nu există sub numele ăla.
     */
    {
      titlu: "eMAG",
      ghiduri: [
        {
          slug: "cum-conectezi-contul-emag",
          titlu: "Cum conectezi contul eMAG",
          rezumat: "eMAG acceptă apeluri doar de la adrese IP trecute dinainte în contul tău, deci adresa se adaugă înaintea utilizatorului și a parolei.",
          intro: "Conectarea are un pas pe care celelalte integrări nu-l au. Dacă îl sari, utilizatorul și parola corecte sunt tot refuzate, iar refuzul nu pomenește nimic despre adrese IP.",
          pasi: [
            "Intră în Integrări > Marketplace > eMAG.",
            "Deschide blocul „Înainte de conectare: adaugă adresa noastră IP” din capul paginii și apasă „Copiaza adresa”.",
            "În panoul eMAG mergi la „Contul meu → Setări API → adrese IP permise” și adaugă acolo adresa copiată.",
            "Întoarce-te în Edinio, la cardul „Conectează contul eMAG”, și alege țara: „eMAG România”, „eMAG Bulgaria” sau „eMAG Ungaria”.",
            "Completează „Utilizator API” și „Parolă API” cu datele de API din contul tău eMAG.",
            "Salvează. La reușită apare mesajul „Cont eMAG conectat.” și cardul se schimbă în „Cont conectat”.",
          ],
          detalii: [
            { titlu: "De ce adresa IP e primul pas, nu ultimul", text: "eMAG răspunde numai apelurilor venite de la adrese pe care le-ai declarat tu în contul lor. Cât timp adresa noastră nu e acolo, orice încercare de conectare pică, iar mesajul primit vorbește despre acreditări, nu despre adresa IP. E felul de greșeală în care se caută o zi întreagă într-un loc greșit." },
            { titlu: "Datele de API nu sunt datele cu care intri tu pe eMAG", text: "„Utilizator API” și „Parolă API” se generează separat, în contul tău de vânzător. Câmpul de utilizator arată un exemplu de forma „ex. api_magazinultau”." },
            { titlu: "Parola nu se mai vede după salvare", text: "Serverul nu o trimite înapoi niciodată. După prima salvare, câmpul arată „•••••••• (salvată)”. Lăsat gol la o salvare următoare, înseamnă „nu o schimba”, nu „șterge-o”." },
            { titlu: "Cele trei țări sunt conturi diferite", text: "eMAG România, Bulgaria și Ungaria au fiecare contul lor de vânzător și fiecare propriile date de API. Alegi țara la conectare." },
          ],
          nota: "Fără adresa IP adăugată în contul eMAG, conectarea nu reușește, oricât de corecte ar fi utilizatorul și parola.",
          termeni: ["adresa ip", "ip permis", "utilizator api", "parola api", "marketplace", "vanzator emag", "seller"],
        },
        {
          slug: "cum-completezi-ce-cere-emag-inainte-de-publicare",
          titlu: "Cum completezi ce cere eMAG înainte de prima publicare",
          rezumat: "Cota de TVA și numărul de zile în care expediezi sunt cerute de eMAG pe fiecare ofertă, deci se completează o dată, înainte de primul produs trimis.",
          pasi: [
            "În pagina eMAG, deschide blocul „Ce cere eMAG înainte de prima publicare”.",
            "Alege „Cota de TVA” cu care pleacă ofertele tale.",
            "Completează „În câte zile expediezi”. Dacă expediezi în ziua comenzii, alegerea este „În aceeași zi”.",
            "Salvează. Apare mesajul „Salvat. Acum poți publica produse pe eMAG.”",
          ],
          detalii: [
            { titlu: "Fără ele nu pleacă niciun produs", text: "Cât timp blocul nu e completat, pagina arată „Integrarea nu este încă pregătită”, iar trimiterea produselor nu se poate porni. Sunt date pe care eMAG le cere pe fiecare ofertă, nu preferințe ale noastre." },
            { titlu: "Se completează o singură dată", text: "Valorile se aplică ofertelor pe care le trimiți de aici înainte. Se pot schimba oricând din același bloc." },
          ],
          termeni: ["tva", "zile de expediere", "handling time", "pregatire publicare", "prima publicare"],
        },
        {
          slug: "cum-completezi-datele-gpsr-pentru-emag",
          titlu: "Cum completezi datele GPSR pentru ofertele de pe eMAG",
          rezumat: "Producătorul, reprezentantul din UE și avertismentele de siguranță sunt cerute de regulamentul european și pleacă la toate ofertele tale.",
          pasi: [
            "În pagina eMAG, deschide blocul „Date GPSR”.",
            "Completează „Producător” cu datele producătorului produselor tale.",
            "Completează „Reprezentant în UE”, dacă producătorul este din afara Uniunii Europene.",
            "Completează „Avertismente de siguranță”, dacă produsele tale cer așa ceva. Câmpul arată un exemplu de forma „Ex.: A nu se lăsa la îndemâna copiilor sub 3 ani.”",
            "Apasă „Salvează datele GPSR”. Apare mesajul „Salvat. Datele pleacă la ofertele tale în câteva minute.”",
          ],
          detalii: [
            { titlu: "Datele nu pleacă pe loc", text: "După salvare, ele se trimit către ofertele deja publicate în câteva minute, nu instantaneu. Mesajul de confirmare spune chiar asta." },
            { titlu: "Se aplică tuturor ofertelor", text: "Sunt date de magazin, nu de produs: se completează o dată și merg pe tot ce ai pe eMAG." },
          ],
          nota: "GPSR este o cerință legală europeană pentru siguranța produselor, nu o opțiune a platformei.",
          termeni: ["gpsr", "producator", "reprezentant ue", "avertismente", "siguranta produsului", "conformitate"],
        },
        {
          slug: "cum-legi-categoriile-de-emag",
          titlu: "Cum legi categoriile magazinului de categoriile eMAG",
          rezumat: "Fiecare categorie a ta primește o categorie eMAG, iar fără legătura asta produsele din ea nu se pot trimite.",
          pasi: [
            "În pagina eMAG, deschide blocul „Leagă categoriile de eMAG”.",
            "Apasă „Sugestii”. Până nu o faci, listele sunt goale: ecranul spune „Apasă întâi «Sugestii», ca să aducem raftul de categorii al eMAG.”",
            "Când apare „Sugestii pregătite.”, verifică propunerea de pe fiecare rând.",
            "Unde propunerea nu e bună, folosește „Caută categoria eMAG după nume” sau scrie direct „Id categorie eMAG”.",
            "Categoriile rămase fără pereche poartă eticheta „Nelegată”.",
          ],
          detalii: [
            { titlu: "Ce se întâmplă dacă o categorie rămâne nelegată", text: "Produsele din ea nu se trimit pe eMAG. Ecranul arată „O categorie nu e legată” și nu te lasă să pornești publicarea pentru ea." },
            { titlu: "Când scoți o legătură", text: "Apare „Legătura a fost scoasă. Ofertele deja publicate rămân pe eMAG.” Scoaterea oprește trimiterile viitoare, nu retrage ce e deja acolo." },
            { titlu: "Grupul de variante", text: "Câmpul „Grup de variante” spune cum se strâng variantele aceluiași produs într-o singură ofertă pe eMAG. Produsele fără grup apar ca „Fără grup”." },
            { titlu: "Categoriile goale", text: "Dacă o categorie nu are niciun produs activ, ecranul spune „Nu e niciun produs activ în categoria asta.” Legătura se poate face oricum, pentru mai târziu." },
          ],
          termeni: ["mapare categorii", "categorie emag", "id categorie", "sugestii", "nelegata", "taxonomie"],
        },
        {
          slug: "cum-legi-produsele-cu-ofertele-de-pe-emag",
          titlu: "Cum legi produsele cu ofertele tale de pe eMAG",
          rezumat: "Dacă vindeai pe eMAG înainte de Edinio, ofertele existente se leagă de produsele tale, ca să nu se creeze duplicate.",
          intro: "Pasul ăsta se face o singură dată, la început. Fără el, o publicare nouă ar crea a doua ofertă pe aceeași pagină de produs de pe eMAG.",
          pasi: [
            "În pagina eMAG, deschide blocul „Leagă produsele cu ofertele tale de pe eMAG”.",
            "Apasă butonul „Leagă produsele”. Ecranul arată pe rând „Se citește lista de pe eMAG…”, apoi „Se creează produsele…” și „Se leagă produsele…”.",
            "Urmărește cifrele de la final: câte oferte au fost „Legate de produse” și câte au rămas „De lămurit”.",
            "Ofertele pe care eMAG le are și magazinul tău nu, apar ca „Doar pe eMAG”.",
          ],
          detalii: [
            { titlu: "Pe cataloage mari, munca se termină în fundal", text: "Ecranul spune „Ai un catalog mare, iar restul produselor se creează în fundal.” și „Poți închide pagina; revino în câteva minute.” Nu trebuie să stai pe pagină." },
            { titlu: "De ce se leagă înainte de a publica", text: "eMAG nu permite două oferte ale aceluiași vânzător pe aceeași pagină de produs. O publicare făcută înaintea legării se lovește de asta, iar oferta nu se creează." },
            { titlu: "Ce înseamnă „De lămurit”", text: "Sunt ofertele pe care nu le-am putut potrivi singuri cu un produs din magazin, de obicei fiindcă nu se potrivește codul. Rămân în listă până le rezolvi." },
          ],
          termeni: ["import oferte", "leaga produsele", "duplicat", "oferta existenta", "doar pe emag", "de lamurit"],
        },
        {
          slug: "cum-trimiti-produse-noi-pe-emag",
          titlu: "Cum trimiți produse noi pe eMAG",
          rezumat: "Alegi produsele din listă, completezi marca acolo unde lipsește, și pleacă la validare.",
          pasi: [
            "În pagina eMAG, deschide lista produselor de publicat.",
            "Restrânge lista cu „Caută după nume sau SKU” sau cu lista de categorii, unde „Toate categoriile” e valoarea de pornire.",
            "Bifează produsele. Butonul „Deselectează pagina” golește selecția de pe pagina curentă.",
            "Completează „Marca produsului” unde e goală. Fără ea, produsul nu pleacă: ecranul cere „Scrie marca produsului.”",
            "Trimite selecția. Ecranul spune „Pleacă în următoarele minute; validarea la eMAG durează ore.”",
          ],
          detalii: [
            { titlu: "Trimiterea și validarea sunt două lucruri diferite", text: "Din Edinio produsele pleacă în câteva minute. Ce urmează după e la eMAG, iar validarea lor durează ore. Până se termină, oferta stă în starea „În validare la eMAG”." },
            { titlu: "Când lista pare goală", text: "Dacă filtrele nu lasă nimic, ecranul spune „Nimic aici cu filtrele astea.” Golește căutarea sau alege „Toate categoriile”." },
            { titlu: "Publicarea automată a produselor noi", text: "Comutatorul „Publică automat produsele noi” din pagina eMAG trimite singur produsele adăugate de acum înainte. Cele existente rămân de trimis manual." },
          ],
          nota: "Marca este obligatorie la eMAG. Un produs fără marcă nu se trimite, oricâte alte câmpuri ar fi completate.",
          termeni: ["publicare", "produse noi", "marca", "brand", "validare", "trimite pe emag"],
        },
        {
          slug: "cum-citesti-starea-ofertelor-de-pe-emag",
          titlu: "Cum citești starea ofertelor tale de pe eMAG",
          rezumat: "Cele nouă stări din „Ofertele tale pe eMAG” spun de ce un produs se vinde sau nu, iar ordinea lor e de la cel mai grav la cel mai bun.",
          pasi: [
            "În pagina eMAG, deschide blocul „Ofertele tale pe eMAG”.",
            {
              text: "Citește cartonașele de stare de deasupra listei. Sunt așezate în ordinea gravității, de la „Respins de eMAG” până la „Se vinde pe eMAG”.",
              captura: { alt: "Cartonașele de stare de deasupra listei de oferte eMAG, cu numărul de oferte pe fiecare.", raport: 16 / 10 },
            },
            "Apasă un cartonaș ca să vezi doar ofertele din starea aceea.",
            "Caută o ofertă anume cu „Caută după SKU sau cod de bare”.",
          ],
          detalii: [
            { titlu: "Ce înseamnă fiecare stare", text: "„Respins de eMAG”: oferta a fost refuzată și nu se vinde. „În validare la eMAG”: e trimisă și așteaptă la ei. „Scoasă din vânzare la eMAG”: ei au retras-o. „Oprită la eMAG”: e oprită din contul tău. „Preț neacceptat de eMAG”: prețul trimis nu trece de regulile lor. „Fără stoc la eMAG”: stocul ajuns la ei este zero. „Încă necitit de la eMAG”: n-am apucat să citim starea. „Stare necunoscută la eMAG”: am citit, dar răspunsul nu spune. „Se vinde pe eMAG”: totul e în regulă." },
            { titlu: "Butonul de cumpărare și competiția", text: "Pe rândul unei oferte care se vinde poate scrie „Ai butonul de cumpărare” sau „În competiție”. Al doilea înseamnă că mai sunt vânzători pe aceeași pagină de produs, iar butonul nu e al tău." },
            { titlu: "Ofertele care cer o reparație", text: "Eticheta „De reparat” strânge ofertele cu o problemă de rezolvat de tine. „Doar pe eMAG” sunt cele care există la ei, dar n-au produs în magazinul tău." },
          ],
          termeni: ["stare oferta", "respins", "in validare", "fara stoc", "buy button", "buton de cumparare", "competitie"],
        },
        {
          slug: "cum-opresti-o-oferta-de-pe-emag",
          titlu: "Cum oprești o ofertă de pe eMAG, și ce oprești de fapt",
          rezumat: "Sunt două opriri diferite pe același rând: una scoate oferta din vânzare, cealaltă doar nu-i mai trimite prețul și stocul.",
          intro: "Cele două se confundă ușor, iar urmările sunt cu totul altele. Prima oprește vânzarea. A doua lasă oferta să se vândă mai departe, dar cu prețul și stocul înghețate la ce era în clipa opririi.",
          pasi: [
            "În „Ofertele tale pe eMAG”, găsește rândul ofertei.",
            "Ca să scoți oferta din vânzare, folosește butonul cu titlul „Oprește de la vânzare pe eMAG”. Apare mesajul „Oferta a fost oprită de la vânzare. Rămâne în contul tău eMAG.”",
            "Ca să oprești doar trimiterile, apasă butonul „Nu mai trimite”, cu titlul „Oprește trimiterea automată a prețului și stocului”.",
            "Butonul se schimbă în „Trimite automat”, cu titlul „Lasă Edinio să conducă prețul și stocul”. Apăsat din nou, apare „Prețul și stocul din Edinio vor conduce de acum oferta de pe eMAG.”",
          ],
          detalii: [
            { titlu: "Oprirea din vânzare nu șterge nimic", text: "Oferta rămâne în contul tău de pe eMAG, doar că nu se mai vinde. Se repune din panoul lor sau retrimițând-o din Edinio." },
            { titlu: "Oprirea trimiterilor e cea periculoasă pe termen lung", text: "Oferta se vinde mai departe, dar cu prețul și stocul de la ultima trimitere. Dacă vinzi produsul și în magazin, stocul de pe eMAG nu mai scade, iar comenzile pot intra peste ce nu mai ai." },
          ],
          nota: "Cele două butoane stau unul lângă altul pe același rând. Citește titlul care apare la trecerea cu mausul înainte să apeși.",
          termeni: ["opreste oferta", "nu mai trimite", "trimite automat", "pauza", "sincronizare pret stoc"],
        },
        {
          slug: "cum-aduci-comenzile-din-emag",
          titlu: "Cum aduci comenzile din eMAG în panou",
          rezumat: "Comenzile vin singure, iar pentru cele dinaintea conectării există un buton separat.",
          pasi: [
            "În pagina eMAG, apasă „Sincronizează acum” ca să ceri pe loc o citire, fără să aștepți rândul obișnuit.",
            "Pentru comenzile de dinaintea conectării, apasă „Adu comenzile vechi”.",
            "Dacă nu e nimic de adus, ecranul răspunde „Nicio comandă nouă.”",
            "Comenzile aduse apar în Comenzi, la fel ca cele din magazin.",
          ],
          detalii: [
            { titlu: "Comenzi instant", text: "Comutatorul „Comenzi instant (optional)” face ca eMAG să ne anunțe imediat ce intră o comandă, în loc să așteptăm următoarea citire. Numele e scris fără diacritice chiar pe ecran." },
            { titlu: "Când eMAG are altceva decât Edinio", text: "Blocul cu numele ăsta stabilește cine are dreptate la o nepotrivire între cele două. Se citește înainte de prima sincronizare mare, fiindcă hotărăște ce se suprascrie." },
            { titlu: "Când nu e nimic de sincronizat", text: "La oferte, răspunsul este „Nicio ofertă de sincronizat.”, iar la o pornire fără lucrări în așteptare, „Nu era nimic de pornit.”" },
          ],
          termeni: ["comenzi emag", "sincronizare", "comenzi vechi", "istoric", "webhook", "comenzi instant"],
        },
        {
          slug: "cum-emiti-awb-pentru-o-comanda-emag",
          titlu: "Cum emiți AWB pentru o comandă venită de pe eMAG",
          rezumat: "Curierul eMAG se cheamă din comandă, cu greutatea și numărul de colete luate din fișele produselor.",
          pasi: [
            "Deschide comanda venită de pe eMAG.",
            "Deschide fereastra de AWB. Verifică „Destinatar” și adresa de ridicare.",
            "Verifică „Câte colete” și „Greutate totală (kg)”. Sunt luate din fișele produselor.",
            "Verifică „De încasat la livrare”. La o comandă deja plătită scrie „Nimic de încasat, comanda e plătită”.",
            "Completează „Observații pentru curier”, dacă e cazul, și emite AWB-ul.",
          ],
          detalii: [
            { titlu: "De unde vin greutatea și coletele", text: "Ecranul spune „Luate din fișa produsului. Schimbă-le dacă ambalajul e altfel.” Dacă expediezi altfel decât e trecut la produs, schimbă valorile aici, nu în produs." },
            { titlu: "De ce contează dimensiunile", text: "Sub câmpuri scrie „Le folosește eMAG la calculul volumetric.” Un colet mare și ușor se taxează după volum, nu după greutate." },
          ],
          termeni: ["awb emag", "curier emag", "colete", "greutate", "ramburs", "volumetric"],
        },
        {
          slug: "cum-rezolvi-un-retur-de-pe-emag",
          titlu: "Cum rezolvi o cerere de retur venită de pe eMAG",
          rezumat: "Vezi cererea, contul în care se întorc banii, și poți chema curierul să ridice marfa de la client.",
          pasi: [
            "În pagina eMAG, deschide lista de retururi.",
            "Citește rândul cererii. Sub el scrie „Banii se întorc în contul:” cu contul indicat de client.",
            "Ca să ridici marfa, cere chemarea curierului și confirmă întrebarea „Chem curierul să ridice marfa de la client?”.",
            "La reușită apare „Curierul a fost chemat.”",
          ],
          detalii: [
            { titlu: "Când AWB-ul e deja emis", text: "Răspunsul este „AWB-ul era deja emis.” Nu se emite un al doilea pentru aceeași cerere." },
            { titlu: "Ce nu se poate face de aici", text: "Ecranul spune direct: „Transportul se plătește, iar AWB-ul nu se poate anula de aici.” Anularea se face din panoul eMAG." },
            { titlu: "Cererile fără comandă", text: "Un retur care nu se leagă de nicio comandă din panou apare ca „Fără comandă legată”. Unde nu e nimic de făcut, rândul spune „Nimic de făcut”." },
          ],
          termeni: ["retur emag", "rma", "chem curierul", "ridicare de la client", "restituire", "bani inapoi"],
        },
      ],
    },
    {
      titlu: "Restul marketplace-urilor",
      ghiduri: [
        {
          slug: "cum-conectezi-contul-olx",
          titlu: "Cum conectezi contul OLX la magazinul tău",
          rezumat: "Autorizezi contul tău OLX.ro o singură dată, iar Edinio poate publica și sincroniza anunțuri.",
          pasi: [
            "Intră în Integrări > Marketplace > OLX.",
            "Citește ecranul „Conectează contul OLX”.",
            "Apasă „Conectează OLX”. Butonul devine „Se deschide OLX...” și ești dus pe site-ul OLX.",
            "Autorizează accesul din contul tău OLX.",
            "La revenire în Edinio vezi mesajul „Cont OLX conectat.” și banda „Conectat la OLX”, cu numele contului și tipul lui, „Firmă” sau „Persoană fizică”.",
          ],
          detalii: [
            { titlu: "Ce e al tău și ce face Edinio", text: "Contul de pe OLX.ro trebuie să fie al tău, iar autorizarea se face pe site-ul OLX. Edinio face legătura și gestionează anunțurile după aceea." },
            { titlu: "Dacă pagina arată „Disponibil în curând”", text: "Înseamnă că integrarea nu e configurată pe serverul nostru. Vezi textul „Integrarea OLX se activează în curând pentru magazinul tău. Revino mai târziu.” și nu ai ce acțiune să faci din panou." },
            { titlu: "Dacă autorizarea nu reușește", text: "Poți primi „Conectarea OLX a eșuat. Încearcă din nou.” sau „Reconectează-te și acceptă accesul.” Reia apăsarea pe „Conectează OLX” și acceptă accesul cerut pe pagina OLX." },
            { titlu: "Când expiră sesiunea", text: "Apare avertismentul „Sesiunea OLX a expirat.” cu linkul „Reconectează contul OLX”. Până reconectezi, sincronizarea nu funcționează." },
            { titlu: "Ce urmează după conectare", text: "Înainte de a publica ceva ai de completat setările anunțurilor și de mapat categoriile magazinului la categoriile OLX." },
          ],
          termeni: ["olx.ro", "autorizare olx", "anunturi olx", "sesiune expirata"],
        },
        {
          slug: "cum-completezi-setarile-anunturilor-olx",
          titlu: "Cum completezi setările anunțurilor OLX",
          rezumat: "Localitatea, numele și telefonul de contact sunt obligatorii, altfel nu poți publica niciun anunț.",
          pasi: [
            "Intră în Integrări > Marketplace > OLX.",
            "Apasă „Setări” în banda „Conectat la OLX”. Dacă setările nu sunt complete, secțiunea se deschide singură.",
            "La „Tip vânzător” alege „Persoană fizică” sau „Firmă”.",
            "La „Localitate” scrie cel puțin două litere în câmpul „Caută orașul...” și alege orașul din listă. Sub fiecare oraș scrie județul.",
            "Dacă orașul are cartiere, alege unul la „Cartier (opțional)” sau lasă opțiunea goală din capul listei.",
            "Completează „Nume de contact” și „Telefon de contact”. Ambele sunt obligatorii.",
            "Bifează, dacă vrei, „Livrare prin OLX”, „Sincronizare automată” și „Reînnoire automată”.",
            "Apasă „Salvează setările”. Confirmarea este „Setări salvate.”",
          ],
          detalii: [
            { titlu: "Ce înseamnă câmpurile de contact", text: "„Nume de contact” este numele afișat pe anunț, iar „Telefon de contact” se scrie în formatul 07xxxxxxxx. Sunt datele pe care le vede cumpărătorul pe OLX." },
            { titlu: "Mesajele de validare", text: "Fără localitate primești „Alege localitatea.”, fără nume „Completează numele de contact.”, fără telefon „Completează telefonul de contact.” Salvarea nu trece până nu completezi." },
            { titlu: "De ce e blocat butonul „Publică tot”", text: "Cât timp setările nu sunt complete, butonul „Publică tot” e dezactivat și deasupra apare motivul, urmat de îndemnul de a completa în Setări. Motivele posibile sunt: contul OLX neconectat, sesiunea OLX expirată, localitatea nesetată, numele de contact lipsă sau telefonul de contact lipsă." },
            { titlu: "Bifele de automatizare", text: "„Sincronizare automată” ține anunțurile aliniate cu produsele tale, „Reînnoire automată” se ocupă de reînnoirea anunțurilor, iar „Livrare prin OLX” marchează anunțurile ca fiind cu livrare prin OLX." },
          ],
          termeni: ["localitate anunt", "telefon contact olx", "tip vanzator", "reinnoire automata", "livrare prin olx"],
        },
        {
          slug: "cum-mapezi-categoriile-la-olx",
          titlu: "Cum mapezi categoriile magazinului la categoriile OLX",
          rezumat: "Fiecare categorie a ta trebuie legată de o categorie OLX, altfel produsele din ea nu se publică.",
          pasi: [
            "Intră în Integrări > Marketplace > OLX și derulează la cardul „Mapare categorii”.",
            "Apasă „Mapează” în dreptul categoriei tale. Dacă are deja o mapare, butonul se numește „Editează”.",
            "În fereastra care se deschide alege tabul „Sugestii” sau tabul „Răsfoiește”.",
            "În „Sugestii” scrie cel puțin trei litere, de exemplu telefon sau rochie, apoi apasă sugestia potrivită.",
            "În „Răsfoiește” pornești de la „Toate” și cobori din categorie în categorie până la una finală, marcată cu bifă.",
            "Completează câmpurile din secțiunea „Atribute categorie”. Cele obligatorii sunt marcate cu asterisc.",
            "Apasă „Salvează maparea”. Confirmarea este „Mapare salvată.”",
          ],
          detalii: [
            { titlu: "Cum citești cardul", text: "Textul cardului arată câte categorii sunt mapate din total, sub forma X/Y. Categoriile fără legătură apar cu eticheta „Nemapată”." },
            { titlu: "Când căutarea nu dă rezultate", text: "Sub trei litere vezi „Scrie cel puțin 3 litere pentru sugestii.” Dacă nu găsește nimic, vezi „Nicio sugestie. Încearcă „Răsfoiește”.” și continui manual din arbore." },
            { titlu: "Atributele categoriei", text: "Câmpurile diferă de la o categorie OLX la alta. Listele au o opțiune goală la început, iar atributele cu mai multe valori se bifează ca etichete. Dacă nu sunt atribute, vezi „Această categorie nu cere atribute suplimentare.” Dacă lași un atribut obligatoriu gol, primești „Completează atributele obligatorii:” cu lista lor și maparea nu se salvează." },
            { titlu: "Schimbarea sau ștergerea unei mapări", text: "După ce ai ales o categorie OLX apare caseta „Categorie OLX aleasă” cu butonul „Schimbă”. La o mapare existentă ai și „Șterge maparea”, cu mesajul „Mapare ștearsă.”" },
            { titlu: "Dacă nu ai categorii în magazin", text: "Cardul afișează doar „Adaugă categorii produselor tale ca să le poți mapa la categoriile OLX.” Pune întâi categorii pe produse." },
          ],
          nota: "Produsele din categoriile nemapate nu se publică deloc pe OLX.",
          termeni: ["categorie olx", "atribute categorie", "nemapata", "rasfoieste", "sugestii"],
        },
        {
          slug: "cum-publici-toate-produsele-pe-olx",
          titlu: "Cum publici toate produsele ca anunțuri pe OLX",
          rezumat: "Butonul „Publică tot” pune în coadă toate produsele active care au categoria mapată.",
          pasi: [
            "Intră în Integrări > Marketplace > OLX.",
            "Verifică în banda de sus că butonul „Publică tot” nu e dezactivat.",
            "Apasă „Publică tot”.",
            "Citește mesajul de confirmare. Vezi câte produse au fost adăugate la publicare sau, dacă nu e nimic eligibil, „Niciun produs mapat de publicat.”",
            "Rămâi pe pagină și urmărește caseta care arată câte produse se publică.",
          ],
          detalii: [
            { titlu: "Ce condiții trebuie îndeplinite", text: "Setările OLX trebuie completate, adică localitate, nume și telefon de contact. Ai nevoie și de cel puțin o categorie mapată, altfel primești mesajul care îți cere să mapezi întâi o categorie la OLX." },
            { titlu: "Ce intră în coadă", text: "Se pun în coadă doar produsele active care au o categorie mapată. Restul sunt sărite." },
            { titlu: "Cât durează", text: "Caseta de pe ecran spune că produsele se procesează automat, câteva pe minut, și că poți rămâne pe pagină pentru că statusul se actualizează singur." },
          ],
          termeni: ["publica tot", "coada publicare", "produse active olx"],
        },
        {
          slug: "cum-urmaresti-anunturile-olx",
          titlu: "Cum urmărești starea anunțurilor tale pe OLX",
          rezumat: "Lista „Anunțuri pe OLX” arată starea fiecărui anunț și îți dă acțiunile pe rând.",
          pasi: [
            "Intră în Integrări > Marketplace > OLX.",
            "Citește cele patru contoare de sus: „Anunțuri”, „Active”, „În așteptare”, „Respinse”.",
            "Derulează la lista „Anunțuri pe OLX”.",
            "Uită-te pe fiecare rând la eticheta de stare, la numele produsului, la linkul către anunțul de pe OLX și la textul de dedesubt, „Sincronizat”, „În coadă” sau mesajul de eroare.",
            "Apasă iconița acțiunii dorite de pe rând. Numele acțiunii apare când treci cu mouse-ul peste ea.",
          ],
          detalii: [
            { titlu: "Ce stări poate avea un anunț", text: "Activ, În moderare, Neplătit, Limită atinsă, Dezactivat, Expirat, Respins, Blocat, Dezactivat de OLX, Șters de OLX, Eroare." },
            { titlu: "Acțiunile de pe rând", text: "Rândurile au iconițe fără text. Numele acțiunii apare la trecerea cu mouse-ul: Republică, Dezactivează, Activează, Cumpără pachet și activează, Șterge anunțul. „Dezactivează” apare doar la anunțurile active sau în moderare, „Activează” doar la cele dezactivate sau expirate, iar „Cumpără pachet și activează” doar la starea Limită atinsă." },
            { titlu: "Confirmările cerute", text: "La cumpărarea unui pachet ești întrebat dacă vrei să cumperi un pachet pentru acel anunț, plătit din creditul contului tău OLX, și să îl activezi. Confirmarea reușitei este „Pachet cumpărat, anunț activat.” La ștergere ești avertizat că acțiunea nu poate fi anulată, iar mesajul final este „Anunț șters de pe OLX.”" },
            { titlu: "Anunțuri la limita gratuită", text: "Când ai anunțuri în starea Limită atinsă, apare un avertisment care îți spune câte sunt și de unde cumperi pachetul, din secțiunea „Cont OLX” de mai jos în pagină." },
            { titlu: "Dacă lista e goală", text: "Vezi „Încă niciun anunț publicat. Apasă „Publică tot” sau publică produse individual.” Dacă setările lipsesc, textul îți cere întâi să completezi setările și să mapezi categoriile." },
          ],
          nota: "Lista afișează cel mult 200 de anunțuri.",
          termeni: ["stare anunt", "limita atinsa", "in moderare", "respins", "sincronizat"],
        },
        {
          slug: "cum-cumperi-pachete-si-promovezi-pe-olx",
          titlu: "Cum vezi soldul OLX, cumperi pachete și promovezi un anunț",
          rezumat: "Din secțiunea de cont OLX vezi creditul disponibil și cumperi pachete de anunțuri sau promovări.",
          pasi: [
            "Intră în Integrări > Marketplace > OLX și apasă rândul „Cont OLX: sold, pachete și promovări”.",
            "Verifică cele trei casete: „Sold total”, „Portofel”, „Bonus”.",
            "La „Cumpără pachet de anunțuri” alege categoria, apoi pachetul din listă și, dacă ți se cere, metoda de plată.",
            "Apasă „Cumpără”. Confirmarea este „Pachet cumpărat.”",
            "La „Promovează un anunț” alege anunțul, apoi promovarea și, dacă ți se cere, metoda de plată.",
            "Apasă „Promovează”. Confirmarea este „Promovare activată.”",
          ],
          detalii: [
            { titlu: "De unde vin banii", text: "Plățile se fac din creditul contului tău OLX. Alimentarea portofelului cu cardul se face pe olx.ro, nu din Edinio. Cumpărarea pachetelor și a promovărilor se face direct din panou. Dacă ai activată plata pe factură, apare și mențiunea despre postpaid, iar la metoda de plată poți alege între „Din credit” și „Pe factură”." },
            { titlu: "Pachetele active", text: "Pachetele deja cumpărate apar la „Pachete active”, cu numărul de anunțuri rămase și data până la care sunt valabile." },
            { titlu: "Condiția pentru pachete", text: "Pachetele sunt per categorie, deci ai nevoie de cel puțin o categorie mapată. Fără mapare vezi textul care îți cere să mapezi întâi o categorie la OLX ca să vezi pachetele. Dacă nu există pachete pentru categoriile tale, vezi „Nu sunt pachete disponibile pentru categoriile tale în acest moment.”" },
            { titlu: "Când nu apare secțiunea de promovare", text: "„Promovează un anunț” nu se afișează dacă nu ai anunțuri active sau la limită, ori dacă OLX nu returnează promovări." },
            { titlu: "Erori la plată", text: "Sold insuficient îți cere să alimentezi portofelul pe olx.ro, pentru că plata cu cardul nu e disponibilă prin API. Dacă plata pe factură nu e activată pe contul tău OLX, mesajul te trimite la suportul OLX. Mai pot apărea metoda de plată indisponibilă pe contul tău sau mărimea de pachet indisponibilă pentru acea categorie, caz în care alegi altă mărime." },
            { titlu: "Dacă soldul nu se încarcă", text: "Vezi „Nu am putut încărca soldul contului OLX.” Reîncarcă pagina, iar dacă persistă verifică dacă sesiunea OLX mai e validă." },
          ],
          nota: "Lista pachetelor și a promovărilor, cu prețurile lor, vine direct de la OLX și se poate schimba.",
          termeni: ["credit olx", "portofel", "bonus", "postpaid", "promovare anunt", "pachet anunturi"],
        },
        {
          slug: "cum-raspunzi-mesajelor-olx",
          titlu: "Cum citești și răspunzi mesajelor de la cumpărători pe OLX",
          rezumat: "Conversațiile de pe anunțurile tale OLX se citesc și se continuă direct din panou.",
          pasi: [
            "Intră în Integrări > Marketplace > OLX și derulează la cardul „Mesaje de la cumpărători”.",
            "Apasă „Deschide”. În paranteză vezi numărul de conversații.",
            "Alege o conversație din lista din stânga.",
            "Citește mesajele din dreapta. Sus vezi numele cumpărătorului și cardul anunțului, cu titlu și preț, apasabil către OLX.",
            "Scrie răspunsul în câmpul „Scrie un mesaj...” și trimite-l cu butonul de trimitere sau cu tasta Enter. Shift plus Enter face rând nou.",
          ],
          detalii: [
            { titlu: "Mesajele necitite", text: "Dacă ai mesaje noi, pe card apare o etichetă cu numărul lor." },
            { titlu: "Cum arată o conversație în listă", text: "Fiecare conversație afișează numele produsului, numărul de mesaje și data. Dacă produsul nu mai poate fi identificat, în locul numelui apare numărul anunțului sau al conversației." },
            { titlu: "Pe telefon", text: "Vezi întâi lista de conversații și intri în una apăsând pe ea." },
            { titlu: "Mesaje care lipsesc", text: "Fără conversații vezi „Nicio conversație încă.” Dacă nu ai selectat niciuna, vezi „Selectează o conversație din stânga.” Într-o conversație goală vezi „Niciun mesaj în această conversație.”" },
          ],
          termeni: ["mesagerie olx", "conversatii cumparatori", "chat olx"],
        },
        {
          slug: "cum-conectezi-contul-about-you",
          titlu: "Cum conectezi contul About You cu cheia API",
          rezumat: "Generezi o cheie API în Seller Center și o lipești în Edinio ca să legi contul.",
          pasi: [
            "Intră în Integrări > Marketplace > About You.",
            "Citește caseta „Înainte de a începe” și verifică dacă îndeplinești cele patru cerințe.",
            "În contul tău About You mergi în Seller Center la Settings > API Keys > + Add și generează o cheie. Copiaz-o pe loc, se afișează o singură dată.",
            "În Edinio, în cardul „Conectează contul About You”, alege „Mediu”: „Producție (date reale)” sau „Sandbox (testare)”.",
            "Lipește cheia în câmpul „Cheie API”.",
            "Apasă „Conectează și testează”. Confirmarea este „Cont About You conectat.”",
          ],
          detalii: [
            { titlu: "Ce trebuie să ai înainte", text: "Contul About You Seller Center aprobat, cu contract și verificare, este al tău. Ai nevoie de produse fashion sau lifestyle cu brand aprobat pe About You și de cod EAN pentru fiecare mărime. Prețurile pe About You sunt în euro, iar conversia din lei o face Edinio." },
            { titlu: "Ce vezi după conectare", text: "Cardul devine „Cont conectat”, cu eticheta „Sandbox” sau „Producție”, cheia mascată și patru contoare: „Listări”, „Publicate”, „Respinse”, „În coadă”." },
            { titlu: "Dacă cheia nu e acceptată", text: "O cheie mai scurtă de 8 caractere e respinsă din start, cu mesajul care îți cere să introduci cheia din Seller Center. Dacă serverul o respinge, mesajul îți spune să o copiezi din Seller Center > Settings > API Keys. Când testarea eșuează din partea About You, în panou apare exact răspunsul primit de la ei." },
            { titlu: "Dacă integrarea e oprită", text: "Vezi doar „Integrarea About You este momentan indisponibilă. Revino în curând.” și nu ai ce configura." },
            { titlu: "Sesiune expirată", text: "Dacă apare „Sesiunea a expirat. Reconectează cheia API.”, generează o cheie nouă în Seller Center și repetă conectarea." },
          ],
          termeni: ["seller center", "api key", "sandbox", "cheie api about you", "ean"],
        },
        {
          slug: "cum-completezi-setarile-about-you",
          titlu: "Cum completezi setările de preț, brand și țări pentru About You",
          rezumat: "Cursul valutar, brandul și țările de listare trebuie completate înainte de a trimite produse.",
          pasi: [
            "Intră în Integrări > Marketplace > About You și mergi la cardul „Setări”.",
            "Completează „Curs 1 EUR (în RON)”, de exemplu 4.97.",
            "Completează „Marjă preț (%)”, de exemplu 5.",
            "Completează „ID brand About You”.",
            "Completează „Țară de origine (ISO2)”. Implicit este RO și acceptă maximum două caractere.",
            "Completează „Țări de listare (coduri ISO2, separate prin virgulă)”, de exemplu RO, DE, AT.",
            "Bifează sau debifează „Sincronizează automat schimbările de produs, stoc și preț”.",
            "Apasă „Salvează setările”. Confirmarea este „Setări salvate.”",
          ],
          detalii: [
            { titlu: "Cum se calculează prețul", text: "Prețurile tale sunt în lei, iar About You le cere în euro. Cursul pe care îl scrii aici este folosit la conversie, iar marja se adaugă peste. Sub câmpul de curs vezi data ultimei actualizări." },
            { titlu: "Brandul se scrie ca număr", text: "„ID brand About You” cere un ID numeric, nu un nume. Câmpul are ca text de ghidaj mențiunea că selectorul cu branduri vine în pasul următor." },
            { titlu: "Mesaje de validare", text: "Un curs care nu e pozitiv dă „Cursul RON -> EUR trebuie să fie un număr pozitiv.”, o marjă negativă dă „Marja trebuie să fie un număr pozitiv.”, iar un brand care nu e număr întreg dă „ID-ul de brand trebuie să fie un număr întreg.”" },
            { titlu: "Ce îți lipsește încă", text: "Cât timp configurarea nu e gata, în banda de sus apare motivul: să alegi brandul About You în setări, să alegi cel puțin o țară de listare sau să setezi cursul valutar. Când totul e pus, textul devine „Configurarea de bază este completă. Maparea produselor și listarea vin în pasul următor.”" },
            { titlu: "Livrarea", text: "Nota din josul cardului spune că livrarea folosește curierii tăi din Edinio, în regim de dropshipping, iar tracking-ul se trimite automat către About You." },
          ],
          termeni: ["curs valutar", "marja pret", "iso2", "tari de listare", "brand about you"],
        },
        {
          slug: "cum-pornesti-notificarile-de-stoc-about-you",
          titlu: "Cum pornești sau oprești notificările de stoc About You",
          rezumat: "Cu notificările active, stocul se sincronizează în ambele sensuri.",
          pasi: [
            "Intră în Integrări > Marketplace > About You și mergi la cardul „Setări”.",
            "Derulează în josul cardului până la rândul „Notificări About You (stoc)”.",
            "Citește starea de sub titlu. Scrie fie „Active”, urmat de precizarea că stocul se sincronizează în ambele sensuri, fie „Inactive.”",
            "Apasă „Activează” sau „Dezactivează”. Confirmarea este „Notificări activate.” sau „Notificări dezactivate.”",
          ],
          detalii: [
            { titlu: "Când ai nevoie de ele", text: "Notificările sunt utile după ce ai listări trimise pe About You, ca stocul din magazin și cel de pe marketplace să rămână aliniate. Contul About You trebuie să fie conectat." },
          ],
          termeni: ["sincronizare stoc", "notificari about you", "webhook stoc"],
        },
        {
          slug: "cum-mapezi-categoriile-la-about-you",
          titlu: "Cum mapezi categoriile magazinului la categoriile About You",
          rezumat: "Fiecare categorie din magazin se leagă de o categorie About You, iar produsele preiau automat maparea.",
          pasi: [
            "Intră în Integrări > Marketplace > About You și derulează la cardul „Mapare categorii”.",
            "Apasă „Mapează” în dreptul categoriei tale. Dacă are deja o legătură, butonul se numește „Schimbă”.",
            "Scrie cel puțin două litere în câmpul de căutare, de exemplu rochii sau tricouri.",
            "Apasă categoria dorită din rezultate. Confirmarea este „Categorie mapată.”",
          ],
          detalii: [
            { titlu: "Cum arată o categorie fără legătură", text: "Rândul afișează „Nemapat”. Pe durata căutării vezi „Se caută...”" },
            { titlu: "Cum scoți o mapare", text: "Apasă „Elimină” pe rândul respectiv. Confirmarea este „Mapare eliminată.”" },
            { titlu: "Dacă nu ai categorii", text: "Cardul afișează doar textul care îți cere să adaugi categorii produselor tale înainte de a le putea mapa la categoriile About You." },
            { titlu: "De ce contează", text: "Editorul de listare al unui produs nu se poate completa până când categoria lui nu e mapată." },
          ],
          termeni: ["categorii about you", "nemapat", "cautare categorie"],
        },
        {
          slug: "cum-mapezi-curierii-la-about-you",
          titlu: "Cum legi curierii tăi de carrierele About You",
          rezumat: "Fiecare curier Edinio primește un carrier About You, ca tracking-ul să plece corect la generarea AWB-ului.",
          pasi: [
            "Intră în Integrări > Marketplace > About You și derulează la cardul „Mapare curieri”.",
            "Găsește rândul curierului tău. Rândurile fixe sunt FAN Courier, DPD, Cargus, Sameday, Woot și Colete Online.",
            "Deschide lista derulantă de pe acel rând. Prima opțiune este „Nemapat”, iar restul opțiunilor vin direct de la About You.",
            "Alege carrier-ul potrivit. Confirmarea este „Curier mapat.”",
          ],
          detalii: [
            { titlu: "La ce folosește", text: "Când generezi AWB-ul pentru o comandă About You, tracking-ul se trimite automat cu carrier-ul mapat." },
            { titlu: "Dacă lista nu se încarcă", text: "Cât timp se încarcă vezi „Se încarcă curierii...”. Dacă tot nu vine, apare „Nu am putut încărca lista de carriere About You. Reîncearcă.” Reîncarcă pagina și verifică dacă sesiunea About You mai e validă." },
          ],
          nota: "Se pot mapa exact cei șase curieri Edinio afișați ca rânduri. Alți curieri nu apar în acest card.",
          termeni: ["carrier", "awb about you", "tracking", "fan courier", "sameday"],
        },
        {
          slug: "cum-completezi-listarea-unui-produs-about-you",
          titlu: "Cum completezi listarea unui produs pe About You",
          rezumat: "Deschizi produsul din cardul Produse, completezi brandul, atributele și variantele, apoi îl trimiți.",
          pasi: [
            "Intră în Integrări > Marketplace > About You și derulează la cardul „Produse”.",
            "Apasă numele produsului ca să deschizi editorul de listare.",
            "Alege „Brand” din listă. Este obligatoriu.",
            "Dacă acea categorie cere culoare, alege culoarea. Celelalte grupe de atribute apar ca liste separate.",
            "Completează „Cod HS (opțional)” și „Țară de origine”, cu maximum două caractere.",
            "La „Variante” bifează „Activă” pentru fiecare variantă pe care o listezi, completează „EAN”, alege valoarea din lista de mărimi a categoriei, completează „Stoc” și, în modul manual, „Preț EUR”.",
            "Apasă „Salvează” pentru a păstra datele, „Salvează și trimite” pentru a trimite produsul sau „Publică” pentru a-l publica.",
          ],
          detalii: [
            { titlu: "Categoria trebuie mapată întâi", text: "Dacă produsul are o categorie nemapată, editorul afișează „Categoria acestui produs nu este mapată. Mapeaz-o în secțiunea de mapare categorii, apoi revino.”, iar salvarea răspunde „Mapează categoria produsului mai întâi.”" },
            { titlu: "Prețul variantei", text: "În modul automat vezi doar „Preț (auto)”, cu prețul calculat din cursul și marja setate în cardul „Setări”. În modul manual completezi tu prețul în euro." },
            { titlu: "Lista de mărimi", text: "Eticheta listei de mărimi vine de la About You și diferă în funcție de categoria aleasă. Blocul apare doar dacă acea categorie are o grupă de mărimi." },
            { titlu: "Mesajele de la salvare", text: "„Listare salvată.” după Salvează, „Trimis pe About You.” după Salvează și trimite, „Publicat pe About You.” după Publică. Fără brand primești „Alege brandul.” Dacă un SKU e folosit de alt produs, mesajul îți cere să folosești SKU-uri unice." },
            { titlu: "Ce produse apar în listă", text: "Cardul afișează cel mult 300 de produse active, ordonate după ultima modificare. Dacă nu ai produse, vezi „Nu ai produse de listat încă.”" },
          ],
          termeni: ["editor listare", "ean-13", "cod hs", "varianta", "pret auto"],
        },
        {
          slug: "cum-trimiti-listarile-about-you",
          titlu: "Cum trimiți sau publici toate listările About You",
          rezumat: "Din cardul Produse poți retrimite tot, publica ciornele, reîncerca o listare cu eroare sau elimina una.",
          pasi: [
            "Intră în Integrări > Marketplace > About You și derulează la cardul „Produse”.",
            "Apasă „Trimite toate” ca să retrimiți toate listările. Vezi câte produse au intrat în coadă.",
            "Apasă „Publică toate” ca să publici ciornele. Vezi câte produse au fost programate pentru publicare.",
            "Pe rândul unei listări cu eroare apasă „Reîncearcă”. Confirmarea este „Retrimis pe About You.”",
            "Ca să scoți o listare, apasă „Elimină” și confirmă întrebarea „Elimini această listare de pe About You?”",
          ],
          detalii: [
            { titlu: "Stările unei listări", text: "Activ pe About You, În așteptare, În aprobare, Se activează, Ciornă, Inactiv, Respins, Problemă, Eroare, Nelistat." },
            { titlu: "Ce face fiecare buton", text: "„Publică toate” pune în coadă doar listările aflate în starea de ciornă. Dacă nu e nimic de trimis, vezi „Nu există listări de trimis.”, iar dacă nu ai ciorne, vezi „Nu există ciorne de publicat.”" },
            { titlu: "Butonul Reîncearcă", text: "Apare doar pe listările aflate în starea de eroare. Citește mai întâi eroarea de pe rând, corectează în editorul de listare, apoi reîncearcă." },
          ],
          termeni: ["ciorna", "retrimitere", "stare listare", "elimina listare"],
        },
        {
          slug: "cum-conectezi-contul-trendyol",
          titlu: "Cum conectezi contul de vânzător Trendyol",
          rezumat: "Ai nevoie de trei valori din panoul Trendyol: Seller ID, API Key și API Secret.",
          pasi: [
            "Intră în Integrări > Marketplace > Trendyol.",
            "Citește caseta „Înainte de a începe” și verifică cerințele.",
            "În panoul Trendyol mergi la Informații cont > Detalii integrare. Secțiunea e vizibilă doar utilizatorului principal al contului.",
            "În Edinio completează „Seller ID”. Se scriu doar cifre.",
            "Alege „Țara magazinului”. Sub câmp scrie în ce monedă vor fi citite prețurile.",
            "Completează „API Key” și „API Secret”.",
            "Alege „Mediu”: „Producție” sau „Stage (testare)”.",
            "Apasă „Conectează și testează”. Confirmarea este „Cont Trendyol conectat.”",
          ],
          detalii: [
            { titlu: "Ce trebuie să ai înainte", text: "Cont Trendyol de vânzător aprobat, cu procesul de înregistrare finalizat, cele trei credențiale din panoul Trendyol, produse cu barcode pentru fiecare variantă și brand existent în catalogul Trendyol, plus categorie finală cu atributele ei obligatorii." },
            { titlu: "Ce nu îți trebuie", text: "Codul de referință al integrării și token-ul din panoul Trendyol nu se folosesc aici. Dacă pui codul de referință în locul Seller ID-ului, serverul îți răspunde că Seller ID trebuie să fie doar cifre și îți indică unde îl găsești." },
            { titlu: "Țările disponibile", text: "România, Bulgaria, Grecia, Cehia, Slovacia, Germania, Arabia Saudită, Emiratele Arabe Unite, Kuweit." },
            { titlu: "Dacă vitrina nu e în lei", text: "Apare un avertisment care îți spune că prețurile din Edinio sunt în lei, dar vitrina aleasă le citește în altă monedă, și că trebuie să setezi manual prețurile de vânzare pe fiecare listare înainte de a trimite produse." },
            { titlu: "Despre mediul Stage", text: "Textul din panou spune că stage-ul are chei separate și cere ca Trendyol să autorizeze IP-ul serverului nostru. Dacă nu ai cerut asta, folosește Producție." },
            { titlu: "Mesaje de validare", text: "Dacă lipsește ceva, în panou vezi „Completează Seller ID, API Key și API Secret.” API Secret trebuie să aibă cel puțin 8 caractere. Dacă sesiunea cade mai târziu, vezi „Sesiunea a expirat. Reconectează credențialele.”" },
            { titlu: "Ce vezi după conectare", text: "Cardul „Cont conectat”, eticheta „Stage” sau „Producție”, rândul cu Seller, cheia mascată, vitrina și moneda, plus contoarele „Listări”, „Aprobate”, „Respinse”, „În coadă”." },
          ],
          termeni: ["seller id", "api secret", "detalii integrare", "vitrina", "stage"],
        },
        {
          slug: "cum-completezi-setarile-de-expediere-trendyol",
          titlu: "Cum completezi setările de expediere pentru Trendyol",
          rezumat: "Alegi adresele de expediere și de retur și curierul implicit folosit la comenzile Trendyol.",
          pasi: [
            "Intră în Integrări > Marketplace > Trendyol și mergi la cardul „Setări”.",
            "Alege „Adresă expediere” din listă. Prima opțiune folosește adresa implicită din contul tău Trendyol.",
            "Alege „Adresă retur” în același fel.",
            "Alege „Curier implicit”. Prima opțiune înseamnă fără curier implicit.",
            "Bifează sau debifează „Sincronizează automat schimbările de produs, stoc și preț”.",
            "Apasă „Salvează setările”. Confirmarea este „Setări salvate.”",
          ],
          detalii: [
            { titlu: "De unde vin adresele", text: "Adresele se încarcă din contul tău Trendyol. Dacă le lași goale, se folosesc cele implicite de acolo. Dacă lista nu se încarcă, câmpul devine unul numeric în care scrii ID-ul adresei." },
            { titlu: "Cine plătește curierul", text: "Fiecare curier din listă are marcajul „(plătit de tine)” sau „(plătit de Trendyol)”. Curierii plătiți de Trendyol își completează singuri AWB-ul. La cei plătiți de tine, trimiți tu numărul AWB din pagina comenzii." },
            { titlu: "Mesaje de eroare", text: "Un ID greșit dă „ID invalid pentru adresa de expediere.” sau „ID invalid pentru adresa de retur.” Lista de curieri depinde de vitrina aleasă, iar un curier nepermis dă „Curierul ales nu este disponibil pe vitrina magazinului tău.”" },
          ],
          termeni: ["adresa expediere", "adresa retur", "curier implicit", "awb trendyol"],
        },
        {
          slug: "cum-pornesti-webhookul-de-comenzi-trendyol",
          titlu: "Cum pornești webhook-ul de comenzi Trendyol",
          rezumat: "Cu webhook-ul activ, comenzile de pe Trendyol intră imediat în Comenzi.",
          pasi: [
            "Intră în Integrări > Marketplace > Trendyol și derulează la cardul „Comenzi Trendyol”.",
            "Verifică eticheta din dreapta. Poate fi „Webhook activ” sau „Webhook inactiv”.",
            "Apasă „Activează webhook comenzi”. Confirmarea este „Webhook comenzi activat.”",
            "Dacă vrei să îl oprești, apasă „Dezactivează webhook”. Confirmarea este „Webhook dezactivat.”",
          ],
          detalii: [
            { titlu: "Ce se schimbă", text: "Comenzile intră automat în secțiunea Comenzi. Fără webhook activ, sincronizarea are loc periodic în loc de instant." },
            { titlu: "Ce vezi în card", text: "Sub text apare câte comenzi au fost importate și data ultimei sincronizări." },
          ],
          termeni: ["comenzi trendyol", "import comenzi", "sincronizare periodica"],
        },
        {
          slug: "cum-mapezi-automat-categoriile-la-trendyol",
          titlu: "Cum mapezi automat categoriile la Trendyol",
          rezumat: "Edinio caută pentru fiecare categorie a ta o categorie Trendyol potrivită și îți arată rezultatele înainte de a salva ceva.",
          pasi: [
            "Intră în Integrări > Marketplace > Trendyol și derulează la cardul „Mapare automată”.",
            "Apasă „Analizează categoriile”. Pe durata analizei butonul arată „Se analizează...”",
            "În fereastra „Potriviri găsite” verifică fiecare rând și eticheta lui de încredere: „Sigură”, „Probabilă” sau „Nesigură”.",
            "Dacă există mai multe variante pentru o categorie, alege varianta bună din listă. Fiecare arată procentul de potrivire.",
            "Bifează rândurile pe care le vrei aplicate.",
            "Apasă butonul de aplicare, care arată câte mapări se salvează. Confirmarea îți spune câte categorii au fost mapate.",
          ],
          detalii: [
            { titlu: "Ce se bifează singur", text: "Se bifează automat doar potrivirile marcate „Sigură” și doar pentru categoriile nemapate. O categorie deja mapată nu se suprascrie automat, dar poartă eticheta „Deja mapată” și îți arată la ce e legată acum." },
            { titlu: "Filtrul din fereastră", text: "Poți bifa „Arată doar categoriile nemapate” ca să scurtezi lista." },
            { titlu: "Categoriile fără potrivire", text: "Pe rândurile fără rezultat vezi „Nicio potrivire găsită. Caut-o manual mai jos.”, iar în bara de sus apare câte categorii au rămas de mapat manual." },
            { titlu: "Dacă analiza nu pornește", text: "Când Trendyol nu răspunde, primești „Nu am putut încărca lista de categorii Trendyol. Încearcă din nou.” sau „Trendyol nu a returnat nicio categorie pentru vitrina aleasă.” Verifică vitrina aleasă la conectare și reia." },
            { titlu: "Limite", text: "Se analizează cel mult 300 de categorii într-o rulare. Fără nicio bifă primești „Bifează cel puțin o mapare.”" },
          ],
          termeni: ["potriviri", "sigura", "probabila", "nesigura", "mapare in masa"],
        },
        {
          slug: "cum-mapezi-manual-o-categorie-la-trendyol",
          titlu: "Cum mapezi manual o categorie la Trendyol",
          rezumat: "Cauți categoria Trendyol după nume și o legi de categoria ta.",
          pasi: [
            "Intră în Integrări > Marketplace > Trendyol și derulează la cardul „Mapare categorii”.",
            "Apasă „Mapează” pe rândul categoriei tale. Dacă are deja o legătură, butonul se numește „Schimbă”.",
            "Scrie cel puțin două litere în câmpul de căutare, de exemplu tricou sau rochie.",
            "Apasă rezultatul dorit. Confirmarea este „Categorie mapată.”",
          ],
          detalii: [
            { titlu: "Doar categorii finale", text: "Se pot alege doar categorii finale, adică cele care nu mai au subcategorii." },
            { titlu: "Cum scoți o mapare", text: "Apasă „Elimină” pe rândul respectiv. Confirmarea este „Mapare eliminată.”" },
            { titlu: "Dacă nu ai categorii", text: "Cardul îți cere întâi să adaugi categorii produselor tale." },
          ],
          termeni: ["categorie finala", "leaf", "cautare categorie trendyol", "nemapat"],
        },
        {
          slug: "cum-trimiti-produse-in-masa-pe-trendyol",
          titlu: "Cum cauți, filtrezi și trimiți produse în masă pe Trendyol",
          rezumat: "Din cardul Produse selectezi produsele după filtre și le trimiți pe Trendyol dintr-o singură apăsare.",
          pasi: [
            "Intră în Integrări > Marketplace > Trendyol și derulează la cardul „Produse”.",
            "Caută după numele produsului în câmpul de căutare.",
            "Filtrează după stare și după categorie.",
            "Bifează „Selectează pagina” pentru toate rândurile din pagină sau bifează rândurile una câte una.",
            "Dacă vrei tot rezultatul filtrului, folosește opțiunea de selectare a tuturor produselor din bara de selecție.",
            "Apasă „Trimite pe Trendyol” și confirmă întrebarea cu numărul de produse.",
            "Așteaptă până se încheie trimiterea. Butonul arată progresul, iar la final rămâne pe ecran raportul.",
          ],
          detalii: [
            { titlu: "Filtrele de stare", text: "Toate produsele, Nelistate, Aprobate pe Trendyol, În așteptare, Cu erori, Configurate (orice stare). La categorie ai și opțiunea pentru toate categoriile. Poți goli filtrele cu „Șterge filtrele”." },
            { titlu: "Raportul de la final", text: "Raportul arată câte produse au fost trimise, câte au probleme și lista erorilor pe produs. Textul menționează că aprobarea durează câteva ore. Dacă nimic nu a putut fi trimis, vezi „Niciun produs nu a putut fi trimis.”" },
            { titlu: "Limitele selecției", text: "Pagina afișează 25 de produse. O apăsare trimite cel mult 100 de produse, iar o selecție mai mare se împarte automat în tranșe de 100. Selectarea tuturor ia cel mult 2000 de produse, iar dacă sunt mai multe primești mesajul care îți cere să restrângi filtrele. Filtrul Nelistate parcurge cel mult 5000 de produse, iar când atinge plafonul apare o mențiune sub numărător. Raportul afișează cel mult 20 de erori." },
            { titlu: "Dacă lista e goală", text: "Vezi „Niciun produs pentru filtrele alese.” sau „Nu ai produse de listat încă.” Verifică filtrele sau adaugă produse." },
          ],
          termeni: ["filtru nelistate", "selecteaza pagina", "raport erori", "trimitere in masa"],
        },
        {
          slug: "cum-completezi-listarea-unui-produs-trendyol",
          titlu: "Cum completezi listarea unui produs pe Trendyol",
          rezumat: "Alegi brandul, completezi atributele categoriei și datele fiecărei variante, apoi trimiți produsul.",
          pasi: [
            "Intră în Integrări > Marketplace > Trendyol, derulează la cardul „Produse” și apasă numele produsului.",
            "La „Brand” scrie cel puțin două litere și alege din listă. Dacă produsul are deja o marcă ce se potrivește exact, brandul se alege singur.",
            "Completează „Greutate (desi/kg, opțional)” dacă vrei altă valoare decât cea luată din greutatea produsului.",
            "Completează câmpurile din „Atribute produs”. Cele obligatorii sunt marcate cu asterisc.",
            "Apasă „Completează automat” dacă vrei ca Edinio să reia completarea peste tot. Vezi câte câmpuri au fost completate.",
            "La „Variante” completează pentru fiecare variantă „Barcode”, „Stoc”, prețul de vânzare și prețul de listă în moneda vitrinei, alege „TVA” și bifează „Activă”.",
            "Apasă „Salvează” sau „Salvează și trimite”.",
          ],
          detalii: [
            { titlu: "De unde vin datele completate automat", text: "Nota din editor spune că datele de conformitate, producător și importatori, se iau din datele firmei tale, din Setări, iar restul se deduc din produs, doar când sunt fără dubiu. Câmpurile completate astfel poartă eticheta „din datele firmei” sau „din produs”. Verifică-le înainte de trimitere. Dacă nu găsește nimic de completat, vezi „Nu am găsit ce completa automat.”" },
            { titlu: "Salvarea ca implicit pentru categorie", text: "Poți bifa opțiunea care salvează brandul și atributele ca implicite pentru acea categorie. Următoarele produse din aceeași categorie vor porni completate." },
            { titlu: "Reguli pentru barcode", text: "Fiecare variantă are nevoie de barcode. Are cel mult 40 de caractere și acceptă doar litere, cifre, punct, liniuță și underscore. Dacă depășește sau conține alte caractere, mesajul îți spune exact care barcode e problema. Barcode-urile duplicate dau „Eroare la salvarea variantelor. Verifică barcode-urile duplicate.”" },
            { titlu: "Cotele de TVA", text: "Lista arată cotele acceptate de vitrina aleasă. Pentru România sunt 0, 11 și 21. Cota de 19 nu mai e acceptată." },
            { titlu: "Categoria și brandul", text: "Dacă produsul are categoria nemapată, editorul îți cere să o mapezi întâi, iar salvarea răspunde „Mapează categoria produsului mai întâi.” Fără brand primești „Alege brandul.”" },
            { titlu: "Curierul", text: "Curierul nu se alege aici. Se declară la expediere, odată cu AWB-ul." },
          ],
          nota: "Se încarcă cel mult 20 de atribute de categorie.",
          termeni: ["barcode", "atribute produs", "completeaza automat", "tva", "pret lista"],
        },
        {
          slug: "cum-conectezi-google-merchant-center",
          titlu: "Cum conectezi contul Google Merchant Center",
          rezumat: "Autorizezi contul Google, apoi alegi contul Merchant Center din care se listează produsele.",
          pasi: [
            "Intră în Integrări > Marketing > Google Merchant Center.",
            "Apasă „Conectează Google Merchant”. Butonul arată „Se deschide Google...” cât timp te redirecționează.",
            "Autorizează accesul în contul tău Google și lasă bifată permisiunea pentru Google Shopping.",
            "La revenire, pe ecranul „Alege contul Merchant Center”, apasă contul dorit din listă.",
            "Dacă nu apare în listă, scrie ID-ul la „Sau introdu ID-ul contului manual” și apasă „Conectează”.",
            "Confirmarea este „Cont Merchant Center conectat.”",
          ],
          detalii: [
            { titlu: "Ai nevoie de domeniu propriu", text: "Dacă magazinul nu are domeniu propriu, sus apare un avertisment care spune că Google nu acceptă listarea pe o adresă de tip edinio.com cu numele tău, că te poți conecta și acum, dar produsele nu vor fi aprobate până nu adaugi un domeniu. Linkul „Conectează un domeniu” te duce unde trebuie." },
            { titlu: "Contul Google e al tău", text: "Trebuie să fii administrator în contul Merchant Center pe care îl alegi. Edinio face doar legătura și trimite produsele." },
            { titlu: "Dacă pagina arată „Disponibil în curând”", text: "Textul complet este „Integrarea Google Merchant se activează în curând pentru magazinul tău. Revino mai târziu.” și înseamnă că integrarea nu e configurată pe serverul nostru." },
            { titlu: "Erori de permisiuni", text: "Dacă primești un mesaj despre acces offline sau despre lipsa permisiunii pentru Google Shopping, apasă „Reconectează contul Google” de pe același ecran și lasă bifată permisiunea de gestionare a produselor Shopping." },
            { titlu: "Cerințe pe care ți le semnalează Google", text: "Poți primi cerința ca homepage-ul contului Merchant să fie verificat, caz în care în Merchant Center mergi la Setări, Informații despre afacere, Site web, verifici și revendici site-ul, apoi reîncerci. Altă cerință este un utilizator activ cu rolul API developer, pe care îl bifezi în Merchant Center la Setări, Persoane și acces, în dreptul utilizatorului tău. Dacă utilizatorul e în așteptare, acceptă întâi invitația primită pe email. Dacă mesajul spune că Google tocmai a înregistrat aplicația pe contul tău, mai încearcă peste câteva minute și alege din nou contul." },
          ],
          termeni: ["merchant center", "google shopping", "api developer", "homepage verificat", "domeniu propriu"],
        },
        {
          slug: "cum-setezi-feedul-google-merchant",
          titlu: "Cum setezi feed-ul, mapezi categoriile și sincronizezi în Google Merchant Center",
          rezumat: "Din pagina integrării completezi setările feed-ului, legi categoriile la cele Google și trimiți produsele.",
          pasi: [
            "Intră în Integrări > Marketing > Google Merchant Center.",
            "În banda „Conectat la Merchant Center” apasă „Setări” ca să deschizi „Setări feed”.",
            "Completează „Feed label”, „Limbă”, „Țară” și „Brand implicit”, apoi alege „Stare produse”.",
            "Bifează sau debifează „Sincronizare automată” și apasă „Salvează setările”.",
            "În cardul „Mapare categorii” alege pentru fiecare categorie a ta o categorie Google din listă, apoi apasă „Salvează maparea”.",
            "Apasă „Sincronizează acum”. Vezi câte produse au fost adăugate la sincronizare.",
            "Urmărește contoarele „Produse active”, „Aprobate”, „În așteptare”, „Respinse” și lista „Produse în Google”.",
          ],
          detalii: [
            { titlu: "Stările produselor", text: "La „Stare produse” alegi între Nou, Recondiționat și Folosit. Este starea trimisă în feed pentru toate produsele." },
            { titlu: "Ce înseamnă maparea", text: "Textul cardului arată câte categorii sunt mapate din total. După ce salvezi, mesajul îți amintește să resincronizezi ca modificarea să ajungă în Google." },
            { titlu: "Problemele semnalate de Google", text: "În lista „Produse în Google” fiecare produs are eticheta de stare și, la nevoie, problemele semnalate de Google, cu link către explicația de rezolvare. Problemele de cont apar separat, în secțiunea „Probleme la nivel de cont Merchant Center”, cu mențiunea că pot bloca aprobarea tuturor produselor până le rezolvi în Merchant Center." },
            { titlu: "Dacă nu ai sincronizat încă", text: "Vezi textul care îți cere să apeși pe „Sincronizează acum”. Dacă nu ai produse active, primești „Niciun produs activ de sincronizat.”" },
            { titlu: "Limite", text: "Lista „Produse în Google” arată cel mult 200 de produse. Lista de categorii Google din panou este un subset selectat al taxonomiei Google, nu taxonomia întreagă." },
          ],
          termeni: ["feed label", "taxonomie google", "sincronizare produse", "probleme cont merchant"],
        },
        {
          slug: "cum-conectezi-catalogul-facebook",
          titlu: "Cum conectezi catalogul Facebook și Instagram",
          rezumat: "Copiezi adresa feed-ului din Edinio și o adaugi o singură dată în Meta Commerce Manager.",
          pasi: [
            "Intră în Integrări > Marketing > Facebook Catalog.",
            "În cardul „Adresa feed-ului tau” apasă „Copiaza”. Confirmarea este „Copiat.”",
            "Apasă „Deschide Commerce Manager” sau intră singur în Meta Commerce Manager și creează un catalog de tip E-commerce.",
            "În catalog mergi la Data Sources, apasă Add, alege Use a URL, lipește adresa copiată și setează actualizarea zilnică.",
            "Leagă Pixel-ul de catalog, din secțiunea Events, ca să pornești reclamele dinamice.",
          ],
          detalii: [
            { titlu: "Cum funcționează sincronizarea", text: "Feed-ul îl actualizăm noi, tu îl conectezi o singură dată. În card vezi câte produse active ai. Feed-ul conține doar produsele active și se servește cu un cache de o oră." },
            { titlu: "Pixel-ul", text: "Pentru reclame dinamice ai nevoie de Facebook Pixel conectat. Dacă nu e, în pagină apare avertismentul care îți cere să conectezi pixelul și apoi să îl legi de catalog la pasul cu Events." },
            { titlu: "Domeniul folosit de feed", text: "Cu domeniu propriu, feed-ul folosește domeniul tău, la fel ca pixelul, așa se potrivesc produsele cu evenimentele de tracking. Fără domeniu propriu, feed-ul folosește adresa edinio.com, iar nota din pagină îți spune că îți poți conecta domeniul din Setări, secțiunea Domeniu." },
            { titlu: "Magazinul trebuie publicat", text: "Dacă magazinul nu e publicat, adresa feed-ului răspunde cu eroare 404 și Meta nu poate prelua produsele." },
          ],
          nota: "Din panou se poate doar copia adresa feed-ului. Nu există buton de sincronizare, listă de produse trimise sau stare de aprobare pentru catalog.",
          termeni: ["commerce manager", "feed xml", "pixel", "reclame dinamice", "instagram shopping"],
        },
        {
          slug: "cum-configurezi-woot",
          titlu: "Cum configurezi Woot și adresa de expeditor",
          rezumat: "Introduci cheile API din contul tău Woot și completezi adresa de unde se ridică coletele.",
          pasi: [
            "Intră în Integrări > Curieri > Woot.",
            "În contul tău de pe woot.ro mergi la Setări, secțiunea API, și generează Public Key și Secret Key.",
            "În Edinio pornește comutatorul „Activeaza Woot”.",
            "Completează „Public Key” și „Secret Key”. Ambele au 32 de caractere.",
            "Apasă „Testeaza conexiunea”. La reușită vezi „Conexiune reusita!” cu numele, emailul și creditul disponibil.",
            "În cardul „Adresa expeditor implicit” apasă butonul „Firma” sau butonul „Persoana fizica”.",
            "Completează „Persoana de contact”, „Telefon”, „Email”, „Judet”, „Oras”, „Adresa” și, dacă vrei, „Cod postal (optional)”. La firmă completezi și „Nume firma”.",
            "Apasă „Salveaza”. Confirmarea este „Configuratia Woot a fost salvata.”",
          ],
          detalii: [
            { titlu: "Ce e al tău", text: "Contul de pe woot.ro și cheile API sunt ale tale. Woot îți arată prețurile mai multor curieri, printre care Fan Courier, DPD, Cargus, Sameday și GLS, iar Edinio creează AWB-urile din comenzile tale." },
            { titlu: "La ce folosește comutatorul", text: "„Activeaza Woot” afișează butonul de creare AWB în pagina comenzilor. Fără el, butonul nu apare." },
            { titlu: "Asigurarea", text: "Dacă bifezi asigurarea cu valoare declarată, fiecare AWB se asigură pentru valoarea produselor din comandă, iar prima de asigurare apare în prețul Woot." },
            { titlu: "Mesaje de validare", text: "Testarea fără chei dă „Introdu Public Key si Secret Key inainte de testare.” Salvarea fără chei dă „Public Key si Secret Key sunt obligatorii.” Cu Woot activat și date de expeditor incomplete, salvarea îți cere contactul, telefonul și emailul sau, după caz, orașul și adresa. Orașul se poate alege doar după ce ai ales județul." },
            { titlu: "Cum renunți", text: "Butonul „Deconecteaza” apare doar când integrarea e deja activă și are Public Key. Mesajul final este „Woot deconectat.”" },
          ],
          termeni: ["woot.ro", "public key", "secret key", "expeditor", "asigurare colet"],
        },
        {
          slug: "cum-creezi-awb-woot",
          titlu: "Cum creezi, descarci sau anulezi AWB-ul unei comenzi cu Woot",
          rezumat: "Compari prețurile curierilor pentru acea comandă și generezi AWB-ul fără să ieși din panou.",
          pasi: [
            "Intră în Comenzi > Toate comenzile și apasă „Creeaza AWB” în coloana „AWB Woot”. Același ecran se deschide și din cardul curierului Woot, din pagina comenzii.",
            "La „Destinatar” verifică „Judet”, „Oras”, „Adresa”, „Telefon” și „Email (optional)”.",
            "La „Detalii colet” alege „Pachet” sau „Plic”. Pentru pachet completează greutatea și cele trei dimensiuni.",
            "Completează „Continut colet”. Implicit scrie Produse comerciale.",
            "Completează „Ramburs (RON)” și, dacă ai nevoie, pornește „Deschidere la livrare” sau „Livrare sambata”.",
            "Apasă „Calculeaza preturi curieri”.",
            "La „Alege curier” apasă oferta dorită. Fiecare arată curierul, serviciul și prețul cu TVA.",
            "Dacă serviciul cere, alege „Locatie de predare” sau „Punct de livrare (destinatar)”.",
            "Apasă butonul final de creare, care afișează curierul și prețul. Confirmarea conține numărul AWB.",
          ],
          detalii: [
            { titlu: "Ce se completează singur", text: "Județul și orașul destinatarului se completează automat dacă se potrivesc cu adresa comenzii. Rambursul se precompletează doar la comenzile cu plata la livrare neplătite. La plata online, lângă eticheta de ramburs apare mențiunea corespunzătoare." },
            { titlu: "Dacă clientul a ales un curier", text: "În ecran apare o notă cu ce curier a ales clientul la comandă și îți spune că se preselectează automat după ce apeși pe calcularea prețurilor." },
            { titlu: "AWB-ul deja generat", text: "Când comanda are deja AWB, vezi „AWB generat”, numărul lui și butoanele „Descarca A4”, „Descarca A6” și „Anuleaza AWB”. Anularea confirmă cu „AWB anulat.”" },
            { titlu: "Mesaje de validare", text: "Fără oraș primești „Selecteaza orasul destinatarului.”, fără adresă „Introdu adresa destinatarului.”, iar la pachet fără dimensiuni „Completeaza dimensiunile coletului.” Fără curier ales vezi „Selecteaza un curier.”, iar dacă serviciul cere predare sau livrare în punct, mesajele îți cer să alegi locația de predare sau punctul de livrare." },
            { titlu: "Când nu apar oferte", text: "Dacă nu există niciun serviciu pentru acea rută, vezi „Niciun serviciu disponibil pentru aceasta ruta.” Dacă nu există locații de predare pentru curierul ales în județul expeditorului, mesajul îți propune un serviciu cu ridicare de la adresă sau verificarea județului expeditorului în setările Woot. Dacă nu există puncte de livrare în orașul destinatarului, mesajul îți propune un serviciu cu livrare la adresă." },
            { titlu: "Dacă butonul lipsește", text: "Woot trebuie configurat și activat din Integrări > Curieri > Woot. Fără chei valide, acțiunile răspund că Woot nu este configurat." },
          ],
          termeni: ["awb", "ramburs", "locker", "easybox", "deschidere la livrare", "eticheta colet"],
        },
        {
          slug: "cum-vezi-comenzile-about-you",
          titlu: "Cum vezi comenzile About You în panou",
          rezumat: "Unde găsești lista comenzilor primite din About You, ce scrie pe fiecare rând și ce înseamnă fiecare etichetă de stare.",
          intro: "Comenzile din About You intră automat în lista ta de comenzi. Cardul „Comenzi About You” îți arată, separat, în ce stare sunt ele la About You și îți dă documentele emise de ei.",
          pasi: [
            "Intră în panoul de administrare > Integrări.",
            "În grupul „Marketplace”, apasă cardul „About You”.",
            "Derulează pagina până la ultimul card, „Comenzi About You”, așezat după „Mapare curieri” și după lista de listări.",
          ],
          detalii: [
            { titlu: "Ce scrie pe un rând", text: "Sus apare numărul comenzii de la About You, iar după el, dacă există legătura, numărul comenzii din Edinio. Sub ele apare data creării, iar când sunt cunoscute se adaugă țara și textul „expediată de About You”. Ultimul text apare doar la comenzile pe care le expediază ei din depozitul lor, nu tu." },
            { titlu: "Etichetele de stare", text: "Eticheta din dreptul comenzii poate fi: „Deschisă”, „Expediere în curs”, „Expediată”, „Expediere respinsă”, „Anulare în curs”, „Anulată”, „Anulare respinsă”, „Retur în curs”, „Returnată”, „Retur respins” sau „Mixtă”. „Mixtă” înseamnă că produsele din comandă nu sunt toate în aceeași stare. Dacă About You trimite o stare pe care Edinio nu o are în listă, pe rând apare codul brut al stării, așa cum vine de la ei." },
            { titlu: "Câte comenzi vezi", text: "Cardul afișează cel mult 100 de comenzi, cele mai noi primele, după data creării. Nu există paginare și nu există căutare, deci comenzile mai vechi de ultimele 100 nu se pot deschide din acest card. Ele rămân în lista ta de comenzi din Edinio." },
            { titlu: "Când lista e goală", text: "„Nicio comandă About You încă.” înseamnă că, pentru magazinul tău, nu a intrat încă nicio comandă din About You. „Nicio comandă cu probleme.” apare doar când ai pornit filtrul de probleme și nu mai există comenzi respinse." },
            { titlu: "Ce trebuie să fie în regulă ca să ajungi aici", text: "Trebuie să fii autentificat și să ai un magazin de tip ministore pe cont, altfel ești dus înapoi în panou. Cardul „About You” din „Integrări” duce la pagina integrării doar cât timp integrarea e pornită la nivel de platformă; când e oprită, cardul apare cu lacăt și fără link. Pe pagina integrării, cardul „Comenzi About You” și celelalte secțiuni apar numai după ce contul About You e conectat." },
            { titlu: "Ce ține de About You", text: "Edinio face integrarea, dar contul și contractul cu About You trebuie să fie ale tale. Stările pe care le vezi aici sunt cele raportate de ei." },
          ],
          termeni: ["comenzi About You", "Comenzi About You", "marketplace", "stare comandă", "expediată de About You", "Mixtă"],
        },
        {
          slug: "cum-vezi-doar-comenzile-about-you-cu-probleme",
          titlu: "Cum vezi doar comenzile About You cu probleme",
          rezumat: "Comutatorul care lasă în listă doar comenzile respinse de About You, ce prinde el și de ce poate să dispară din pagină.",
          pasi: [
            "Intră în panoul de administrare > Integrări > About You.",
            "Derulează la cardul „Comenzi About You”.",
            "Apasă „Arată doar problemele (N)”, butonul din dreapta titlului.",
            "Apasă „Arată toate” ca să revii la lista completă.",
          ],
          detalii: [
            { titlu: "Când apare butonul", text: "Butonul e afișat doar dacă ai cel puțin o comandă respinsă. N din paranteză e numărul acestor comenzi: cele cu „Expediere respinsă”, „Anulare respinsă” sau „Retur respins”." },
            { titlu: "Filtrarea se face pe ce e deja pe ecran", text: "Comutatorul filtrează cele cel mult 100 de comenzi deja încărcate în card. Nu recitește din baza de date, deci nu scoate la iveală comenzi mai vechi care nu erau oricum în listă." },
            { titlu: "Butonul poate să dispară cât timp filtrul e pornit", text: "Dacă apeși „Reia expedierea” pe ultima comandă respinsă, starea ei devine „Expediere în curs” și numărul de probleme ajunge la zero. Butonul „Arată toate” nu mai e afișat, iar în card rămâne textul „Nicio comandă cu probleme.”. Reîncarcă pagina ca să vezi din nou lista completă." },
            { titlu: "Ce poți face pentru fiecare tip de problemă", text: "Din panou poți relua doar comenzile cu „Expediere respinsă”, prin butonul „Reia expedierea”. Pentru „Anulare respinsă” și „Retur respins” filtrul le arată, dar nu există buton de reluare în card." },
          ],
          termeni: ["Arată doar problemele", "Arată toate", "Expediere respinsă", "Anulare respinsă", "Retur respins"],
        },
        {
          slug: "cum-descarci-factura-si-documentul-de-livrare-about-you",
          titlu: "Cum descarci factura și documentul de livrare de la About You",
          rezumat: "Cele două butoane de pe rândul comenzii, ce PDF descarcă fiecare și ce înseamnă mesajele pe care le poți primi.",
          pasi: [
            "Intră în panoul de administrare > Integrări > About You.",
            "Derulează la cardul „Comenzi About You” și găsește comanda.",
            "Apasă „Factură” pentru factura emisă de About You sau „Livrare” pentru documentul de livrare.",
            "Așteaptă descărcarea. Fișierul se salvează ca „factura-numărAboutYou.pdf”, respectiv „livrare-numărAboutYou.pdf”.",
          ],
          detalii: [
            { titlu: "Cine emite documentele", text: "About You deține checkout-ul și emite factura către cumpărător. Edinio nu generează aceste documente, ci le ia din contul tău de vânzător prin interfața lor și ți le dă la descărcare. Edinio face integrarea, dar contul și contractul cu About You trebuie să fie ale tale." },
            { titlu: "Când butoanele nu apar pe rând", text: "Cele două butoane sunt afișate doar dacă rândul e legat de o comandă din Edinio. Fără această legătură, pe rând nu apare niciun buton, nici „Reia expedierea”." },
            { titlu: "Cum le deosebești", text: "Ambele butoane au aceeași pictogramă de document, deci mergi după text. La trecerea cu mouse-ul, „Factură” arată „Factura emisă de About You”, iar „Livrare” arată „Documentul de livrare”." },
            { titlu: "Butoanele se blochează cât durează descărcarea", text: "Cât timp o cerere e în curs, se dezactivează „Factură”, „Livrare” și „Reia expedierea” de pe toate rândurile din card, nu doar de pe rândul apăsat. Așteaptă să se termine și apoi apasă următorul buton." },
            { titlu: "Mesajele pe care le poți primi", text: "Mesajele apar ca notificare în colțul ecranului. „About You nu a emis încă factura pentru această comandă.” sau „About You nu a emis încă documentul de livrare pentru această comandă.”: documentul nu e gata la ei, încearcă din nou mai târziu. „Conectează mai întâi contul About You.”: contul nu are cheie API salvată. „Cheia API About You a fost citită criptat (eroare internă). Reconectează contul.”: reconectează contul din pagina integrării. „About You nu a răspuns la timp. Încearcă din nou.” și „Eroare de rețea către About You.”: apasă din nou peste câteva momente. „Comanda nu este o comandă About You.”: rândul nu corespunde unei comenzi About You a magazinului tău." },
          ],
          nota: "Numărul de comandă folosit la descărcare se ia din rândul salvat în Edinio pentru magazinul tău, nu din ce trimite browserul, deci nu poți lua documentele altei comenzi.",
          termeni: ["factură About You", "document de livrare", "Factură", "Livrare", "PDF comandă marketplace"],
        },
        {
          slug: "cum-reiei-expedierea-unei-comenzi-about-you",
          titlu: "Cum reiei expedierea unei comenzi respinse de About You",
          rezumat: "Butonul „Reia expedierea” pentru comenzile cu „Expediere respinsă”, ce face el și ce trebuie pregătit ca expedierea să plece a doua oară.",
          pasi: [
            "Intră în panoul de administrare > Integrări > About You.",
            "La cardul „Comenzi About You”, găsește comanda cu eticheta roșie „Expediere respinsă”. Poți apăsa întâi „Arată doar problemele (N)”.",
            "Apasă „Reia expedierea”, butonul cu pictograma de camion.",
            "Verifică notificarea „Expedierea a fost repusă la coadă.” și eticheta comenzii, care trece pe „Expediere în curs”.",
          ],
          detalii: [
            { titlu: "Ce face butonul", text: "Pune comanda înapoi în coada de sincronizare cu About You, pe operația de expediere, cu numărul de încercări adus la zero, și trece starea locală pe „Expediere în curs”. Nu trimite nimic către About You în momentul apăsării. Trimiterea o face procesarea din fundal, iar starea finală, „Expediată” sau din nou „Expediere respinsă”, apare după răspunsul lor." },
            { titlu: "Butonul apare doar la „Expediere respinsă”", text: "Pentru „Anulare respinsă” și „Retur respins” nu există buton de reluare în card. Rândul trebuie să fie și legat de o comandă din Edinio, altfel pe el nu apare niciun buton." },
            { titlu: "Ce trebuie să fie pregătit ca expedierea să plece", text: "Comanda trebuie să aibă AWB generat la curier. Fără AWB, elementul din coadă e sărit și nu se întâmplă nimic. Curierul trebuie să fie mapat la un carrier About You în cardul „Mapare curieri”, de pe aceeași pagină. Acolo, opțiunea implicită pentru fiecare curier este „Nemapat”. Verifică ambele înainte să reiei a doua oară." },
            { titlu: "De ce poate reveni pe „Expediere respinsă” fără explicație", text: "Când curierul nu e mapat, procesarea din fundal se oprește cu un motiv salvat intern, care nu se afișează în panou. Rândul revine pur și simplu pe „Expediere respinsă”. Dacă reluarea eșuează de fiecare dată, prima verificare este maparea curierului și existența AWB-ului, nu comanda în sine." },
            { titlu: "Comenzile expediate de About You", text: "Rândurile care au sub ele textul „expediată de About You” sunt sărite la expediere, pentru că marfa pleacă din depozitul lor. Reluarea nu are ce trimite pentru ele." },
            { titlu: "Câte încercări se fac", text: "Procesarea din fundal reia expedierea de cel mult 5 ori. După aceea scoate comanda din coadă și pune înapoi starea „Expediere respinsă”. Poți apăsa din nou „Reia expedierea”, ceea ce readuce contorul la zero, dar mai întâi rezolvă cauza, altfel se va opri iar." },
            { titlu: "Dacă apare o eroare la apăsare", text: "Mesajul „Nu am putut repune expedierea la coadă.” înseamnă că elementul nu a fost adăugat în coadă. Apasă din nou, iar dacă mesajul se repetă, reîncarcă pagina și încearcă a treia oară." },
          ],
          termeni: ["Reia expedierea", "Expediere respinsă", "Mapare curieri", "Nemapat", "AWB", "coadă de sincronizare"],
        },
      ],
    },
  ],
};
