import { CreditCard } from "lucide-react";
import type { CategorieAjutor } from "../ajutor-tipuri";

/**
 * Categoria „Plăți și facturare” din centrul de ajutor.
 *
 * ⚠ TEXTELE SUNT CIORNĂ, scrise dintr-un audit al codului panoului, nu din cap.
 * Vezi `../ajutor.ts` pentru cum s-a făcut auditul și ce reguli de scriere se
 * aplică. Clientul le corectează.
 */
export const PLATI_SI_FACTURARE: CategorieAjutor = {
  slug: "plati-si-facturare",
  titlu: "Plăți și facturare",
  descriere: "Încasări, facturare automată, taxe și abonament.",
  icon: CreditCard,
  grupuri: [
    {
      titlu: "Plăți online",
      ghiduri: [
        {
          slug: "cum-conectezi-netopia-payments",
          titlu: "Cum conectezi Netopia Payments",
          rezumat: "Pașii pentru plata cu cardul prin Netopia, de la POS Signature și API Key până la activare.",
          intro: "Edinio face integrarea, dar contul de comerciant Netopia și punctul de vânzare sunt ale tale. Clienții sunt trimiși pe pagina securizată Netopia, nu introduc datele cardului pe site-ul tău.",
          pasi: [
            "Intră în Integrări > Netopia Payments.",
            "Într-un alt tab, deschide admin.netopia-payments.com și autentifică-te cu contul tău de comerciant.",
            "În Netopia mergi la Puncte de vânzare, alege punctul de vânzare, apoi Setări tehnice, și copiază valoarea din câmpul Signature.",
            "Tot în Netopia, apasă pe numele contului din partea de sus, apoi Profil > Securitate, și generează un API Key.",
            "Înapoi în Edinio, pornește comutatorul Activează Netopia Payments.",
            "Alege mediul din comutatorul Mod Sandbox (testare). Pornit înseamnă plăți de test, oprit înseamnă plăți reale.",
            "Completează Titlu afișaj checkout sau lasă textul implicit, Card online (Netopia).",
            "Lipește valoarea copiată în câmpul POS Signature și cheia generată în câmpul API Key.",
            "Apasă Salvează. Dacă totul e în regulă apare mesajul Configurația Netopia a fost salvată.",
          ],
          detalii: [
            { titlu: "Nu confunda API Key cu cheile de criptare", text: "Cheie publică și Cheie privată din Setări tehnice sunt pentru versiunea veche a API-ului Netopia și nu se folosesc aici. API Key-ul se generează separat, din Profil > Securitate. Ecranul te avertizează în acest sens, într-o casetă dedicată." },
            { titlu: "Ce face fiecare câmp", text: "Activează Netopia Payments arată sau ascunde metoda în formularul de comandă. Mod Sandbox (testare) alege între mediul de test și cel real. Titlu afișaj checkout este textul pe care îl vede clientul. POS Signature este semnătura punctului de vânzare, în formatul XXXX-XXXX-XXXX-XXXX-XXXX. API Key se introduce mascat, ca o parolă." },
            { titlu: "Ce te oprește la salvare", text: "Dacă lipsește semnătura apare POS Signature este obligatoriu. Dacă lipsește cheia apare API Key este obligatoriu. Până completezi ambele câmpuri, configurația nu se salvează." },
            { titlu: "Testare și trecerea pe real", text: "Cu Mod Sandbox pornit plățile nu sunt reale, deci poți face comenzi de probă. Când ești gata, oprește comutatorul și salvează din nou. Nu există buton de testare a conexiunii, iar datele nu sunt verificate la Netopia în momentul salvării." },
            { titlu: "Ce se întâmplă după salvare", text: "Netopia apare automat în Setări > Metode de plată, unde poți schimba denumirea și ordinea. La checkout apare doar dacă integrarea este și activată, și are POS Signature, și are API Key." },
          ],
          nota: "Plata prin Netopia se face în RON.",
          termeni: ["POS Signature", "API Key", "plata cu cardul", "sandbox", "admin.netopia-payments.com", "mobilPay", "procesator"],
        },
        {
          slug: "cum-adaugi-logo-netopia-in-footer",
          titlu: "Cum adaugi logo-ul Netopia în footerul magazinului",
          rezumat: "Iei codul HTML/IFRAME din Identitate Vizuală și îl lipești în ecranul integrării Netopia.",
          pasi: [
            "În contul Netopia, mergi la Identitate Vizuală.",
            "La tipul de platformă alege HTML/IFRAME.",
            "Selectează punctul de vânzare potrivit și copiază codul generat.",
            "În Edinio intră în Integrări > Netopia Payments și coboară la câmpul Logo Netopia pentru footer (Identitate Vizuală).",
            "Lipește codul în caseta de text.",
            "Apasă Salvează.",
            "Deschide magazinul și verifică footerul. Logo-ul apare sub titlul Plată securizată.",
          ],
          detalii: [
            { titlu: "Doar formatul HTML/IFRAME", text: "Câmpul acceptă doar codul de tip HTML/IFRAME de la Netopia. Variantele Script, React sau Angular nu se afișează, chiar dacă le lipești și salvezi." },
            { titlu: "Ce se păstrează din codul lipit", text: "La salvare, codul este filtrat. Rămân doar elementele iframe, a, div, span, img, picture și source, și doar adresele https. Pentru iframe se acceptă numai domeniile Netopia, adică mny.ro, netopia-payments.com, netopia.ro și mobilpay.ro. Restul este eliminat și nu ajunge în magazin." },
            { titlu: "Dacă logo-ul nu apare în magazin", text: "Verifică întâi dacă integrarea Netopia este pornită, pentru că logo-ul nu se afișează cât timp integrarea e oprită. Apoi verifică formatul codului, generându-l din nou ca HTML/IFRAME pentru punctul tău de vânzare." },
          ],
          nota: "Afișarea logo-ului Netopia este obligatorie când accepți plata cu cardul prin Netopia.",
          termeni: ["identitate vizuală", "iframe", "badge", "footer magazin", "plată securizată", "cod HTML"],
        },
        {
          slug: "cum-conectezi-contul-stripe",
          titlu: "Cum conectezi contul Stripe",
          rezumat: "Pornești conectarea din Edinio și completezi datele contului direct pe Stripe.",
          intro: "Edinio face integrarea, dar contul Stripe și relația cu Stripe sunt ale tale. Banii ajung direct în contul tău Stripe.",
          pasi: [
            "Intră în Integrări > Stripe.",
            "Verifică caseta de stare. Dacă scrie Stripe neconectat, nu ai încă niciun cont legat.",
            "Apasă butonul Conectează cu Stripe.",
            "Completează pe Stripe datele cerute despre tine și despre firmă.",
            "Întoarce-te în Edinio. Starea din pagină se actualizează singură, fără să mai salvezi ceva.",
          ],
          detalii: [
            { titlu: "Nu completezi nimic în Edinio", text: "Ecranul Stripe din panou nu are câmpuri de completat. Toate datele, inclusiv contul în care primești banii, se introduc pe Stripe." },
            { titlu: "Când începe să funcționeze", text: "Stripe se consideră gata de folosit abia când contul tău are încasările activate. Până atunci metoda nu apare în formularul de comandă, chiar dacă ai terminat pașii de pe Stripe." },
            { titlu: "Mesaje care pot apărea sub butoane", text: "Dacă nu ai un magazin creat apare textul netradus No business found, venit direct de la Stripe. Dacă cererea eșuează apare Eroare la conectare. Încearcă din nou. Dacă nu ai conexiune apare Eroare de rețea. Încearcă din nou. În toate cazurile poți relua apăsând din nou butonul." },
            { titlu: "Comisioane", text: "Sub butoane scrie că Stripe percepe comisioane proprii per tranzacție, de obicei 1,4% plus 0,25 EUR pentru carduri europene, și că Edinio nu adaugă comisioane suplimentare. Este un text informativ, comisionul exact ți-l confirmă Stripe pentru contul tău." },
            { titlu: "Casetele de prezentare", text: "Cât timp nu ești conectat, sub caseta de stare vezi trei casete despre plățile cu cardul, despre banii care ajung direct la tine și despre securitate. Ele dispar după ce contul e conectat." },
          ],
          termeni: ["Stripe Connect", "onboarding", "plăți cu cardul", "cont de plată", "conectare"],
        },
        {
          slug: "cum-verifici-starea-contului-stripe",
          titlu: "Cum continui sau verifici conectarea Stripe",
          rezumat: "Ce înseamnă fiecare stare a contului Stripe și ce buton apeși în fiecare caz.",
          pasi: [
            "Intră în Integrări > Stripe.",
            "Citește caseta de stare din partea de sus a paginii.",
            "Dacă scrie Onboarding incomplet, apasă Continuă onboarding și termină pașii rămași pe Stripe.",
            "Dacă scrie că ai contul conectat și că Stripe îl verifică, apasă Verifică din nou pentru a reciti starea, sau Continuă pe Stripe pentru a completa ce îți mai cere Stripe.",
            "Dacă scrie Stripe conectat, plățile cu cardul sunt gata. Apasă Accesează dashboard Stripe ca să treci în contul tău Stripe.",
          ],
          detalii: [
            { titlu: "Cele patru stări", text: "Stripe neconectat înseamnă că nu ai pornit nimic. Onboarding incomplet înseamnă că ai început, dar nu ai trimis datele. Starea de verificare înseamnă că ai terminat, iar Stripe îți verifică contul. Stripe conectat înseamnă că este activ și clienții pot plăti cu cardul." },
            { titlu: "Cât durează verificarea", text: "Textul din ecran spune că poate dura de la câteva minute până la una sau două zile lucrătoare. Din Edinio nu poți grăbi verificarea. Dacă Stripe cere informații suplimentare, le completezi pe Stripe." },
            { titlu: "Identificatorul contului", text: "În starea de verificare și în starea conectat, identificatorul contului Stripe apare în interiorul casetei de stare, sub textul explicativ. Îl poți folosi când discuți cu suportul." },
            { titlu: "Ce butoane apar în fiecare stare", text: "În starea de verificare ai Verifică din nou, Continuă pe Stripe și Deconectează. În starea conectat ai Accesează dashboard Stripe și Deconectează. În Onboarding incomplet există doar Continuă onboarding, deci acolo nu poți deconecta." },
          ],
          termeni: ["onboarding incomplet", "verificare cont", "charges enabled", "dashboard Stripe", "stare integrare"],
        },
        {
          slug: "cum-conectezi-bt-ipay",
          titlu: "Cum conectezi BT iPay",
          rezumat: "Configurezi plata cu cardul prin Banca Transilvania cu utilizatorul și parola API primite de la bancă.",
          intro: "Edinio face integrarea, dar contractul de comerciant și credentialele iPay vin de la Banca Transilvania. Clienții sunt trimiși pe pagina securizată a băncii, cu 3D Secure.",
          pasi: [
            "Intră în Integrări > BT iPay.",
            "Pregătește perechea utilizator și parolă API primită de la Banca Transilvania la crearea comerciantului pe platforma iPay.",
            "Pornește comutatorul Activează BT iPay.",
            "Alege mediul din comutatorul Mod Sandbox (testare). Pornit înseamnă mediu de test, oprit înseamnă plăți reale.",
            "Completează Titlu afișaj checkout sau lasă textul implicit, Card bancar (BT iPay).",
            "Completează Utilizator API și Parolă API.",
            "Apasă Salvează. Dacă totul e în regulă apare mesajul Configurația BT iPay a fost salvată.",
          ],
          detalii: [
            { titlu: "Credentialele API nu sunt cele de la consolă", text: "Ecranul precizează clar acest lucru. Utilizatorul și parola API sunt separate de datele cu care intri în consola iPay. Dacă nu le ai, le ceri băncii." },
            { titlu: "Ce te oprește la salvare", text: "Fără utilizator apare Utilizatorul API este obligatoriu. Fără parolă apare Parola API este obligatorie. Parola se introduce mascat." },
            { titlu: "Testare înainte de plăți reale", text: "Cu Mod Sandbox pornit poți face comenzi de probă. Când treci pe real, oprești comutatorul și salvezi din nou. Nu există buton de testare a credentialelor, deci ele nu sunt verificate la bancă în momentul salvării." },
            { titlu: "Ce ajunge la bancă", text: "Plata se face în RON. Descrierea comenzii trimisă către bancă este curățată de diacritice și tăiată la 80 de caractere, deci în extras poate apărea prescurtată." },
            { titlu: "După activare", text: "BT iPay apare automat în Setări > Metode de plată, unde poți schimba denumirea afișată clientului și ordinea metodelor în formularul de comandă." },
          ],
          termeni: ["Banca Transilvania", "iPay", "3D Secure", "utilizator API", "parolă API", "card bancar"],
        },
        {
          slug: "cum-conectezi-klarna",
          titlu: "Cum conectezi Klarna",
          rezumat: "Activezi plata mai târziu și plata în rate cu credentialele API din Klarna Merchant Portal.",
          intro: "Edinio face integrarea, dar contul de comerciant Klarna și credentialele API sunt ale tale.",
          pasi: [
            "Intră în Integrări > Klarna.",
            "În Klarna Merchant Portal mergi la Settings, apoi API credentials, și generează o pereche nouă de credentiale API.",
            "Înapoi în Edinio, pornește comutatorul Activează Klarna.",
            "Alege mediul din comutatorul Mod Playground (testare). Pornit înseamnă mediul de test Klarna, oprit înseamnă plăți reale.",
            "Completează Titlu afișaj checkout sau lasă textul implicit, Klarna.",
            "Completează Utilizator API și Parolă API.",
            "Apasă Salvează. Dacă totul e în regulă apare mesajul Configurația Klarna a fost salvată.",
          ],
          detalii: [
            { titlu: "Ce oferă Klarna clientului", text: "Metoda acoperă cumpără acum și plătește mai târziu, precum și plata în rate. Opțiunile efective pe care le vede clientul le stabilește Klarna, în funcție de contul tău." },
            { titlu: "Ce te oprește la salvare", text: "Fără utilizator apare Utilizatorul API este obligatoriu. Fără parolă apare Parola API este obligatorie. Dacă lași titlul gol, se salvează automat Klarna." },
            { titlu: "Piață și monedă", text: "Integrarea este fixată pe România. Plata se face în RON, iar comunicarea cu Klarna se face în limba română. Nu există opțiune pentru altă piață sau altă monedă." },
            { titlu: "Testare", text: "Cu Mod Playground pornit lucrezi în mediul de test Klarna. Nu există buton de testare a credentialelor, deci ele nu sunt verificate la Klarna în momentul salvării." },
            { titlu: "După activare", text: "Klarna apare automat în Setări > Metode de plată, unde poți schimba denumirea afișată și ordinea în formularul de comandă." },
          ],
          termeni: ["cumpără acum plătește mai târziu", "plata în rate", "Merchant Portal", "playground", "API credentials"],
        },
        {
          slug: "cum-conectezi-revolut",
          titlu: "Cum conectezi Revolut",
          rezumat: "Adaugi cheia secretă Merchant din Revolut Business, iar webhook-ul de confirmare se înregistrează singur.",
          intro: "Ai nevoie de un cont Revolut Business cu Merchant activat. Contul și cheia sunt ale tale, Edinio doar le folosește pentru a porni plata.",
          pasi: [
            "Intră în Integrări > Revolut.",
            "În Revolut Business mergi la Merchant, apoi APIs, și generează cheia secretă API.",
            "Înapoi în Edinio, pornește comutatorul Activează Revolut.",
            "Alege mediul din comutatorul Mod Sandbox (testare).",
            "Completează Titlu afișaj checkout sau lasă textul implicit, Revolut.",
            "Lipește cheia în câmpul Cheie secretă API (Merchant). Începe cu sk_ și se introduce mascat.",
            "Apasă Salvează.",
          ],
          detalii: [
            { titlu: "Webhook-ul se înregistrează automat", text: "La salvare, Edinio înregistrează singur webhook-ul prin care Revolut confirmă plata. Se întâmplă doar când integrarea e activată și cheia e completată. Dacă schimbi cheia sau treci de pe Sandbox pe Live, webhook-ul vechi este șters și se creează unul nou." },
            { titlu: "Dacă webhook-ul nu poate fi înregistrat", text: "În locul mesajului de reușită apare un avertisment, fie mesajul de eroare primit de la Revolut, fie textul că a fost salvată cheia, dar nu s-a putut înregistra webhook-ul și că trebuie verificată cheia secretă, care are nevoie de permisiuni de webhook. Configurația se salvează oricum, deci poți genera o cheie cu drepturile potrivite și salva din nou." },
            { titlu: "Ce te oprește la salvare", text: "Fără cheie apare Cheia secretă API este obligatorie. Cheia se păstrează doar pe server și nu se mai afișează în ecran după salvare." },
            { titlu: "Ce nu vezi în ecran", text: "Secretul cu care se semnează webhook-ul nu apare în interfață și nu poate fi editat. În ecran ajung doar câmpurile pe care le completezi tu." },
            { titlu: "Ce plătește clientul", text: "Plata se face în RON, pe o pagină de plată Revolut. Integrarea acceptă și Apple Pay, Google Pay și Revolut Pay, în funcție de contul tău Merchant." },
          ],
          termeni: ["Revolut Business", "merchant", "cheie secretă", "webhook", "sk_", "Apple Pay", "Google Pay"],
        },
        {
          slug: "cum-alegi-metodele-de-plata-la-checkout",
          titlu: "Cum alegi și ordonezi metodele de plată din formularul de comandă",
          rezumat: "Din Setări > Metode de plată pornești, redenumești și reordonezi ce văd clienții la finalizarea comenzii.",
          pasi: [
            "Intră în Setări, din meniul din stânga.",
            "Din lista de secțiuni alege Metode de plată.",
            "Folosește cele două săgeți, sus și jos, din dreptul fiecărei metode ca să schimbi ordinea afișării.",
            "Scrie în câmpul de text denumirea pe care o vede clientul.",
            "Pornește sau oprește metoda din comutatorul din dreapta.",
            "Apasă Salvează. Dacă totul e în regulă apare mesajul Metodele de plată au fost salvate.",
          ],
          detalii: [
            { titlu: "Ce metode apar în listă", text: "Deasupra fiecărui rând scrie tipul metodei: Ramburs, Netopia, Stripe, BT iPay, Klarna sau Revolut. Ramburs la curier este activ implicit. Un procesator apare aici automat și pornit abia după ce devine gata de folosit din Integrări." },
            { titlu: "Denumirea afișată clientului", text: "Poți scrie maximum 40 de caractere. Dacă lași câmpul gol, se folosește denumirea implicită: Ramburs la curier, Card online (Netopia), Card online (Stripe), Card bancar (BT iPay), Klarna sau Card online (Revolut)." },
            { titlu: "Avertismentul Neconfigurat", text: "Sub câmpul unui procesator care nu are toate datele completate apare textul că este neconfigurat și că nu apare la checkout până nu îl configurezi în Integrări. Avertismentul se afișează indiferent dacă metoda e pornită sau oprită aici, iar metoda nu se vede în formularul de comandă." },
            { titlu: "Ce nu se poate face din acest ecran", text: "Nicio metodă nu poate fi ștearsă. Le poți doar dezactiva, reordona și redenumi. Ramburs la curier rămâne mereu în listă. Trebuie să rămână cel puțin o metodă activă, altfel la salvare apare mesajul Trebuie să rămână cel puțin o metodă de plată activă." },
            { titlu: "Alte mesaje de eroare", text: "Dacă nu ai un magazin asociat contului, apare Nu există un magazin asociat. Dacă salvarea nu reușește, apare Eroare la salvarea metodelor de plată, iar modificările rămân pe ecran și poți încerca din nou." },
          ],
          termeni: ["checkout", "finalizare comandă", "ordine metode", "ramburs", "denumire metodă", "setări magazin"],
        },
        {
          slug: "cum-oferi-discount-la-plata-cu-cardul-sau-ramburs",
          titlu: "Cum oferi un discount pentru plata cu cardul sau pentru ramburs",
          rezumat: "Setezi o reducere automată în funcție de metoda de plată aleasă de client.",
          pasi: [
            "Intră în Setări > Metode de plată.",
            "Găsește cardul Discount la plata cu cardul.",
            "Pornește comutatorul din dreapta titlului.",
            "La Tip discount alege Procent (%) sau Sumă fixă (lei).",
            "Completează Valoare discount (%) sau Valoare discount (lei).",
            "Apasă Salvează. Dacă totul e în regulă apare mesajul Discountul la plata cu cardul a fost salvat.",
          ],
          detalii: [
            { titlu: "Discountul la ramburs", text: "Se setează la fel, în cardul Discount la plata ramburs, aflat mai jos în aceeași secțiune. Are aceleași opțiuni, procent sau sumă fixă, iar la salvare apare mesajul Discountul la plata ramburs a fost salvat." },
            { titlu: "Cum se calculează", text: "Reducerea se aplică la valoarea produselor, fără transport, după eventualul cod de reducere. De exemplu, la produse de 200 lei și un procent de 5, clientul plătește cu 10 lei mai puțin, iar costul livrării rămâne neschimbat." },
            { titlu: "Cele două discounturi nu se cumulează", text: "O comandă are o singură metodă de plată, deci clientul primește fie discountul la card, fie cel la ramburs. Discountul la card nu se aplică la ramburs, iar cel la ramburs nu se aplică la plata cu cardul." },
            { titlu: "Ce te oprește la salvare", text: "Dacă valoarea este 0 apare Introdu o valoare mai mare ca 0 pentru discount. Dacă treci peste 100 la procent apare Procentul nu poate depăși 100%." },
            { titlu: "Textul de sub câmp", text: "La Procent (%) scrie că reducerea se aplică la valoarea produselor, fără transport, după eventualul cod de reducere. La Sumă fixă (lei) scrie că se scade din valoarea produselor, fără transport, după eventualul cod de reducere." },
            { titlu: "Ca să aibă efect", text: "Discountul la card se vede doar dacă ai cel puțin o metodă de plată online activă și configurată complet. Dacă niciun procesator nu e gata de folosit, clientul nu are ce alege și reducerea nu se aplică." },
          ],
          termeni: ["reducere", "plată online", "checkout", "procent", "sumă fixă", "cod de reducere"],
        },
      ],
    },
    {
      titlu: "Facturare",
      ghiduri: [
        {
          slug: "cum-conectezi-smartbill",
          titlu: "Cum conectezi SmartBill la magazinul tău",
          rezumat: "Completezi emailul, tokenul și CUI-ul din contul tău SmartBill, testezi conexiunea, alegi seria facturilor și salvezi.",
          intro: "Înainte să începi, ai nevoie de un cont SmartBill, de un token API generat în acel cont și de o serie de facturi creată acolo.",
          pasi: [
            "Intră în Integrări > Facturare > SmartBill.",
            "Pornește comutatorul „Activează SmartBill”.",
            "Completează „Email cont SmartBill” cu adresa contului tău SmartBill.",
            "Completează „Token API SmartBill” cu tokenul copiat din contul tău.",
            "Completează „CUI firmă”, cu sau fără prefixul RO.",
            "Apasă „Testează conexiunea” și așteaptă răspunsul.",
            "În lista de serii de facturi apasă seria pe care o folosești; ea intră singură în câmpul „Seria facturilor”.",
            "Apasă „Salvează”.",
          ],
          detalii: [
            { titlu: "Ce pregătești în contul SmartBill", text: "Tokenul se ia din SmartBill, din Contul meu > Integrări > API. Seria de facturi se creează în SmartBill > Nomenclatoare > Serii, de exemplu FACT, iar dacă emiți și proforme creezi acolo și o serie de proforme, de exemplu PFACT. Panoul „Cum configurezi integrarea?” din pagină repetă acești pași și are legătura „Deschide SmartBill”." },
            { titlu: "Când poți apăsa „Testează conexiunea”", text: "Butonul rămâne inactiv până completezi emailul, tokenul și CUI-ul. Cât timp verifică, pe buton scrie „Se testează...”. Testul salvează întâi configurația din pagină și abia apoi întreabă SmartBill, deci dacă salvarea nu reușește testul nu mai pornește." },
            { titlu: "Ce vezi după un test reușit", text: "Apare o casetă verde cu seriile aduse din contul tău, sub titlurile „Serii de facturi (click pentru selectare):” și „Serii de proforme (click pentru selectare):”. Fiecare serie e afișată cu următorul număr disponibil, în forma „FACT (urm. 125)”, atunci când SmartBill îl întoarce. Când apeși o serie, primești confirmarea că a fost selectată ca serie de facturi sau de proforme." },
            { titlu: "Dacă nu apare nicio serie", text: "Vezi un avertisment care îți spune că în cont nu există serii de facturi și că trebuie să creezi una în SmartBill > Nomenclatoare > Serii. Creează seria acolo, apoi apasă din nou „Testează conexiunea”." },
            { titlu: "Ce se verifică la salvare", text: "Verificările se aplică doar când comutatorul „Activează SmartBill” este pornit. Dacă lipsește ceva, primești pe rând mesaje pentru emailul SmartBill, tokenul API, CUI-ul firmei și seria facturilor. Cât timp se salvează, pe buton scrie „Se salvează...”, iar la final primești confirmarea că integrarea a fost salvată. Dacă scrierea în baza de date nu reușește, vezi mesajul „Eroare la salvare.”." },
            { titlu: "Mesaje de eroare la testare", text: "Dacă emailul sau tokenul nu sunt corecte, primești mesajul despre credențiale invalide și verifici datele în contul SmartBill. Alte răspunsuri de la SmartBill apar ca „Eroare SmartBill” urmat de cod. Dacă nu există conexiune la internet, mesajul este despre eroare de rețea." },
          ],
          nota: "Contul SmartBill și abonamentul la SmartBill sunt ale tale. Edinio trimite documentele în contul tău, dar nu îl administrează.",
          termeni: ["token api smartbill", "cui firma", "serie facturi", "testeaza conexiunea", "conectare facturare", "smartbill nu merge"],
        },
        {
          slug: "cum-alegi-cota-tva-smartbill",
          titlu: "Cum alegi cota de TVA pentru facturile SmartBill",
          rezumat: "Cotele se aduc din contul tău SmartBill, iar tu alegi din listă cota care corespunde TVA-ului din Setări.",
          pasi: [
            "Intră în Integrări > Facturare > SmartBill.",
            "Verifică dacă emailul, tokenul și CUI-ul sunt completate.",
            "Apasă „Testează conexiunea” sau butonul cu iconiță de reîncărcare de lângă listă.",
            "Deschide lista „Cotă TVA”.",
            "Alege cota adusă din contul tău, afișată sub forma numelui urmat de procent, de exemplu „Normală (19%)”.",
            "Dacă nu ești plătitor de TVA, lasă prima opțiune din listă, cea pentru situația în care nu ești plătitor de TVA.",
            "Apasă „Salvează”.",
          ],
          detalii: [
            { titlu: "SmartBill cere numele cotei, nu procentul", text: "În listă se trimite numele cotei din contul tău, de exemplu „Normală”. Dacă în câmp rămâne o valoare care nu există în contul tău SmartBill, ea apare în listă marcată ca necunoscută în SmartBill și primești un avertisment care îți cere să alegi una dintre cotele aduse din cont." },
            { titlu: "Butonul de reîncărcare", text: "Lângă lista „Cotă TVA” este un buton pătrat cu iconiță de reîncărcare, numit pentru cititoarele de ecran „Reîncarcă cotele din SmartBill”. Este inactiv cât timp lipsesc emailul, tokenul sau CUI-ul. Dacă datele nu sunt încă salvate, primești mesajul care îți cere să completezi email, token și CUI, apoi să salvezi." },
            { titlu: "Când se încarcă singure cotele", text: "La deschiderea paginii, cotele se aduc automat doar dacă emailul, tokenul și CUI-ul erau deja salvate. Altfel lista rămâne goală până apeși „Testează conexiunea” sau butonul de reîncărcare." },
            { titlu: "Legătura cu setările magazinului", text: "Textul de sub listă îți cere să alegi cota care corespunde TVA-ului din Setări. Dacă în Setări > Taxe ai 19%, alege din SmartBill cota care are 19% în dreptul ei." },
          ],
          nota: "Dacă nu ești plătitor de TVA, lași câmpul pe opțiunea fără TVA. Nu scrie un procent de mână doar ca să fie completat câmpul.",
          termeni: ["cota tva factura", "tva 19%", "plata fara tva", "reincarca cote", "tva smartbill nu apare"],
        },
        {
          slug: "cum-trimiti-factura-pe-email-smartbill",
          titlu: "Cum trimiți automat documentul pe email clientului din SmartBill",
          rezumat: "Un comutator din pagina SmartBill face ca factura sau proforma să plece pe email către client la emitere.",
          pasi: [
            "Intră în Integrări > Facturare > SmartBill.",
            "Pornește comutatorul „Trimite documentul pe email clientului”.",
            "Citește caseta care apare sub comutator.",
            "Apasă „Salvează”.",
          ],
          detalii: [
            { titlu: "Ce trebuie să fie pregătit", text: "Clientul comenzii trebuie să aibă email salvat pe comandă, iar contul tău SmartBill trebuie să aibă un server de email configurat, din SmartBill: Setări, apoi Configurare email. Fără el, documentul se emite oricum, dar emailul către client nu pleacă." },
            { titlu: "Ce vezi când trimiterea nu reușește", text: "După emitere primești un avertisment care spune că factura a fost generată, dar emailul către client nu a putut fi trimis, urmat de motiv. Acolo ai și cele două direcții de rezolvare: configurezi serverul de email în SmartBill sau oprești trimiterea pe email din integrare." },
            { titlu: "Cine compune emailul", text: "Textul și atașamentul emailului vin din contul tău SmartBill. Edinio doar cere trimiterea la emiterea documentului." },
          ],
          nota: "Comutatorul acoperă trimiterea automată la emitere. Retrimiterea manuală se face separat, din cardul „Facturare” al comenzii, cu butonul „Retrimite”.",
          termeni: ["email client factura", "trimitere automata factura", "server email smartbill", "clientul nu a primit factura"],
        },
        {
          slug: "cum-configurezi-setarile-avansate-smartbill",
          titlu: "Cum configurezi setările avansate SmartBill",
          rezumat: "În „Setări avansate” stabilești seria de proforme, încasarea la plata cu cardul, scadența și facturarea automată.",
          pasi: [
            "Intră în Integrări > Facturare > SmartBill.",
            "Apasă rândul „Setări avansate” ca să desfaci secțiunea.",
            "Completează „Seria proformelor (opțional)” dacă emiți proforme.",
            "Pornește „Marchează factura încasată la plata online” dacă vrei ca facturile plătite cu cardul să iasă încasate.",
            "Completează „Scadența facturii (zile)”.",
            "Pornește „Generare automată factură” dacă vrei ca facturile să iasă singure.",
            "Alege din lista „Declanșează generarea când comanda devine” statusul la care se emite factura.",
            "Apasă „Salvează”.",
          ],
          detalii: [
            { titlu: "Seria proformelor", text: "Dacă acest câmp este completat, în detaliul comenzii apare secțiunea „Proformă” cu butonul „Generează proformă”. Dacă îl lași gol, poți emite doar facturi. Seria trebuie să existe deja în contul tău SmartBill, de exemplu PFACT." },
            { titlu: "Încasarea la plata online", text: "Opțiunea are efect doar când comanda are plata efectuată cu cardul, iar totalul este mai mare decât 0. Atunci factura iese direct încasată, cu mențiunea Card online. La proforme nu se aplică." },
            { titlu: "Scadența facturii", text: "Câmpul este numeric, iar 0 înseamnă data emiterii. Lăsat gol, documentul are tot data emiterii. Valorile negative sunt aduse la 0, iar intervalul sugerat de câmp este 0 până la 120 de zile. Nu există o verificare care să oprească salvarea unei valori mai mari, deci scrie numărul de zile pe care îl folosești în realitate." },
            { titlu: "Facturarea automată", text: "Lista de declanșare apare numai după ce pornești comutatorul. Poți alege între „Comandă confirmată”, „În procesare”, „Expediată”, „Livrată” și „Plătită (status plată)”. Când comanda ajunge la statusul ales, factura se emite fără intervenția ta." },
            { titlu: "Ce se întâmplă dacă ai mai multe softuri de facturare", text: "Dacă ai facturare automată pornită la mai multe integrări, pentru o comandă se emite o singură factură, în ordinea SmartBill, apoi Oblio, apoi fGO. Dacă pe comandă există deja o factură, nu se mai emite a doua. Comenzile venite din marketplace, About You și Trendyol, nu sunt facturate automat." },
            { titlu: "Când se deschide secțiunea singură", text: "Dacă ai deja o serie de proforme salvată sau facturarea automată pornită, secțiunea „Setări avansate” apare desfăcută de la deschiderea paginii." },
          ],
          nota: "Facturile emise automat sunt documente fiscale reale. Alege statusul de declanșare care corespunde momentului în care comanda e sigură, nu unul de la începutul fluxului, dacă anulezi des comenzi.",
          termeni: ["proforma smartbill", "factura incasata card", "scadenta factura", "facturare automata status comanda", "marketplace nu se factureaza"],
        },
        {
          slug: "cum-conectezi-oblio",
          titlu: "Cum conectezi contul Oblio",
          rezumat: "Introduci emailul și tokenul din contul Oblio, apoi încarci datele firmei în Edinio.",
          pasi: [
            "Intră în Integrări > Facturare > Oblio.",
            "Pornește comutatorul „Activat”.",
            "În panoul „Credențiale API” completează „Email cont Oblio (client_id)” cu adresa cu care te autentifici în Oblio.",
            "Completează „Token secret (client_secret)” cu tokenul din contul tău Oblio.",
            "Apasă „Testează și încarcă date”.",
            "Verifică mesajul de confirmare, care îți spune câte firme au fost găsite în cont.",
          ],
          detalii: [
            { titlu: "De unde iei datele de acces", text: "client_id este chiar emailul cu care te autentifici în Oblio. client_secret este tokenul din contul tău Oblio, din Setări > Date Cont. Explicațiile apar și în caseta „Despre Oblio” din capul paginii." },
            { titlu: "Când poți apăsa butonul", text: "„Testează și încarcă date” rămâne inactiv până completezi ambele câmpuri. Dacă apeși fără credențiale salvate, primești mesajul care îți cere emailul și secretul contului Oblio." },
            { titlu: "Ce vezi după încărcare", text: "Panourile „Configurare firmă și documente”, „Opțiuni document” și „Generare automată factură” apar doar după ce datele au fost încărcate sau dacă integrarea era deja conectată. Fără ele nu poți alege firma și seriile." },
            { titlu: "Dacă apare o eroare", text: "Dacă în contul tău Oblio nu există nicio firmă, primești mesajul că nu a fost găsită nicio firmă și trebuie să o adaugi în Oblio. Restul erorilor apar ca text roșu sub buton, exact cum le întoarce Oblio, și se rezolvă din contul tău Oblio." },
          ],
          nota: "Contul Oblio și tokenul sunt ale tale. Edinio face integrarea, dar contractul cu Oblio rămâne între tine și ei.",
          termeni: ["client_id oblio", "client_secret", "token oblio", "date cont oblio", "conectare oblio edinio"],
        },
        {
          slug: "cum-configurezi-firma-si-seriile-oblio",
          titlu: "Cum configurezi firma, seriile și TVA-ul în Oblio",
          rezumat: "După încărcarea datelor din cont alegi firma, seriile de documente, cota de TVA și opțiunile facturii, apoi salvezi.",
          pasi: [
            "Intră în Integrări > Facturare > Oblio, cu datele contului deja încărcate.",
            "În panoul „Configurare firmă și documente” alege „Firmă”.",
            "Alege „Serie factură” din listă.",
            "Alege „Serie proformă” sau lasă opțiunea fără proformă.",
            "Alege „Cotă TVA implicită”.",
            "În panoul „Opțiuni document” alege „Tip produse”.",
            "Completează „Scadență factură (zile)”.",
            "Pornește „Trimite în SPV (e-Factura)” dacă folosești trimiterea automată din Oblio.",
            "Pornește „Generare automată factură” și alege statusul din „Declanșează generarea când comanda devine”.",
            "Apasă „Salvează”.",
          ],
          detalii: [
            { titlu: "Alegerea firmei", text: "Firmele apar cu numele și CIF-ul între paranteze. Dacă în cont ai o singură firmă, câmpul este doar de citit. Când schimbi firma, seriile și cotele de TVA se reîncarcă pentru noul CIF, iar selecțiile implicite se rescriu, deci verifică din nou seria de factură după schimbare." },
            { titlu: "Seriile de documente", text: "Prima opțiune la „Serie factură” este „-- Selectează --”, iar seria implicită din Oblio este marcată ca implicită. La „Serie proformă” prima opțiune este „-- Fără proformă --”. Dacă seriile nu s-au încărcat, câmpurile devin text liber și scrii seria de mână, de exemplu FCT pentru facturi și PR pentru proforme." },
            { titlu: "Cota de TVA implicită", text: "Este folosită la generarea facturilor când cota nu este specificată per produs și se aplică potrivit setărilor de TVA ale magazinului. Cotele aduse din cont apar cu nume și procent, iar cea implicită din Oblio e marcată ca atare." },
            { titlu: "Tip produse", text: "Stabilește tipul liniilor de produs de pe factură. Poți alege între Marfă, Serviciu, Produs finit, Semifabricate, Materii prime, Materiale consumabile, Ambalaje și Obiecte de inventar. Pentru magazine cu produse fizice se alege Marfă. Linia de transport rămâne Serviciu." },
            { titlu: "Scadența", text: "Câmpul este numeric, iar 0 înseamnă data emiterii. Intervalul sugerat de câmp este 0 până la 120 de zile, dar nu există o verificare care să oprească salvarea unei valori mai mari." },
            { titlu: "Trimiterea în SPV", text: "Comutatorul trimite factura în SPV doar dacă trimiterea automată este activată în contul tău Oblio. Dacă în Oblio nu e pornită, comutatorul din Edinio nu suplinește acea setare." },
            { titlu: "Ce se verifică la salvare", text: "Salvarea cere credențialele Oblio, firma selectată și seria pentru factură. Dacă lipsește ceva, primești mesajul corespunzător. La reușită vezi confirmarea că a fost salvată configurația Oblio." },
            { titlu: "Facturarea automată", text: "Poți alege ca factura Oblio să se emită când comanda devine confirmată, în procesare, expediată, livrată sau plătită. Dacă ai facturare automată și la alt soft, se emite o singură factură, în ordinea SmartBill, apoi Oblio, apoi fGO." },
          ],
          termeni: ["serie factura oblio", "serie proforma", "spv e-factura", "tip produse marfa", "cota tva implicita oblio"],
        },
        {
          slug: "cum-conectezi-fgo",
          titlu: "Cum conectezi fGO",
          rezumat: "Completezi CUI-ul firmei și cheia privată API din contul fGO, apoi verifici conexiunea.",
          pasi: [
            "Intră în Integrări > Facturare > fGO.",
            "Lasă „Mod testare (UAT)” oprit dacă lucrezi pe date reale.",
            "În panoul „Credențiale API” completează „CUI firmă” cu codul fiscal al firmei tale.",
            "Completează „Cheie privată API” cu cheia generată în contul fGO.",
            "Apasă „Testează conexiunea” și așteaptă răspunsul.",
            "Verifică mesajul care confirmă conexiunea și numărul de județe disponibile.",
          ],
          detalii: [
            { titlu: "Ce pregătești în contul fGO", text: "Te autentifici în contul tău fGO, mergi la Setări, apoi Utilizatori, și generezi un utilizator API. Copiezi cheia privată afișată acolo. Tot din Setări, la Serii Documente, notezi seria pe care o folosești pentru facturi, pentru că îți trebuie la pasul următor. Pagina are și legătura „Deschide fGO”." },
            { titlu: "Când poți apăsa butonul de testare", text: "„Testează conexiunea” rămâne inactiv până completezi și „CUI firmă”, și „Cheie privată API”. Cât timp verifică, pe buton scrie „Se verifică...”, iar după o verificare reușită scrie „Conexiune reușită”. Dacă modifici apoi orice câmp, butonul revine la „Testează conexiunea” și trebuie să verifici din nou." },
            { titlu: "Dacă verificarea nu reușește", text: "Mesajul începe cu „Eroare conexiune fGO:” și continuă cu motivul întors de fGO. Verifică în contul fGO dacă utilizatorul API este activ și dacă ai copiat cheia întreagă, apoi încearcă din nou." },
            { titlu: "Modul de testare", text: "Comutatorul „Mod testare (UAT)” trimite cererile către serverul de test fGO, api-testuat.fgo.ro. Pornește-l doar cât timp testezi și oprește-l înainte să emiți documente reale." },
            { titlu: "Caseta de stare", text: "Când integrarea este salvată și are CUI, cheie privată și serie, sus în pagină apare caseta verde „fGO activ”, cu CUI-ul și seria configurate și cu butonul „Deconectează”." },
          ],
          nota: "Pagina fGO nu are un comutator separat de activare. Salvarea configurației pornește integrarea, iar oprirea se face din „Deconectează”.",
          termeni: ["cheie privata fgo", "utilizator api fgo", "mod uat", "cui firma fgo", "eroare conexiune fgo"],
        },
        {
          slug: "cum-completezi-setarile-documentelor-fgo",
          titlu: "Cum completezi setările documentelor fGO",
          rezumat: "Stabilești seria, valuta, tipul facturii, adresa platformei și scadența, apoi salvezi configurația.",
          pasi: [
            "Intră în Integrări > Facturare > fGO.",
            "În panoul „Setări documente” completează „Serie documente” cu seria din contul tău fGO.",
            "Alege „Valută”.",
            "Verifică „Tip factură” și lasă valoarea implicită dacă nu folosești alt tip.",
            "Completează „URL platformă”.",
            "Completează „Scadență factură (zile)”.",
            "Pornește „Generare automată factură” și alege statusul din „Declanșează generarea când comanda devine”, dacă vrei facturi emise fără intervenția ta.",
            "Apasă „Salvează configurația”.",
          ],
          detalii: [
            { titlu: "Seria documentelor", text: "Seria se configurează în fGO, la Setări, apoi Serii Documente, și se scrie aici la fel. Textul introdus este transformat automat cu majuscule, de exemplu fct devine FCT." },
            { titlu: "Valuta și tipul facturii", text: "La „Valută” poți alege RON, EUR sau USD. La „Tip factură” valoarea implicită este Factura, iar indicația din pagină îți spune să o lași așa dacă nu ai un motiv anume să o schimbi." },
            { titlu: "URL platformă", text: "Se completează cu adresa root a platformei tale, de exemplu https://edinio.com. Câmpul este obligatoriu la salvare." },
            { titlu: "Scadența", text: "Câmpul este numeric, iar 0 înseamnă data emiterii. Intervalul sugerat de câmp este 0 până la 120 de zile, dar nu există o verificare care să oprească salvarea unei valori mai mari." },
            { titlu: "Ce se verifică la salvare", text: "Verificările se fac în această ordine: CUI-ul firmei, cheia privată, seria documentelor și URL-ul platformei. La reușită vezi confirmarea că a fost salvată configurația fGO, iar cât timp se salvează, pe buton scrie „Se salvează...”." },
            { titlu: "Facturarea automată", text: "Factura fGO se emite când comanda ajunge la statusul ales dintre confirmată, în procesare, expediată, livrată și plătită. Dacă ai facturare automată și la alt soft, pentru o comandă se emite o singură factură, în ordinea SmartBill, apoi Oblio, apoi fGO." },
          ],
          nota: "Salvarea configurației pornește integrarea, chiar dacă nu ai apăsat „Testează conexiunea”. Verificarea conexiunii înainte de salvare îți arată din timp dacă datele de acces sunt bune.",
          termeni: ["serie documente fgo", "valuta factura", "url platforma", "scadenta fgo", "salveaza configuratia"],
        },
        {
          slug: "cum-emiti-factura-dintr-o-comanda",
          titlu: "Cum emiți factură, proformă sau storno dintr-o comandă",
          rezumat: "Din cardul „Facturare” al comenzii generezi documentul, îl descarci ca PDF și, la SmartBill, îl retrimiți pe email.",
          pasi: [
            "Intră în Comenzi > Toate comenzile și deschide comanda.",
            "În coloana din dreapta caută cardul „Facturare”.",
            "Dacă ai mai multe softuri conectate, alege furnizorul din butoanele „SmartBill”, „Oblio” și „fGO” din capul cardului.",
            "Apasă „Generează factură” sau, unde există, „Generează proformă”.",
            "Așteaptă până se termină emiterea; pe buton scrie „Se generează...”.",
            "Descarcă documentul cu butonul „PDF”.",
          ],
          detalii: [
            { titlu: "Când apare cardul „Facturare”", text: "Cardul apare doar dacă ai cel puțin un soft de facturare pornit. SmartBill apare dacă are comutatorul de activare pornit. Oblio apare dacă are activare, email, CIF și serie de factură. fGO apare dacă are activare, CUI, cheie privată și serie. Dacă ai un singur soft conectat, logoul lui apare în colțul cardului, fără butoane de comutare." },
            { titlu: "SmartBill: proformă și conversie", text: "Secțiunea „Proformă” apare doar dacă ai completat seria proformelor în setările integrării. După emitere, rândul „Proformă emisă” arată numărul documentului și butoanele „PDF” și „Retrimite”. Butonul „SmartBill”, care deschide documentul în contul tău, apare doar dacă platforma a salvat link-ul documentului la emitere. Cu proformă emisă și fără factură, poți apăsa „Convertește în factură”." },
            { titlu: "SmartBill: storno", text: "„Emite storno” apare doar dacă statusul comenzii este „Anulat” sau „Rambursat” și nu există deja un storno. După apăsare confirmi cu „Confirmă storno”, iar textul de avertizare îți spune că acțiunea stornează factura în SmartBill și nu poate fi anulată. Dacă SmartBill nu întoarce numărul stornoului, în locul descărcării primești un mesaj care te trimite la documentul de stornare din contul tău SmartBill." },
            { titlu: "Oblio: ce vezi după emitere", text: "Cu factura emisă vezi rândul cu seria și numărul facturii, butonul „PDF” dacă Oblio a întors un link și butonul „Emite storno”. Cu doar proforma emisă vezi rândul cu seria și numărul proformei, butonul „PDF” dacă există link și butonul „Generează factură”." },
            { titlu: "fGO: ce vezi după emitere", text: "Butonul disponibil este „Generează factură”. După emitere apare rândul cu seria și numărul facturii, butonul „PDF” dacă fGO a întors un link și butonul „Emite storno”." },
            { titlu: "Retrimiterea pe email", text: "Butonul „Retrimite” există doar la SmartBill. Îl apeși, se deschide un câmp în care scrii adresa clientului, apoi apeși „Trimite”. Poți trimite atât factura, cât și proforma." },
            { titlu: "Mesaje când ceva nu merge", text: "O comandă nu poate fi facturată de două ori, la fel nici stornată de două ori, iar mesajele îți spun asta pentru fiecare furnizor. Conversia dă eroare dacă nu există proformă sau dacă factura există deja. Dacă proforma a fost deja facturată în SmartBill și factura e ciornă, mesajul te trimite să o finalizezi din contul SmartBill. Dacă integrarea nu are toate datele, primești mesajul că furnizorul nu este configurat complet și te întorci în pagina lui de setări. La descărcare, o problemă apare ca eroare la descărcarea PDF-ului." },
          ],
          nota: "La Oblio și la fGO nu există pas de confirmare înainte de storno. Documentele sunt fiscale reale, deci verifică furnizorul selectat înainte să apeși.",
          termeni: ["genereaza factura comanda", "proforma comanda", "storno", "descarca pdf factura", "retrimite factura pe email"],
        },
        {
          slug: "cum-emiti-facturi-in-masa",
          titlu: "Cum emiți facturi pentru mai multe comenzi deodată",
          rezumat: "Bifezi comenzile din listă, alegi furnizorul și apeși „Generează facturi”.",
          pasi: [
            "Intră în Comenzi > Toate comenzile.",
            "Bifează comenzile dorite sau folosește bifa din capul tabelului, care selectează toată pagina.",
            "În bara de acțiuni în masă alege din listă „Factură: automat” sau numele unui furnizor.",
            "Apasă „Generează facturi”.",
            "Confirmă în fereastra deschisă de browser.",
            "Citește rezumatul cu numărul de facturi reușite, sărite și eșuate.",
          ],
          detalii: [
            { titlu: "Ce înseamnă „Factură: automat”", text: "Alege singur furnizorul, în ordinea SmartBill, apoi Oblio, apoi fGO, dintre cele active. Lista de furnizori apare doar dacă ai mai multe softuri conectate." },
            { titlu: "Limite și ordine", text: "Se procesează cel mult 50 de comenzi la o acțiune. Facturile se emit una câte una, nu în paralel, pentru că furnizorii dau numere consecutive pe aceeași serie. Comenzile care au deja o factură, de la orice furnizor, sunt sărite." },
            { titlu: "Ce spune confirmarea", text: "Fereastra de confirmare îți arată câte comenzi ai selectat și te avertizează că se emit documente fiscale reale, care nu pot fi șterse, doar stornate." },
            { titlu: "Unde vezi rezultatul", text: "Notificarea arată cifrele într-o formă de tipul „Facturi: 8 reușite, 1 sărite, 1 eșuate”. Aceleași cifre rămân în panoul de sub bara de acțiuni, cu valorile separate prin punct." },
            { titlu: "Dacă nu se întâmplă nimic", text: "Dacă nu ai bifat nicio comandă, primești mesajul că nu e selectată nicio comandă. Dacă alegi un furnizor care nu este activ, primești mesajul că nu există niciun furnizor de facturare activ pentru opțiunea aleasă, iar rezolvarea e în pagina de configurare a acelui furnizor." },
            { titlu: "Butoane pe fiecare rând", text: "În tabel există și coloanele „Documente” pentru SmartBill, „Oblio” și „fGO”, cu butoane de generare și cu etichetele documentelor deja emise. Aceste coloane sunt vizibile doar pe ecrane late." },
          ],
          termeni: ["facturare in masa", "selectare comenzi", "50 de comenzi", "bulk facturi", "comenzi sarite"],
        },
        {
          slug: "generare-automata-factura-smartbill",
          titlu: "Cum activezi generarea automată a facturii în SmartBill",
          rezumat: "Conectezi contul SmartBill, pornești generarea automată din „Setări avansate” și alegi la ce status al comenzii se emite factura.",
          intro: "Edinio face integrarea, dar contul și contractul cu SmartBill trebuie să fie ale tale.",
          pasi: [
            "Intră în Integrări > Facturare > SmartBill.",
            "Pornește comutatorul „Activează SmartBill”.",
            "Completează „Email cont SmartBill”, „Token API SmartBill”, „CUI firmă” și „Seria facturilor”.",
            "Apasă „Testează conexiunea”. Seriile din cont apar ca butoane sub „Serii de facturi (click pentru selectare):”, iar cotele se încarcă în lista „Cotă TVA”.",
            "Alege seria și, dacă folosești, cota de TVA.",
            "Deschide secțiunea „Setări avansate”.",
            "Pornește comutatorul „Generare automată factură”.",
            "Din lista „Declanșează generarea când comanda devine” alege statusul: „Comandă Confirmată”, „În procesare”, „Expediată”, „Livrată” sau „Plătită (status plată)”.",
            "Apasă „Salvează”.",
          ],
          detalii: [
            { titlu: "Ce iei din contul SmartBill", text: "Tokenul: în contul SmartBill mergi la Contul meu > Integrări > API și copiezi tokenul generat. Seria: în SmartBill > Nomenclatoare > Serii creezi o serie pentru facturi (de exemplu FACT) și, dacă vrei să emiți și proforme, una separată (de exemplu PFACT)." },
            { titlu: "Unde stă comutatorul de generare automată", text: "„Generare automată factură” nu se vede în pagină până nu deschizi „Setări avansate”. Secțiunea e închisă la un magazin nou și se deschide singură doar dacă ai deja completată „Seria proformelor” sau generarea automată pornită dinainte." },
            { titlu: "Butonul „Testează conexiunea”", text: "Rămâne inactiv până completezi email, token și CUI. Când îl apeși, configurația se salvează întâi și abia apoi se face testul, deci ce ai scris în câmpuri rămâne în cont chiar dacă testul nu trece. Dacă legătura cade, apare „Eroare de rețea.”." },
            { titlu: "Celelalte câmpuri din „Setări avansate”", text: "„Trimite documentul pe email clientului”, „Seria proformelor”, „Marchează factura încasată la plata online” și „Scadența facturii (zile)”. Pentru trimiterea pe email, panoul spune direct: „Ca emailul să fie trimis, contul tău SmartBill trebuie să aibă un server de email configurat (în SmartBill: Setări > Configurare email). Dacă nu e configurat, factura se generează oricum, dar emailul către client nu pleacă.”" },
            { titlu: "Mesaje la salvare", text: "Cu integrarea pornită, salvarea se oprește dacă lipsește ceva: „Email-ul SmartBill este obligatoriu.”, „Tokenul API este obligatoriu.”, „CUI-ul firmei este obligatoriu.”, „Seria facturilor este obligatorie.”" },
            { titlu: "Cota de TVA", text: "SmartBill cere numele cotei, nu procentul. Dacă numele salvat de tine nu se regăsește în contul tău, factura se emite oricum: Edinio caută printre cotele din cont una cu același procent și o folosește pe aceea. Dacă nici după procent nu găsește ceva potrivit, trimite numele așa cum l-ai scris tu și SmartBill hotărăște mai departe. Ca să nu ajungi acolo, alege cota din lista încărcată după test." },
            { titlu: "Când nu se emite nimic", text: "Pe calea automată factura pleacă doar dacă în configurație sunt salvate integrarea activă, generarea automată, emailul, tokenul, CUI-ul și seria. Dacă pe comandă există deja o factură nestornată, nu se mai emite a doua." },
            { titlu: "Dacă factura automată nu iese", text: "Nu primești niciun mesaj de eroare în panou: eșecul se scrie doar în jurnalul de erori al platformei, vizibil administratorilor Edinio. Verifică pe rând: integrarea e pornită, generarea automată e pornită, statusul comenzii chiar a ajuns la declanșatorul ales și comanda nu are deja factură. Dacă totul pare în regulă, scrie-ne cu numărul comenzii." },
          ],
          termeni: ["SmartBill", "factură automată", "generare automată factură", "declanșator status comandă", "token API SmartBill", "serie facturi", "cotă TVA"],
        },
        {
          slug: "generare-automata-factura-oblio",
          titlu: "Cum activezi generarea automată a facturii în Oblio",
          rezumat: "Conectezi contul Oblio, alegi firma și seria, apoi pornești generarea automată și statusul la care se emite factura.",
          intro: "Edinio face integrarea, dar contul și contractul cu Oblio trebuie să fie ale tale.",
          pasi: [
            "Intră în Integrări > Facturare > Oblio.",
            "Pornește comutatorul „Activat”.",
            "Completează „Email cont Oblio (client_id) *” și „Token secret (client_secret) *”.",
            "Apasă „Testează și încarcă date”. Firmele, seriile și cotele de TVA vin din contul tău.",
            "Alege „Firmă *” și „Serie factură *”. Dacă folosești, alege și „Serie proformă” și „Cotă TVA implicită”.",
            "Coboară la blocul de sub linie și pornește „Generare automată factură”.",
            "Din lista „Declanșează generarea când comanda devine” alege statusul: „Comandă Confirmată”, „În procesare”, „Expediată”, „Livrată” sau „Plătită (status plată)”.",
            "Apasă „Salvează”.",
          ],
          detalii: [
            { titlu: "Ce iei din contul Oblio", text: "„client_id” este emailul cu care te autentifici în Oblio, iar „client_secret” este tokenul din Setări > Date Cont." },
            { titlu: "De ce nu vezi blocul de generare automată", text: "Blocul apare doar după ce datele contului au fost încărcate cu „Testează și încarcă date” sau dacă integrarea e deja conectată (are email și firmă salvate). Într-o pagină goală, întâi conectezi contul, apoi apare comutatorul." },
            { titlu: "Butonul „Testează și încarcă date”", text: "Rămâne inactiv până completezi emailul și secretul. La reușită apare „Conexiune reușită!” cu numărul de firme găsite. La eșec, textul erorii apare și ca notificare, și într-o casetă roșie sub buton." },
            { titlu: "Celelalte câmpuri", text: "„Tip produse” (Marfă, Serviciu, Produs finit, Semifabricate, Materii prime, Materiale consumabile, Ambalaje, Obiecte de inventar), „Scadență factură (zile)” și comutatorul „Trimite în SPV (e-Factura)”." },
            { titlu: "Mesaje la salvare", text: "„Introdu credențialele Oblio”, „Selectează firma”, „Selectează seria pentru factură”. Când merge, apare „Configurație Oblio salvată”." },
            { titlu: "Butonul „Deconectează”", text: "Apare doar când integrarea e deja conectată. Golește credențialele și seriile și oprește comutatorul „Activat”, iar la final vezi „Oblio deconectat”. Cu integrarea deconectată, generarea automată nu mai emite nimic." },
            { titlu: "Dacă ai și alt soft de facturare", text: "Sub lista de declanșatoare scrie regula: „Dacă ai mai multe softuri de facturare cu generare automată, se emite o singură factură (prioritate: SmartBill, apoi Oblio, apoi fGO).”" },
            { titlu: "Dacă factura automată nu iese", text: "Eșecul nu apare nicăieri în panou, se scrie doar în jurnalul de erori al platformei. Verifică dacă integrarea e activă, generarea automată e pornită și comanda a ajuns chiar la statusul ales ca declanșator." },
          ],
          termeni: ["Oblio", "factură automată", "client_id", "client_secret", "serie factură", "SPV e-Factura", "declanșator status comandă"],
        },
        {
          slug: "generare-automata-factura-fgo",
          titlu: "Cum activezi generarea automată a facturii în fGO",
          rezumat: "Completezi credențialele API fGO și seria de documente, apoi pornești generarea automată și alegi statusul la care se emite factura.",
          intro: "Edinio face integrarea, dar contul și contractul cu fGO trebuie să fie ale tale.",
          pasi: [
            "Intră în Integrări > Facturare > fGo.",
            "În „Credențiale API” completează „CUI firmă” și „Cheie privată API”, apoi apasă „Testează conexiunea”.",
            "În „Setări documente” completează „Serie documente” și „URL platformă”. Dacă e cazul, alege „Valută”, „Tip factură” și „Scadență factură (zile)”.",
            "Sub linia din josul blocului pornește comutatorul „Generare automată factură”.",
            "Din lista „Declanșează generarea când comanda devine” alege statusul: „Comandă Confirmată”, „În procesare”, „Expediată”, „Livrată” sau „Plătită (status plată)”.",
            "Apasă „Salvează configurația”.",
          ],
          detalii: [
            { titlu: "Ce iei din contul fGO", text: "În fGO mergi la Setări > Utilizatori și generezi un utilizator API, apoi copiezi cheia privată afișată. Seria o iei din Setări > Serii Documente." },
            { titlu: "Comutatorul „Mod testare (UAT)”", text: "Mută emiterea pe serverul de test fGO (api-testuat.fgo.ro). Cât timp e pornit, și facturile automate ies pe mediul de test, nu în contabilitatea reală. Oprește-l când treci pe comenzi adevărate." },
            { titlu: "Butonul „Testează conexiunea”", text: "Rămâne inactiv până completezi CUI-ul și cheia privată. La reușită butonul devine „Conexiune reușită” și apare mesajul „fGO a acceptat CUI-ul și cheia privată.”" },
            { titlu: "Salvarea pornește integrarea", text: "Când apeși „Salvează configurația”, integrarea fGO se activează odată cu salvarea. Bannerul de stare arată „fGO activ”, iar confirmarea este „Configurație fGO salvată”." },
            { titlu: "Mesaje la salvare", text: "„CUI-ul firmei este obligatoriu”, „Cheia privată este obligatorie”, „Seria documentelor este obligatorie”, „URL-ul platformei este obligatoriu”." },
            { titlu: "fGO e ultimul în ordinea de emitere", text: "Sub lista de declanșatoare scrie: „Dacă ai mai multe softuri de facturare cu generare automată, se emite o singură factură (prioritate: SmartBill, apoi Oblio, apoi fGO).” Dacă ai și SmartBill sau Oblio cu generare automată pornită, fGO emite doar când acelea nu au emis." },
            { titlu: "Când nu se emite nimic", text: "Factura automată pleacă doar dacă integrarea e activă și generarea automată e pornită în configurația salvată. Dacă pe comandă există deja o factură nestornată, emiterea e oprită. Eșecul nu apare în panou, se scrie doar în jurnalul de erori al platformei." },
          ],
          termeni: ["fGO", "fGo", "factură automată", "cheie privată API", "serie documente", "mod testare UAT", "declanșator status comandă"],
        },
        {
          slug: "factura-automata-la-schimbarea-statusului-comenzii",
          titlu: "Cum declanșezi factura automată schimbând statusul unei comenzi",
          rezumat: "După ce ai configurat generarea automată, factura se emite când muți comanda pe statusul ales ca declanșator, din detaliul comenzii sau din bara de acțiuni în masă.",
          pasi: [
            "Intră în Comenzi > Toate comenzile și deschide comanda.",
            "În cardul „Status comandă” apasă butonul statusului dorit.",
            "Dacă e cazul, schimbă și „Status plată”.",
            "Apasă „Salvează modificările” și confirmă.",
            "Dacă noul status coincide cu declanșatorul configurat, factura se emite în fundal și documentul apare în cardul „Facturare” al comenzii.",
          ],
          detalii: [
            { titlu: "Denumirile nu sunt identice în cele două locuri", text: "Butoanele de status din comandă scriu „Confirmat”, „Expediat”, „Livrat”, iar lista de declanșatoare din pagina furnizorului scrie „Comandă Confirmată”, „Expediată”, „Livrată”. Sunt aceleași stări, doar scrise diferit. Statusurile complete ale comenzii sunt: În așteptare, Confirmat, În procesare, Expediat, Livrat, Anulat, Rambursat." },
            { titlu: "Pentru mai multe comenzi deodată", text: "În Comenzi > Toate comenzile bifezi comenzile, alegi noul status din lista „Schimbă status…” și apeși „Aplică”. Butonul rămâne inactiv cât timp lista e pe „Schimbă status…”. Statusurile disponibile: În așteptare, Confirmate, În procesare, Expediate, Livrate, Anulate, Rambursate. Se facturează doar comenzile care chiar au fost actualizate, iar emiterea se face după actualizare, separat de ea: dacă furnizorul de facturare întârzie sau pică, schimbarea de status rămâne făcută." },
            { titlu: "Declanșatorul „Plătită (status plată)”", text: "Se potrivește ori de câte ori statusul de plată al comenzii este „plătit”. Pe o comandă deja plătită, chiar și o simplă mutare de status poate potrivi declanșatorul. A doua factură nu se emite: dacă pe comandă există deja un număr de factură de la oricare furnizor, emiterea se oprește." },
            { titlu: "Cardul „Facturare” din comandă", text: "Apare în detaliul comenzii doar dacă ai cel puțin un furnizor de facturare activ. Acolo vezi documentul emis pentru comanda respectivă." },
            { titlu: "Dacă statusul s-a salvat, dar factura nu apare", text: "Facturarea nu blochează și nu oprește salvarea comenzii, și nu afișează niciun mesaj de eșec în ecranul comenzii. Verifică în pagina furnizorului dacă generarea automată e pornită și dacă declanșatorul ales este chiar statusul pe care l-ai pus, apoi dacă pe comandă nu există deja o factură. Comenzile venite din marketplace (About You, Trendyol) nu se facturează automat, pentru că marketplace-ul încasează și facturează el clientul final." },
          ],
          termeni: ["status comandă", "factură automată", "acțiuni în masă", "Schimbă status", "card Facturare", "declanșator"],
        },
        {
          slug: "factura-automata-dupa-plata-online",
          titlu: "Cum se emite factura automat după o plată online",
          rezumat: "Cu generarea automată pornită și declanșatorul pe „Plătită (status plată)” sau „Comandă Confirmată”, factura pleacă singură când clientul plătește cu cardul.",
          pasi: [
            "Pornește „Generare automată factură” la unul dintre furnizori: SmartBill, Oblio sau fGO.",
            "Alege ca declanșator „Plătită (status plată)” sau „Comandă Confirmată”.",
            "Apasă „Salvează”. De aici nu mai ai nimic de făcut: la o plată cu cardul, comanda e marcată plătită și factura se emite fără intervenția ta.",
          ],
          detalii: [
            { titlu: "De ce doar aceste două declanșatoare", text: "O plată online marchează comanda ca plătită și o duce direct în „confirmată”. Alte declanșatoare nu se potrivesc la plată: „În procesare”, „Expediată” și „Livrată” țin de traseul de livrare, nu de încasare." },
            { titlu: "Când comanda ajunge la curier", text: "Aceeași generare automată se cheamă și când coletul devine expediat sau livrat, la urmărirea automată a coletelor. Deci un declanșator pe „Expediată” sau „Livrată” poate porni și fără să atingi tu comanda." },
            { titlu: "Fără facturi duble", text: "Dacă procesatorul de plăți trimite de două ori aceeași confirmare, nu se emite a doua factură: dacă pe comandă există deja un număr de factură de la oricare furnizor, emiterea se oprește." },
            { titlu: "Dacă nu vine nicio factură", text: "Verifică întâi că integrarea e activă și „Generare automată factură” e pornit în configurația salvată, nu doar bifat în ecran fără salvare. Eșecul emiterii nu apare nicăieri în panou, deci dacă comanda e plătită, nu are factură și configurația pare corectă, scrie-ne cu numărul comenzii." },
          ],
          termeni: ["plată online", "plată cu cardul", "factură automată", "Plătită status plată", "comandă confirmată", "urmărire colet"],
        },
        {
          slug: "prioritate-furnizori-facturare-automata",
          titlu: "Ce se întâmplă când ai mai multe softuri de facturare conectate",
          rezumat: "Se emite o singură factură pe comandă. Ordinea încercării este fixă: SmartBill, apoi Oblio, apoi fGO.",
          pasi: [
            "Deschide fiecare furnizor la care vrei factură automată și pornește „Generare automată factură”.",
            "Reține ordinea în care se încearcă emiterea: întâi SmartBill, apoi Oblio, apoi fGO.",
            "Verifică declanșatorul ales la fiecare: se oprește la primul furnizor care chiar a emis factura.",
          ],
          detalii: [
            { titlu: "Textul din panou", text: "Regula e scrisă sub lista „Declanșează generarea când comanda devine”, la Oblio și la fGO, și doar când comutatorul de generare automată e pornit: „Dacă ai mai multe softuri de facturare cu generare automată, se emite o singură factură (prioritate: SmartBill, apoi Oblio, apoi fGO).” În ecranul SmartBill textul nu apare." },
            { titlu: "Ordinea nu se poate schimba", text: "Nu există un ecran de prioritate în panoul de administrare. Ordinea e fixă. Dacă vrei ca facturile să iasă dintr-un anumit soft, ține „Generare automată factură” pornit doar la acela." },
            { titlu: "Când furnizorul cu prioritate mai mare nu emite", text: "Dacă la SmartBill declanșatorul nu se potrivește sau emiterea eșuează, se trece la Oblio, apoi la fGO. Nu primești nicio notificare că a emis alt furnizor decât cel așteptat." },
            { titlu: "O singură factură pe comandă", text: "Dacă pe comandă există deja un număr de factură de la oricare dintre cei trei furnizori, nu se mai emite nimic, indiferent câte integrări ai active." },
            { titlu: "Comenzile din marketplace", text: "Comenzile venite din marketplace (About You, Trendyol) sunt excluse complet de la facturarea automată: marketplace-ul încasează și emite el factura către clientul final." },
          ],
          termeni: ["prioritate facturare", "SmartBill Oblio fGO", "o singură factură", "mai multe softuri de facturare", "marketplace"],
        },
      ],
    },
    {
      titlu: "Plan, livrare și taxe",
      ghiduri: [
        {
          slug: "cum-vezi-planul-activ-si-data-urmatoarei-plati",
          titlu: "Cum vezi ce plan ai activ și când urmează plata",
          rezumat: "Cardul de sus din Setări > Plan îți arată planul, intervalul de plată și data următoare.",
          pasi: [
            "Intră în Setări > Plan.",
            {
              text: "Sus, în cardul de plan, citește eticheta Plan activ și denumirea planului tău.",
              captura: { alt: "Cardul de plan activ, cu denumirea planului și data următoarei plăți.", src: "/capturi/ajutor/plati-si-facturare/cum-vezi-planul-activ-si-data-urmatoarei-plati.webp", raport: 16 / 10 },
            },
            "Dacă ești pe plan plătit, lângă denumire scrie plata anuală sau plata lunară.",
            "Sub denumire citește rândul Următoarea plată pe, cu data, sau Expiră pe, cu data, dacă ești pe plan neplătit.",
          ],
          detalii: [
            { titlu: "Ce denumiri de plan pot apărea", text: "Gratuit (15 zile), Basic, Premium și Ultra. Contul pe perioadă de testare și contul pe planul gratuit apar amândouă ca Gratuit (15 zile)." },
            { titlu: "Rândul cu data", text: "Apare doar dacă pe contul tău există o dată de expirare. Pe plan plătit este data la care se face următoarea plată, pe plan neplătit este data la care expiră accesul." },
            { titlu: "Cardul este doar informativ", text: "Nu se editează nimic aici. Schimbarea planului se face din cardurile de mai jos, din aceeași secțiune, iar cardul, anularea și chitanțele se gestionează din Setări > Facturare." },
          ],
          nota: "Dacă vrei să vezi dacă ești în testare sau pe planul gratuit, intră în Setări > Facturare. Acolo cele două stări arată diferit.",
          termeni: ["abonament curent", "cand expira", "data urmatoarei plati", "ce plan am", "interval de facturare"],
        },
        {
          slug: "cum-cumperi-sau-schimbi-planul-de-abonament",
          titlu: "Cum cumperi sau schimbi planul de abonament",
          rezumat: "Alegi intervalul, apeși butonul de pe cardul planului dorit și plătești cu cardul pe pagina de checkout.",
          pasi: [
            "Intră în Setări > Plan.",
            "Alege intervalul din comutator: Lunar sau Anual.",
            "Compară cele trei carduri: Basic, Premium și Ultra.",
            "Apasă butonul de pe cardul dorit: Alege Basic, Alege Premium sau Alege Ultra.",
            "Butonul devine Se redirecționează și ajungi pe pagina de plată cu cardul.",
            "Plătește cu cardul. După o plată reușită revii în Setări, direct pe secțiunea Plan, cu un mesaj care confirmă că plata a fost procesată și planul actualizat.",
          ],
          detalii: [
            { titlu: "Ce cuprinde fiecare plan", text: "Basic, 99 lei pe lună: până la 500 produse, comenzi nelimitate, suport non-stop 24/7, mentenanță gratuită. Premium, 249 lei pe lună: până la 2.500 produse, comenzi nelimitate, suport non-stop 24/7, mentenanță gratuită și manager dedicat magazinului tău. Ultra, 499 lei pe lună: produse nelimitate, comenzi nelimitate, suport non-stop 24/7, mentenanță gratuită și manager dedicat magazinului tău." },
            { titlu: "Cardul planului pe care ești deja", text: "Nu are buton. În locul lui apare textul Plan activ. Eticheta Recomandat de pe Premium se vede doar dacă Premium nu este planul tău; altfel în locul ei apare Plan activ sau Planul tău." },
            { titlu: "Ce se întâmplă cu abonamentul vechi", text: "Nu se anulează în momentul în care apeși butonul. Anularea lui se face după ce noua plată reușește." },
            { titlu: "Dacă renunți la plată", text: "Revii pe ecranul de setări, fără niciun mesaj, iar planul tău rămâne neschimbat." },
            { titlu: "Mesaje de eroare", text: "Trebuie să fii autentificat, altfel plata răspunde Neautorizat. Dacă alegi Anual și prețul anual nu este configurat, apare Planul anual nu este disponibil momentan. Dacă alegi Lunar și prețul lunar nu este configurat, apare Plan invalid. Mesajul depinde de intervalul ales, nu de motiv. La alte probleme apare Eroare la inițializarea plății." },
            { titlu: "Dacă butonul rămâne pe Se redirecționează", text: "Când conexiunea cade, butonul rămâne blocat pe acest text și nu apare niciun mesaj. Reîncarcă pagina și încearcă din nou." },
            { titlu: "Anularea nu se face din secțiunea Plan", text: "Aici nu există buton de anulare. Anulezi din portalul de plată, în Setări > Facturare. Textul de jos al secțiunii trimite la contact@edinio.com pentru upgrade sau informații." },
          ],
          nota: "Plata se face cu cardul, pe pagina externă de checkout Stripe. Edinio te duce acolo, dar procesarea cardului se întâmplă la Stripe.",
          termeni: ["upgrade plan", "cumpar abonament", "plata cu cardul", "stripe checkout", "schimbare plan"],
        },
        {
          slug: "cum-treci-de-la-plata-lunara-la-plata-anuala",
          titlu: "Cum treci același plan de pe plata lunară pe plata anuală",
          rezumat: "Comuți intervalul în secțiunea Plan și apeși butonul de trecere de pe cardul planului tău.",
          pasi: [
            "Intră în Setări > Plan.",
            "Apasă pe comutatorul opus intervalului tău curent: Anual dacă plătești lunar, Lunar dacă plătești anual.",
            "Pe cardul planului tău eticheta de sus devine Planul tău, în loc de Plan activ.",
            "Apasă butonul Treci pe plata anuală sau Treci pe plata lunară.",
            "Butonul afișează Se redirecționează și ajungi pe pagina de plată.",
          ],
          detalii: [
            { titlu: "Creditul din planul curent", text: "Când treci pe plata anuală, sub buton apare nota că creditul din planul curent se aplică automat." },
            { titlu: "Când apare opțiunea", text: "Doar dacă ești pe un plan plătit, adică Basic, Premium sau Ultra. Pe planul gratuit vezi butoanele obișnuite de alegere a planului." },
            { titlu: "Diferența dintre cele două etichete", text: "Plan activ apare pe cardul tău când te uiți la intervalul pe care plătești acum. Planul tău apare pe același card când ai comutat pe celălalt interval." },
          ],
          nota: "Ce se întâmplă exact cu perioada deja plătită, ca dată de intrare în vigoare, nu se vede în panou. Pentru un caz anume scrie la contact@edinio.com.",
          termeni: ["trecere pe anual", "schimb interval", "plata anuala abonament", "credit plan"],
        },
        {
          slug: "cum-gestionezi-abonamentul-din-portalul-de-plata",
          titlu: "Cum gestionezi abonamentul din portalul de plată",
          rezumat: "Din Setări > Facturare intri în portalul Stripe, unde schimbi cardul, anulezi abonamentul sau descarci chitanțele.",
          pasi: [
            "Intră în Setări > Facturare.",
            "În cardul Abonamentul tău citește planul și prețul, de exemplu Plan Premium, 249 lei pe lună.",
            "Lângă el vezi eticheta de stare: Activ sau Plată restantă.",
            "Apasă butonul Gestionează abonamentul. Devine Se redirecționează și ajungi în portalul de plată.",
            "În portal actualizezi cardul, anulezi abonamentul sau descarci chitanțele.",
          ],
          detalii: [
            { titlu: "Când apare cardul Abonamentul tău", text: "Doar dacă ești pe un plan plătit. Pe planul gratuit sau în perioada de testare apar alte carduri, fără buton către portal." },
            { titlu: "Ce mai scrie pe card", text: "Rândul Următoarea plată, cu data la care se reînnoiește abonamentul, și explicația că prin portalul de plată poți actualiza cardul, anula abonamentul sau descărca chitanțele Stripe." },
            { titlu: "Când butonul lipsește", text: "Dacă abonamentul este în stare de plată restantă, în locul lui apare butonul roșu Reia plata." },
            { titlu: "Mesaje de eroare", text: "Nu există un abonament activ asociat contului tău, Eroare la deschiderea portalului de plată sau Eroare de rețea, încearcă din nou. Contul tău trebuie să aibă deja un client Stripe asociat, creat la prima plată." },
          ],
          nota: "Anularea abonamentului se face aici, în portal, nu în secțiunea Plan.",
          termeni: ["anulare abonament", "schimbare card", "portal stripe", "chitante", "facturi stripe"],
        },
        {
          slug: "cum-reiei-o-plata-restanta",
          titlu: "Cum reiei o plată restantă",
          rezumat: "Când plata reînnoirii eșuează, butonul Reia plata din Setări > Facturare te duce direct pe factura restantă.",
          pasi: [
            "Intră în Setări > Facturare.",
            "Dacă plata reînnoirii a eșuat, lângă plan apare eticheta roșie Plată restantă, iar data apare la A expirat pe.",
            "Citește mesajul de pe card, care îți spune că plata reînnoirii a eșuat și că trebuie reluată ca să îți păstrezi magazinul activ.",
            "Apasă butonul roșu Reia plata. Butonul devine Se deschide.",
            "Ajungi pe pagina facturii restante, unde poți plăti pe loc, inclusiv cu alt card.",
          ],
          detalii: [
            { titlu: "Când apare eticheta Plată restantă", text: "Doar pe plan plătit și doar când pe cont există o eșuare reală de plată înregistrată." },
            { titlu: "Dacă nu există o factură deschisă", text: "Butonul te duce în schimb în portalul Stripe, de unde poți actualiza cardul sau te poți reabona." },
            { titlu: "Mesaje de eroare", text: "Nu există un abonament asociat contului tău, Nu am putut deschide plata, încearcă din nou sau contactează-ne, Eroare la deschiderea plății și Eroare de rețea, încearcă din nou." },
          ],
          nota: "Contul trebuie să aibă un client de plată asociat, creat la prima plată reușită.",
          termeni: ["plata esuata", "reinnoire", "factura neplatita", "cont suspendat", "past due"],
        },
        {
          slug: "cum-vezi-si-descarci-facturile",
          titlu: "Cum vezi istoricul facturilor și le descarci în PDF",
          rezumat: "Facturile emise pentru abonament stau în Setări > Facturare, în cardul Istoricul facturilor.",
          pasi: [
            "Intră în Setări > Facturare.",
            "Derulează la cardul Istoricul facturilor.",
            "Pe desktop vezi un tabel cu coloanele Dată, Număr factură, Plan, Sumă și Factură.",
            "În coloana Factură apasă Descarcă PDF. Documentul se deschide într-o filă nouă.",
            "Pe telefon fiecare factură este un rând cu plan, sumă și dată, iar descărcarea se face din iconița din dreapta.",
          ],
          detalii: [
            { titlu: "Ce înseamnă coloanele", text: "Dată este ziua emiterii, Număr factură este seria și numărul din Smartbill, Plan este planul facturat, Sumă este valoarea și moneda, iar Factură este linkul de descărcare." },
            { titlu: "Când scrie În procesare", text: "Cât timp seria sau numărul lipsesc, în loc de link apare textul În procesare și nu poți descărca nimic. Revino mai târziu." },
            { titlu: "Dacă nu ai nicio factură", text: "În card scrie Nicio factură încă, împreună cu explicația că facturile apar aici după prima plată." },
            { titlu: "Facturile ajung și pe email", text: "Sunt emise automat prin Smartbill la fiecare plată reușită, în numele companiei, și se trimit automat pe email. Pentru probleme de facturare, adresa din josul cardului este contact@edinio.com." },
          ],
          termeni: ["factura abonament", "smartbill", "descarcare pdf", "istoric plati", "numar factura"],
        },
        {
          slug: "cum-pornesti-sau-opresti-livrarea",
          titlu: "Cum pornești sau oprești livrarea pe magazin",
          rezumat: "Primul comutator din Setări > Livrare decide dacă clienții pot alege o metodă de livrare la comandă.",
          pasi: [
            "Intră în Setări > Livrare.",
            "Sus, în primul card, găsește Livrare activată, cu explicația că permite clienților să aleagă o metodă de livrare la comandă.",
            "Mută comutatorul din dreapta.",
            "Coboară la finalul paginii și apasă Salvează.",
          ],
          detalii: [
            { titlu: "Ai nevoie de un magazin creat", text: "Fără magazin, sus apare avertismentul că nu ai un magazin activ și că trebuie să finalizezi onboarding-ul, iar butonul Salvează este blocat." },
            { titlu: "Nimic nu se salvează singur", text: "Comutatorul, metodele, prețurile, pragul, comanda minimă, clasele și regulile se salvează toate deodată, cu butonul Salvează de la finalul secțiunii." },
          ],
          nota: "În panou scrie doar că opțiunea permite clienților să aleagă o metodă de livrare la comandă. Ce se schimbă exact în formularul de comandă când comutatorul este oprit nu este descris acolo.",
          termeni: ["dezactivare livrare", "transport activ", "metode de livrare pornite"],
        },
        {
          slug: "cum-activezi-o-metoda-de-livrare-si-ii-pui-pret",
          titlu: "Cum activezi o metodă de livrare și îi stabilești prețul",
          rezumat: "Fiecare curier are un comutator propriu în lista Metode de livrare, iar unele metode cer și un preț.",
          pasi: [
            "Intră în Setări > Livrare și coboară la lista Metode de livrare.",
            "Găsește curierul dorit: Fan Courier, DPD, Cargus, Sameday, Woot, Colete Online, Curier propriu sau Ridicare personală.",
            "Mută comutatorul din dreapta rândului ca să activezi metoda.",
            "La Curier propriu și Ridicare personală apare direct câmpul Preț. Scrie suma în lei.",
            "Apasă Salvează la finalul secțiunii.",
          ],
          detalii: [
            { titlu: "Curierii reali cer întâi integrarea", text: "Fan Courier, DPD, Cargus, Sameday, Woot și Colete Online trebuie configurați în Integrări, din meniul lateral al panoului. Până atunci rândul apare estompat, comutatorul nu se mișcă, iar sub numele curierului apare linkul Configurează integrarea, care te duce la Integrări. Edinio face integrarea, dar contul și contractul cu curierul trebuie să fie ale tale." },
            { titlu: "Metodele care nu cer nimic", text: "Curier propriu și Ridicare personală se pot activa oricând, fără integrare." },
            { titlu: "Prețurile propuse implicit", text: "Fan Courier 20, DPD 18, Cargus 17, Sameday 19, Woot 16, Colete Online 15, Curier propriu 10 și Ridicare personală 0. Le poți schimba, iar câmpul acceptă valori de la 0 în sus, cu pas de 0,01." },
            { titlu: "Costul implicit de livrare al magazinului", text: "La salvare, el este preluat din prețul primei metode active din listă. Ordinea metodelor din listă contează pentru asta." },
            { titlu: "Lista de curieri este fixă", text: "Nu poți adăuga un alt curier în afară de opțiunea Curier propriu." },
          ],
          termeni: ["curier", "transport", "fan courier", "sameday", "ridicare din magazin", "cost livrare"],
        },
        {
          slug: "cum-alegi-pret-automat-sau-pret-fix-la-curier",
          titlu: "Cum alegi între preț automat din contract și preț fix la un curier integrat",
          rezumat: "Curierii integrați pot lua tariful direct din contractul tău sau pot folosi o sumă stabilită de tine.",
          pasi: [
            "Intră în Setări > Livrare și activează curierul integrat, de exemplu Fan Courier.",
            "Sub rândul lui apar două opțiuni: Preț automat (din contract) și Preț fix.",
            "Alege Preț automat (din contract) dacă vrei tariful venit de la curier.",
            "Alege Preț fix dacă vrei să pui tu suma. Lângă opțiune apare un câmp numeric și eticheta lei.",
            "Apasă Salvează la finalul secțiunii.",
          ],
          detalii: [
            { titlu: "Unde apar aceste opțiuni", text: "Doar la curierii reali care sunt și integrați în Integrări. Curier propriu și Ridicare personală nu au contract, așa că primesc direct un câmp de preț fix." },
            { titlu: "Ce este selectat din start", text: "Pentru un curier integrat, opțiunea implicită este Preț automat (din contract)." },
            { titlu: "Legătura cu regulile de transport", text: "Regulile care setează un preț fix se aplică doar curierilor cu preț fix, adică Curier propriu, Ridicare personală și curierii integrați puși pe Preț fix. Pe un curier lăsat pe preț automat, acele reguli nu au efect." },
          ],
          termeni: ["tarif curier", "pret din contract", "cost transport calculat", "pret fix livrare"],
        },
        {
          slug: "cum-schimbi-numele-metodei-de-livrare-la-checkout",
          titlu: "Cum schimbi numele cu care apare metoda de livrare în formularul de comandă",
          rezumat: "Fiecare metodă activată are un câmp în care scrii denumirea văzută de client.",
          pasi: [
            "Intră în Setări > Livrare și activează metoda dorită.",
            "Sub ea apare câmpul Nume afișat la checkout.",
            "Scrie numele pe care vrei să îl vadă clientul, de exemplu Livrare în 24h.",
            "Apasă Salvează la finalul secțiunii.",
          ],
          detalii: [
            { titlu: "Ce se întâmplă dacă lași gol", text: "Se folosește numele implicit al metodei, pe care îl vezi ca sugestie în câmp: Livrare prin FAN Courier, Livrare prin Sameday, DPD, Cargus, Woot, Colete Online, Curier propriu sau Ridicare personală." },
            { titlu: "Limita de caractere", text: "Numele poate avea maximum 60 de caractere." },
            { titlu: "Câmpul apare doar la metodele activate", text: "Dacă metoda este oprită, câmpul nu se vede. Activeaz-o întâi, apoi scrie numele." },
          ],
          nota: "Sub câmp scrie că așa apare metoda în formularul de comandă și că poți lăsa gol pentru numele implicit.",
          termeni: ["denumire livrare", "checkout", "cum vede clientul livrarea", "eticheta transport"],
        },
        {
          slug: "cum-setezi-pragul-de-transport-gratuit",
          titlu: "Cum setezi pragul de la care transportul este gratuit",
          rezumat: "Scrii o sumă în cardul Transport gratuit de la, iar comenzile peste ea nu mai plătesc livrarea.",
          pasi: [
            "Intră în Setări > Livrare și coboară la cardul Transport gratuit de la.",
            "Scrie suma în câmpul numeric. Lângă el scrie lei.",
            "Apasă Salvează la finalul secțiunii.",
          ],
          detalii: [
            { titlu: "Cum funcționează pragul", text: "Clienții nu plătesc livrarea dacă valoarea comenzii depășește suma scrisă aici. Dacă pui 200, o comandă de 250 lei primește transport gratuit." },
            { titlu: "Cum oprești funcția", text: "Lasă câmpul gol. Gol înseamnă oprit, nu este același lucru cu valoarea 0." },
            { titlu: "Ce valori sunt acceptate", text: "Doar numere pozitive. Altfel, la salvare apare mesajul că pragul pentru transport gratuit trebuie să fie un număr pozitiv." },
          ],
          termeni: ["livrare gratuita", "prag comanda", "transport gratis peste"],
        },
        {
          slug: "cum-setezi-valoarea-minima-a-comenzii",
          titlu: "Cum setezi valoarea minimă a unei comenzi",
          rezumat: "Sub suma stabilită aici, clienții nu pot finaliza comanda.",
          pasi: [
            "Intră în Setări > Livrare și coboară la cardul Comanda minimă.",
            "Scrie suma în câmpul numeric. Lângă el scrie lei.",
            "Apasă Salvează la finalul secțiunii.",
          ],
          detalii: [
            { titlu: "La ce se referă suma", text: "La valoarea produselor, nu la totalul cu transport. Dacă pui 50, un coș de 45 lei în produse nu poate fi finalizat, chiar dacă livrarea ar duce totalul peste 50." },
            { titlu: "Cum oprești funcția", text: "Lasă câmpul gol. În panou scrie că un câmp gol dezactivează comanda minimă." },
            { titlu: "Ce valori sunt acceptate", text: "Doar numere pozitive. Altfel, la salvare apare mesajul că valoarea comenzii minime trebuie să fie un număr pozitiv." },
          ],
          termeni: ["comanda minima", "suma minima cos", "valoare minima checkout"],
        },
        {
          slug: "cum-creezi-clase-de-transport",
          titlu: "Cum creezi, redenumești sau ștergi clase de transport",
          rezumat: "Clasele grupează produsele, ca Voluminos sau Fragil, ca să le poți aplica reguli de transport.",
          pasi: [
            "Intră în Setări > Livrare și coboară la cardul Clase de transport.",
            "Scrie numele clasei în câmpul de jos, de exemplu Voluminos.",
            "Apasă Adaugă sau tasta Enter.",
            "Ca să redenumești o clasă, scrie direct în câmpul ei.",
            "Ca să o ștergi, apasă iconița coș de gunoi din dreptul ei.",
            "Apasă Salvează la finalul secțiunii Livrare.",
          ],
          detalii: [
            { titlu: "Butonul Adaugă rămâne blocat cât timp câmpul e gol", text: "Scrie întâi un nume, apoi îl poți apăsa." },
            { titlu: "Unde folosești clasa după ce o creezi", text: "Pe fiecare produs, în Produse > Toate produsele, în câmpul Clasa de transport. Opțiunea implicită acolo este Standard (implicit), iar câmpul apare pe produs doar după ce ai creat cel puțin o clasă." },
            { titlu: "Clasele nu se salvează singure", text: "Adăugarea, redenumirea și ștergerea rămân doar pe ecran până apeși butonul Salvează din josul secțiunii Livrare." },
            { titlu: "Numărul de clase", text: "În panou nu am găsit o limită maximă la numărul de clase." },
          ],
          termeni: ["voluminos", "fragil", "grupare produse transport", "clasa produs"],
        },
        {
          slug: "cum-adaugi-o-regula-presetata-de-transport",
          titlu: "Cum adaugi o regulă presetată de transport",
          rezumat: "Trei scenarii gata făcute: treaptă de greutate, treaptă de valoare și supliment pe clasă.",
          pasi: [
            "Intră în Setări > Livrare și coboară la cardul Reguli de transport.",
            "Apasă unul dintre butoane: Treaptă de greutate, Treaptă de valoare sau Supliment pe clasă.",
            "La treapta de greutate completează intervalul, De la și până sub, în kg, apoi prețul în lei.",
            "La treapta de valoare completează același interval, dar în lei, apoi prețul în lei.",
            "La suplimentul pe clasă alege clasa din lista Dacă coșul conține clasa și scrie suma la supliment.",
            "Apasă Salvează la finalul secțiunii Livrare.",
          ],
          detalii: [
            { titlu: "Butonul Supliment pe clasă cere o clasă", text: "Rămâne blocat până creezi cel puțin o clasă de transport, iar la trecerea cu mouse-ul apare explicația că trebuie să adaugi întâi o clasă. Când îl apeși, regula se creează cu prima ta clasă deja selectată. O poți schimba din listă." },
            { titlu: "Pe ce curieri se aplică", text: "Regulile de tip treaptă stabilesc un preț fix, deci au efect doar pe curierii cu preț fix: Curier propriu, Ridicare personală și curierii integrați puși pe Preț fix. Suplimentul pe clasă se aplică oricărui curier. Presetele nu au selector de curieri, se aplică tuturor." },
            { titlu: "Prioritățile sunt fixe", text: "10 la treapta de greutate, 5 la treapta de valoare și 0 la suplimentul pe clasă. Nu se pot edita din interfața presetată. Regulile se evaluează în ordinea descrescătoare a priorității." },
            { titlu: "Numele nu se schimbă", text: "Regulile presetate păstrează denumirile Treaptă de greutate, Treaptă de valoare și Supliment pe clasă." },
            { titlu: "Oprire temporară sau ștergere", text: "Fiecare regulă are un comutator pe rândul ei, pentru oprire temporară, și o iconiță coș de gunoi pentru ștergere." },
            { titlu: "Dacă nu ai nicio regulă", text: "În card scrie că nu există nicio regulă și că poți adăuga un scenariu presetat sau o regulă custom mai jos." },
          ],
          termeni: ["treapta greutate", "kg transport", "supliment clasa", "tarif pe greutate", "reguli livrare"],
        },
        {
          slug: "cum-construiesti-o-regula-de-transport-custom",
          titlu: "Cum construiești o regulă de transport custom",
          rezumat: "Combini condiții, o acțiune, curierii vizați și o prioritate, într-o regulă scrisă de tine.",
          pasi: [
            "Intră în Setări > Livrare, în cardul Reguli de transport, și apasă butonul verde Regulă custom.",
            "Scrie un nume în câmpul de sus. Regula se creează cu numele Regulă nouă.",
            "Apasă Condiție și alege tipul: Greutate (kg), Valoare coș (lei), Cantitate (buc), Clasă, Categorie, Produs sau Județ.",
            "Completează condiția: intervalul de la și până sub la greutate, valoare și cantitate, sau alege din listă la clasă, categorie, produs și județ.",
            "La Acțiune alege: Supliment, Preț fix (curieri fix), Transport gratuit sau Ascunde curierul.",
            "La Se aplică la alege curierii. Dacă nu alegi niciunul, regula se aplică tuturor.",
            "Scrie un număr la Prioritate.",
            "Apasă Salvează la finalul secțiunii Livrare.",
          ],
          detalii: [
            { titlu: "Toate condițiile trebuie îndeplinite", text: "Când ai mai multe condiții, titlul devine Condiții (toate trebuie îndeplinite). Dacă le ștergi pe toate, apare nota că fără condiții regula se aplică la orice comandă." },
            { titlu: "Condiția pe clasă", text: "Alegi clasele din Alege clase și modul: oricare sau toate. Ai nevoie de clase create în Clase de transport." },
            { titlu: "De unde vin opțiunile din liste", text: "La Categorie apar doar categoriile folosite efectiv de produsele active ale magazinului, iar la Produs cauți doar printre produsele active. Listele arată cel mult 60 de rezultate filtrate, iar când nu se potrivește nimic scrie Niciun rezultat." },
            { titlu: "Ce face fiecare acțiune", text: "Supliment adaugă o sumă peste prețul de bază, în lei sau în procent. Preț fix (curieri fix) impune o sumă. Transport gratuit duce prețul la 0. Ascunde curierul scoate opțiunea din formularul de comandă." },
            { titlu: "Cum se combină regulile", text: "Suplimentele de la mai multe reguli se cumulează. La preț fix câștigă prima regulă potrivită. Regulile cu prioritate mai mare se evaluează primele. Acțiunea Preț fix nu are efect pe curierii lăsați pe Preț automat (din contract)." },
            { titlu: "Un exemplu", text: "Vrei 15 lei în plus la comenzile de peste 20 kg. Adaugi o condiție Greutate (kg) cu de la 20, alegi acțiunea Supliment, scrii 15 și lași unitatea pe lei." },
            { titlu: "Ce valori nu sunt acceptate", text: "Sumele nu pot fi negative." },
          ],
          termeni: ["regula personalizata", "judet livrare", "ascunde curier", "supliment procent", "conditii transport"],
        },
        {
          slug: "cum-te-declari-platitor-de-tva",
          titlu: "Cum te declari plătitor de TVA și alegi cota",
          rezumat: "Secțiunea Taxe pornește calculul TVA pentru comenzile din magazinul tău.",
          pasi: [
            "Intră în Setări > Taxe.",
            "Mută comutatorul de la Plătitor de TVA.",
            "La Cota TVA (%) apasă unul dintre butoanele 19%, 9% sau 5%, ori scrie altă valoare în câmpul liber.",
            "Apasă Salvează setările TVA.",
          ],
          detalii: [
            { titlu: "Ce scrie avertismentul de sus", text: "Dacă ești plătitor de TVA, activezi secțiunea și TVA-ul se aplică la totalul comenzii și se afișează clienților. Dacă nu ești plătitor de TVA, lași secțiunea dezactivată." },
            { titlu: "Restul câmpurilor apar abia după pornirea comutatorului", text: "Cota, întrebarea despre prețuri și defalcarea în coș se văd doar cu Plătitor de TVA pornit." },
            { titlu: "Ce valori acceptă cota", text: "Un număr între 0 și 100. Altfel apare mesajul că cota TVA trebuie să fie între 0 și 100." },
            { titlu: "Ai nevoie de un magazin creat", text: "Fără magazin apare avertismentul că nu ai un magazin activ și că trebuie să finalizezi onboarding-ul, iar butonul de salvare este blocat." },
            { titlu: "Mesaje la salvare", text: "La reușită apare confirmarea că setările TVA au fost salvate. La eșec apare Eroare la salvare." },
          ],
          termeni: ["tva", "cota 19", "firma platitoare tva", "taxe magazin"],
        },
        {
          slug: "cum-spui-daca-preturile-includ-tva",
          titlu: "Cum spui dacă prețurile din catalog includ deja TVA",
          rezumat: "Alegerea din secțiunea Taxe decide dacă TVA-ul se extrage din preț sau se adaugă peste el.",
          pasi: [
            "Intră în Setări > Taxe, cu Plătitor de TVA pornit.",
            "Coboară la întrebarea Prețurile produselor includ TVA.",
            "Apasă Da, prețurile includ TVA sau Nu, prețurile sunt fără TVA.",
            "Verifică efectul în cardul Previzualizare coș cumpărături.",
            "Apasă Salvează setările TVA.",
          ],
          detalii: [
            { titlu: "Ce arată previzualizarea", text: "Folosește mereu un exemplu fix de 100 lei și afișează rândurile Subtotal, TVA cu cota ta și Total. Când prețurile includ TVA, pe rândul de TVA apare mențiunea inclus." },
            { titlu: "Ce nu se schimbă", text: "Alegerea schimbă modul de calcul al totalului, nu prețurile scrise pe produsele tale. Nu trebuie să reintri în catalog după ce o schimbi." },
          ],
          termeni: ["pret cu tva", "pret fara tva", "calcul tva cos", "subtotal total"],
        },
        {
          slug: "cum-afisezi-tva-separat-in-cos",
          titlu: "Cum afișezi sau ascunzi valoarea TVA separat în coșul clientului",
          rezumat: "Un comutator din secțiunea Taxe decide dacă rândul de TVA apare în sumarul coșului.",
          pasi: [
            "Intră în Setări > Taxe, cu Plătitor de TVA pornit.",
            "Coboară la Afișează defalcarea TVA în coș.",
            "Mută comutatorul.",
            "Verifică în cardul Previzualizare coș cumpărături dacă rândul de TVA apare sau dispare.",
            "Apasă Salvează setările TVA.",
          ],
          detalii: [
            { titlu: "Ce se schimbă de fapt", text: "Doar afișarea. Dacă ești plătitor de TVA, TVA-ul se calculează oricum, indiferent dacă rândul se vede sau nu în sumar." },
          ],
          termeni: ["defalcare tva", "sumar cos", "afisare taxe client"],
        },
      ],
    },
  ],
};
