import { Rocket } from "lucide-react";
import type { CategorieAjutor } from "../ajutor-tipuri";

/**
 * Categoria „Primii pași” din centrul de ajutor.
 *
 * ⚠ TEXTELE SUNT CIORNĂ, scrise dintr-un audit al codului panoului, nu din cap.
 * Vezi `../ajutor.ts` pentru cum s-a făcut auditul și ce reguli de scriere se
 * aplică. Clientul le corectează.
 */
export const PRIMII_PASI: CategorieAjutor = {
  slug: "primii-pasi",
  titlu: "Primii pași",
  descriere: "Cont nou, panoul de administrare și publicarea magazinului.",
  icon: Rocket,
  grupuri: [
    {
      titlu: "Cont și înregistrare",
      ghiduri: [
        {
          slug: "cum-iti-creezi-cont-pe-edinio",
          titlu: "Cum îți creezi cont pe Edinio",
          rezumat: "Îți faci contul cu nume, email și parolă, apoi treci direct la configurarea magazinului.",
          intro: "Contul se face din pagina de înregistrare. Ai nevoie de nume, o adresă de email și o parolă.",
          pasi: [
            "Deschide pagina de înregistrare. Din pagina de conectare ajungi acolo prin linkul \"Creează cont gratuit\" de jos.",
            "Completează \"Numele tău complet\" cu numele tău, nu cu numele magazinului.",
            "Completează \"Adresa de email\". Cu ea te vei conecta și pe ea primești mesajele de la platformă.",
            {
              text: "Completează \"Parola\". Sub câmp vezi cele trei cerințe: \"Minim 8 caractere\", \"O literă mare\", \"Un număr\".",
              captura: { alt: "Formularul de înregistrare, cu cele trei cerințe afișate sub câmpul de parolă.", raport: 16 / 10 },
            },
            "Apasă iconița de ochi din dreapta câmpului dacă vrei să vezi ce ai scris.",
            "Completează \"Confirmă parola\" cu aceeași parolă.",
            "Bifează \"Sunt de acord cu Termenii și condițiile și Politica de confidențialitate\".",
            "Apasă \"Creează cont gratuit\". Cât timp se salvează, butonul scrie \"Se creează contul...\".",
            "Ajungi automat la primul pas de configurare a magazinului.",
          ],
          detalii: [
            { titlu: "Ce se cere în fiecare câmp", text: "\"Numele tău complet\" este numele persoanei care deține contul și are între 2 și 80 de caractere. \"Adresa de email\" este adresa de conectare. \"Parola\" trebuie să aibă minim 8 caractere, cel puțin o literă mare și cel puțin o cifră. \"Confirmă parola\" trebuie să fie identică cu parola." },
            { titlu: "Cum citești cerințele parolei", text: "Cât timp o cerință nu e îndeplinită, în dreptul ei stă un X gri. Când e îndeplinită, apare o bifă verde. Butonul de ochi se numește \"Arată parola\" și \"Ascunde parola\"." },
            { titlu: "Mesajele care pot apărea", text: "La nume prea scurt: \"Numele trebuie să aibă cel puțin 2 caractere\". La parolă, mesajul spune exact ce lipsește, de exemplu \"Parola trebuie să conțină cel puțin o literă mare\". Dacă cele două parole diferă: \"Parolele nu coincid\". Dacă nu ai bifat acordul: \"Trebuie să accepți termenii și condițiile\"." },
            { titlu: "Dacă adresa de email este deja folosită", text: "Vezi mesajul \"Există deja un cont cu această adresă de email.\". Înseamnă că ai deja cont pe acea adresă. Conectează-te cu ea, iar dacă nu îți amintești parola, folosește \"Ai uitat parola?\" din pagina de conectare. Pentru orice altă problemă apare \"Înregistrarea a eșuat. Încearcă din nou.\"." },
            { titlu: "Ce urmează după creare", text: "Ești dus la pasul 1 din configurare, unde completezi numele magazinului, telefonul și adresa online. Primești și emailul de bun venit, cu butonul \"Configurează magazinul\"." },
            { titlu: "Ce nu se cere aici", text: "Formularul nu are câmp de telefon, de firmă sau de CUI și nu cere card. Telefonul se completează la pasul 1 din configurare, iar plata doar dacă alegi un plan plătit." },
          ],
          nota: "Bifa cu Termenii și condițiile și Politica de confidențialitate este obligatorie. Fără ea, contul nu se creează.",
          termeni: ["înregistrare", "sign up", "înscriere", "parolă", "termeni și condiții", "email de bun venit"],
        },
        {
          slug: "cum-te-inregistrezi-sau-te-conectezi-cu-google",
          titlu: "Cum te înregistrezi sau te conectezi cu Google",
          rezumat: "Intri în Edinio cu contul tău Google, fără să îți setezi o parolă separată.",
          pasi: [
            {
              text: "Pe pagina de înregistrare apasă \"Înregistrare cu Google\". Dacă ai deja cont, pe pagina de conectare apasă \"Conectare cu Google\".",
              captura: { alt: "Butonul Google de sub separatorul \"sau\", pe pagina de înregistrare.", raport: 16 / 10 },
            },
            "Butonul scrie \"Se conectează...\" și ești trimis la ecranul Google.",
            "Alege contul Google și aprobă accesul.",
            "Te întorci în Edinio. Dacă nu ai terminat configurarea, ajungi la pasul 1 cu datele magazinului.",
            "Dacă ai terminat deja configurarea, intri direct în panoul de administrare.",
          ],
          detalii: [
            { titlu: "Cele două butoane nu fac exact același lucru", text: "Butonul de pe pagina de înregistrare duce mai departe și planul ales dintr-o campanie. Butonul de pe pagina de conectare nu transmite niciun plan. Dacă ai pornit dintr-o campanie cu plan ales, folosește butonul de pe pagina de înregistrare." },
            { titlu: "Cât se păstrează planul ales dinainte", text: "Planul reținut prin Google se păstrează cel mult 10 minute. Dacă durează mai mult până termini pașii, alegi planul manual la pasul 2." },
            { titlu: "Dacă autentificarea nu reușește", text: "Ești adus înapoi pe pagina de conectare, dar acolo nu apare niciun mesaj, vezi doar formularul gol. Încearcă din nou butonul Google sau conectează-te cu email și parolă." },
          ],
          nota: "Ai nevoie de un cont Google. Contul Google rămâne al tău, Edinio îl folosește doar ca să te recunoască la intrare.",
          termeni: ["autentificare", "google", "gmail", "login social", "fără parolă"],
        },
        {
          slug: "cum-te-conectezi-la-contul-tau",
          titlu: "Cum te conectezi la contul tău",
          rezumat: "Intri cu emailul și parola din pagina de conectare și ajungi în panoul de administrare.",
          pasi: [
            "Deschide pagina de conectare. Titlul de sus este \"Bine ai revenit\".",
            "Completează \"Adresa de email\".",
            "Completează \"Parola\". Poți apăsa iconița de ochi ca să vezi ce ai scris.",
            "Apasă \"Conectează-te\". Cât timp lucrează, butonul scrie \"Se conectează...\".",
            "Dacă ai verificarea în doi pași activată, ajungi la ecranul cu codul primit pe email.",
            "Dacă nu ai terminat configurarea magazinului, ajungi la pasul 1. Altfel intri direct în panoul de administrare.",
          ],
          detalii: [
            { titlu: "Dacă datele nu sunt acceptate", text: "Apare un singur mesaj, \"Email sau parolă incorectă. Încearcă din nou.\", fără să spună care câmp e greșit. Verifică dacă ai lăsat majuscule pornite sau un spațiu în plus la începutul adresei. Dacă nu îți amintești parola, folosește \"Ai uitat parola?\"." },
            { titlu: "Dacă lași un câmp gol", text: "Fără email: \"Adresa de email este obligatorie\". Cu o adresă scrisă greșit: \"Adresa de email nu este validă\". Fără parolă: \"Parola este obligatorie\"." },
            { titlu: "Când ai fost trimis la conectare dintr-o pagină din panou", text: "După conectare ajungi în pagina principală a panoului, nu în pagina de la care ai plecat. Deschide din nou pagina care te interesa." },
            { titlu: "Ce nu există la conectare", text: "Nu există opțiunea de a ține contul minte și nici conectare printr-un link trimis pe email. Dacă nu ai cont, folosește \"Creează cont gratuit\" din josul paginii." },
          ],
          nota: "Dacă îți lipsește un cont, pagina de conectare nu îl creează. Trebuie să treci prin înregistrare.",
          termeni: ["autentificare", "login", "intru în cont", "email sau parolă incorectă", "acces panou"],
        },
        {
          slug: "cum-confirmi-conectarea-cu-codul-primit-pe-email",
          titlu: "Cum confirmi conectarea cu codul primit pe email",
          rezumat: "Cu verificarea în doi pași activă, după parolă introduci un cod de 6 cifre primit pe email.",
          pasi: [
            "Conectează-te cu emailul și parola. Dacă ai verificarea în doi pași activă, ajungi pe ecranul \"Verificare în doi pași\".",
            "Deschide emailul primit. Codul de 6 cifre apare chiar în subiectul mesajului.",
            {
              text: "Scrie codul în câmpul \"Cod de verificare\".",
              captura: { alt: "Ecranul de verificare în doi pași, cu câmpul pentru codul de 6 cifre.", raport: 16 / 10 },
            },
            "Apasă \"Verifică\". Cât timp lucrează, butonul scrie \"Se verifică...\".",
            "Intri în panoul de administrare, sau la pasul 1 de configurare dacă nu l-ai terminat.",
          ],
          detalii: [
            { titlu: "Cât e valabil codul", text: "Zece minute. Pe ecran scrie \"Codul este valabil 10 minute. Dacă nu ai primit emailul, verifică folderul Spam.\"." },
            { titlu: "Dacă butonul nu se apasă", text: "Butonul \"Verifică\" rămâne inactiv până introduci 6 cifre. Câmpul primește doar cifre, literele și semnele sunt ignorate automat." },
            { titlu: "Dacă a expirat sau codul e greșit", text: "Vezi \"Cod incorect sau expirat.\", \"Codul a expirat. Autentifică-te din nou.\" sau \"Sesiune expirată. Autentifică-te din nou.\". Pe acest ecran nu există buton de retrimitere. Reia conectarea de la pagina de conectare și primești un cod nou." },
            { titlu: "Cât timp nu confirmi codul", text: "Orice pagină din panou te aduce înapoi pe ecranul de verificare. Nu poți intra în panou până nu introduci codul." },
          ],
          nota: "Codul vine doar pe email. Nu există aplicație de autentificare și nici SMS.",
          termeni: ["2FA", "cod de 6 cifre", "verificare în doi pași", "nu primesc codul", "spam"],
        },
        {
          slug: "cum-iti-resetezi-parola-uitata",
          titlu: "Cum îți resetezi parola dacă ai uitat-o",
          rezumat: "Ceri un link pe email din pagina de conectare, apoi setezi parola nouă din acel link.",
          pasi: [
            "Pe pagina de conectare apasă \"Ai uitat parola?\", linkul din dreptul câmpului de parolă.",
            "Pe pagina \"Resetare parolă\" completează \"Adresa de email\".",
            "Apasă \"Trimite link de resetare\". Cât timp lucrează, butonul scrie \"Se trimite...\".",
            "Ecranul se schimbă în confirmarea \"Email trimis\".",
            "Deschide emailul primit și apasă linkul de resetare. Ajungi pe pagina \"Parolă nouă\".",
            "Completează \"Parolă nouă\" și \"Confirmă parola nouă\".",
            "Apasă \"Setează parola nouă\". Cât timp salvează, butonul scrie \"Se salvează...\".",
            "La confirmarea \"Parola a fost resetată\" apasă \"Mergi la autentificare\" și intră cu parola nouă.",
          ],
          detalii: [
            { titlu: "Ce reguli are parola nouă", text: "Minim 8 caractere, cel puțin o literă mare și cel puțin o cifră, iar cele două câmpuri trebuie să fie identice. Pagina de resetare nu afișează bifele de la înregistrare, deci verifici singur regulile înainte să salvezi. La nepotrivire apare \"Parolele nu coincid\"." },
            { titlu: "De ce mesajul de confirmare e la fel de fiecare dată", text: "Textul \"Dacă există un cont cu această adresă, vei primi un email cu instrucțiunile de resetare a parolei.\" apare indiferent dacă adresa există sau nu în platformă. Așa nu se poate afla din afară cine are cont. Dacă nu primești nimic, verifică folderul Spam și dacă ai scris adresa corect." },
            { titlu: "Dacă linkul nu mai merge", text: "Vezi \"Nu am putut reseta parola. Link-ul poate fi expirat.\". Întoarce-te la \"Ai uitat parola?\" și cere un link nou." },
            { titlu: "Dacă emailul nu pleacă", text: "Apare \"Nu am putut trimite email-ul de resetare. Încearcă din nou.\". Mai încearcă o dată butonul." },
          ],
          nota: "Pagina de parolă nouă funcționează doar dacă ajungi la ea din linkul primit pe email. Linkul creează sesiunea de care are nevoie pagina.",
          termeni: ["am uitat parola", "resetare", "link pe email", "parolă nouă", "recuperare cont"],
        },
        {
          slug: "cum-completezi-datele-magazinului-la-pasul-1",
          titlu: "Cum completezi datele magazinului la pasul 1 din configurare",
          rezumat: "Numele magazinului, telefonul și adresa online sunt cele trei date cu care pornește magazinul.",
          intro: "Pasul 1 apare imediat după ce îți faci contul. Ecranul se numește \"Creează-ți magazinul\", iar sus scrie \"Pasul 1 din 2\".",
          pasi: [
            "Completează \"Numele magazinului\". Este numele pe care îl văd clienții.",
            "Completează \"Numărul de telefon\" în formatul 07XXXXXXXX. La acest număr te contactează clienții.",
            "Verifică \"Adresa magazinului online\". Se completează singură din numele magazinului, dar o poți schimba.",
            {
              text: "Uită-te sub câmp, unde vezi adresa finală în forma edinio.com/adresa-ta.",
              captura: { alt: "Câmpul cu adresa magazinului online și previzualizarea edinio.com de sub el.", raport: 16 / 10 },
            },
            "Așteaptă verificarea. Bifa verde din dreapta câmpului înseamnă că adresa e liberă, X-ul roșu că e deja folosită.",
            "Apasă \"Continuă\" și treci la alegerea planului.",
          ],
          detalii: [
            { titlu: "Regulile fiecărui câmp", text: "Numele magazinului are între 2 și 100 de caractere, la mai puțin apare \"Minim 2 caractere\". Telefonul se acceptă doar ca număr de 10 cifre care începe cu 07, altfel apare \"Format invalid: 07XXXXXXXX\". Spațiile, liniuțele, parantezele și semnul plus sunt eliminate automat. Adresa online are între 3 și 50 de caractere și primește doar litere mici, cifre și liniuțe." },
            { titlu: "Cum se construiește adresa online", text: "Diacriticele și spațiile din numele magazinului sunt transformate automat, ă devine a, ș devine s, ț devine t. Dacă magazinul se numește Florăria Mirei, adresa propusă este floraria-mirei, iar linkul devine edinio.com/floraria-mirei. Caracterele nepermise sunt șterse pe măsură ce scrii." },
            { titlu: "Când butonul Continuă nu se apasă", text: "Butonul stă inactiv cât timp se verifică adresa și cât timp adresa e ocupată. Schimbă adresa și așteaptă bifa verde." },
            { titlu: "Atenție la adresele care seamănă cu paginile platformei", text: "Verificarea se uită doar în lista de magazine. Cuvinte ca blog, contact sau integrari sunt pagini ale platformei și nu ar funcționa ca adresă de magazin, chiar dacă apar ca disponibile. Alege ceva legat de numele magazinului tău." },
            { titlu: "Ce nu se cere la acest pas", text: "Nu se cer logo, culori sau descriere. Sub buton scrie \"Poți adăuga logo, descriere și toate detaliile din dashboard după creare\"." },
          ],
          nota: "Pasul se poate deschide doar cât timp configurarea nu e terminată. După ce magazinul e creat, adresele de configurare te duc în panoul de administrare.",
          termeni: ["onboarding", "link magazin", "slug", "număr de telefon", "adresă online", "nume magazin"],
        },
        {
          slug: "cum-alegi-planul-si-creezi-magazinul",
          titlu: "Cum alegi planul și creezi magazinul la pasul 2",
          rezumat: "Alegi intervalul de facturare și planul, apoi magazinul se creează, cu plată sau pe testare gratuită.",
          pasi: [
            "După \"Continuă\" ajungi pe ecranul \"Alege planul potrivit\", cu \"Pasul 2 din 2\" sus.",
            "Alege intervalul din comutatorul de sus: \"Lunar\" sau \"Anual\". Lângă \"Anual\" scrie \"3 luni gratis\".",
            {
              text: "Apasă pe cartonașul planului dorit. Cartonașul ales afișează jos \"Selectat\", celelalte \"Selectează\".",
              captura: { alt: "Cartonașele celor patru planuri, cu comutatorul Lunar și Anual deasupra.", raport: 16 / 10 },
            },
            "Verifică sub preț cum se facturează, \"Facturat lunar\" sau \"Facturat anual\" cu totalul pe an.",
            "Apasă butonul din dreapta jos. Pentru testare gratuită scrie \"Creează magazinul gratuit\", pentru un plan plătit \"Plătește și creează magazinul\".",
            "La plan plătit ești trimis la pagina de plată cu cardul. După plată te întorci și pe ecran apare \"Se creează magazinul tău...\".",
            "Vezi confirmarea că magazinul a fost creat și intri în panoul de administrare.",
          ],
          detalii: [
            { titlu: "Ce conține fiecare plan", text: "\"Testare gratuită\" este gratuită 15 zile și permite până la 10 produse. \"Basic\" costă 99 lei pe lună și merge până la 500 de produse. \"Premium\" costă 249 lei pe lună, merge până la 2.500 de produse și adaugă manager dedicat. \"Ultra\" costă 499 lei pe lună și are produse nelimitate. Toate au comenzi nelimitate și suport 7 zile din 7, iar planurile plătite includ mentenanță gratuită pe viață." },
            { titlu: "Cum se calculează planul anual", text: "La facturare anuală plătești 9 luni pentru 12, adică 891 lei la Basic, 2241 lei la Premium și 4491 lei la Ultra, o dată pe an. Economia este echivalentul a 3 luni." },
            { titlu: "Ce se întâmplă cu testarea gratuită", text: "Ține 15 zile de la crearea magazinului și acceptă maxim 10 produse. După ce expiră, panoul se blochează pe ecranul de reactivare, de unde alegi un plan plătit. Datele rămân la locul lor." },
            { titlu: "Limita de produse se aplică efectiv", text: "Când o depășești, apare mesajul \"Ai atins limita de ... produse pentru planul tău. Upgradează planul pentru mai multe produse.\". Limitele sunt 10 pe testare, 500 pe Basic, 2500 pe Premium și fără limită pe Ultra." },
            { titlu: "De ce butonul principal nu se apasă", text: "Cât timp nu ai selectat niciun plan, butonul scrie \"Creează magazinul gratuit\" și stă inactiv. Devine \"Plătește și creează magazinul\" doar după ce selectezi un plan plătit." },
            { titlu: "Dacă renunți la pagina de plată", text: "Revii pe pagina de planuri cu mesajul \"Plata a fost anulată. Selectează un plan pentru a continua.\", iar planul ales rămâne selectat. De acolo poți alege alt plan, inclusiv testarea gratuită." },
            { titlu: "Mesaje care pot opri crearea", text: "\"Planul anual nu este disponibil momentan.\" înseamnă că trebuie să treci pe \"Lunar\". \"Această adresă de magazin este deja folosită. Alege alta.\" înseamnă că cineva a luat adresa între timp, întoarce-te cu \"Înapoi\" și schimb-o. Mai pot apărea \"Nu am putut crea magazinul. Încearcă din nou.\", \"Eroare la inițializarea plății.\" sau \"A apărut o eroare. Încearcă din nou.\"." },
            { titlu: "Cum te întorci la pasul 1", text: "Butonul \"Înapoi\" este jos în stânga pe ecrane late. Pe telefon apare sub butonul principal." },
            { titlu: "Cum arată magazinul imediat după creare", text: "Magazinul pornește cu verdele platformei ca și culoare principală. Logo, culori și restul detaliilor le schimbi apoi din panoul de administrare. Primești și emailul care anunță că magazinul tău este live." },
          ],
          nota: "Pagina de plan se deschide doar dacă ai trecut prin pasul 1 în aceeași navigare. Dacă o deschizi direct, ești trimis înapoi la datele magazinului.",
          termeni: ["abonament", "prețuri", "plată card", "testare gratuită", "facturare anuală", "limita de produse"],
        },
        {
          slug: "cum-incepi-inregistrarea-cu-un-plan-ales-dinainte",
          titlu: "Cum începi înregistrarea cu un plan ales dinainte",
          rezumat: "Dacă pornești de pe butonul unui plan, plata se deschide singură după datele magazinului.",
          pasi: [
            "Pe pagina de start apasă butonul planului dorit. Ajungi pe formularul de înregistrare, cu planul reținut.",
            "Creează contul normal, cu email și parolă sau cu \"Înregistrare cu Google\".",
            "Completează pasul 1 cu datele magazinului și apasă \"Continuă\".",
            "La pasul 2 nu mai alegi nimic. Ești trimis direct la pagina de plată pentru planul ales, cu facturare lunară.",
          ],
          detalii: [
            { titlu: "Ce planuri se pot alege dinainte", text: "Doar \"Basic\", \"Premium\" și \"Ultra\". Testarea gratuită nu se poate porni astfel, ea se alege la pasul 2." },
            { titlu: "De ce facturarea este lunară", text: "Pe acest drum nu treci prin comutatorul \"Lunar\" și \"Anual\", deci plata pornește pe interval lunar." },
            { titlu: "Dacă vrei facturare anuală sau alt plan", text: "Renunță la pagina de plată. Revii pe pagina de planuri cu mesajul \"Plata a fost anulată. Selectează un plan pentru a continua.\" și de acolo alegi ce vrei, inclusiv \"Anual\" sau testarea gratuită." },
            { titlu: "Dacă intri cu Google", text: "Planul reținut se păstrează cel mult 10 minute. Funcționează doar dacă apeși butonul Google de pe pagina de înregistrare, cel de pe pagina de conectare nu duce planul mai departe." },
          ],
          nota: "Planul reținut nu blochează nimic. Îl poți schimba din pagina de planuri înainte de a plăti.",
          termeni: ["campanie", "plan preselectat", "basic", "premium", "ultra", "pagina de start"],
        },
        {
          slug: "cum-parcurgi-lista-de-configurare-din-panou",
          titlu: "Cum parcurgi lista Configurează-ți magazinul din panou",
          rezumat: "Cardul din prima pagină a panoului îți arată cei patru pași cu care pui magazinul pe picioare.",
          pasi: [
            "Intră în panoul de administrare > \"Panou principal\".",
            {
              text: "Găsește cardul \"Configurează-ți magazinul\", cu bara de progres și numărul de pași făcuți.",
              captura: { alt: "Cardul Configurează-ți magazinul, cu bara de progres și cei patru pași.", raport: 16 / 10 },
            },
            "La \"Adaugă primul produs\" apasă \"Adaugă\" și completează formularul de produs nou.",
            "La \"Personalizează magazinul\" apasă \"Personalizează\". Ajungi în pagina de editare, unde pui logo, culori și detaliile magazinului.",
            "La \"Publică magazinul\" apasă \"Publică\". Ajungi tot în pagina de editare.",
            "La \"Primește prima comandă\" apasă \"Distribuie\". Linkul magazinului se copiază și îl poți trimite pe WhatsApp sau pe rețele.",
            "Pașii terminați rămân tăiați și marcați cu \"Gata\".",
          ],
          detalii: [
            { titlu: "Cum strângi lista", text: "Săgeata din dreapta sus a cardului o restrânge și o extinde la loc, butonul se numește \"Restrânge\" și \"Extinde\"." },
            { titlu: "Când dispare cardul", text: "Pe un plan plătit, cardul dispare de tot când toți pașii sunt bifați. Pe testare gratuită, în locul listei apare mesajul de felicitare și butonul \"Alege un plan\", care te duce în \"Setări\", secțiunea \"Plan\"." },
            { titlu: "Pasul de personalizare se bifează la vizitare", text: "Se marchează ca făcut și doar dacă ai deschis pagina de editare, chiar dacă nu ai încărcat logo. Verifică singur dacă ai pus tot ce voiai acolo." },
            { titlu: "Dacă linkul nu se copiază", text: "Apare \"Nu am putut copia link-ul. Copiază-l manual din bara de sus.\". Ia linkul de acolo și trimite-l." },
          ],
          nota: "Cardul apare doar după ce magazinul este creat.",
          termeni: ["checklist", "pași de început", "primul produs", "distribuie link", "publicare magazin"],
        },
        {
          slug: "cum-iti-schimbi-numele-contului",
          titlu: "Cum îți schimbi numele contului",
          rezumat: "Numele contului se modifică din Setări, secțiunea General. Adresa de email nu se poate schimba singur.",
          pasi: [
            "Intră în panoul de administrare > \"Setări\".",
            "Rămâi pe secțiunea \"General\", prima din lista din stânga.",
            "Coboară la cardul \"Contul tău\".",
            "Schimbă câmpul \"Numele complet\".",
            "Apasă \"Salvează contul\". Cât timp lucrează, butonul scrie \"Se salvează...\".",
            "Apare confirmarea \"Profilul a fost actualizat.\".",
          ],
          detalii: [
            { titlu: "Unde se vede numele", text: "Numele apare în panoul de administrare, în meniul din dreapta sus, și este folosit în emailurile pe care le primești de la platformă." },
            { titlu: "Adresa de email nu se poate modifica de aici", text: "Câmpul \"Adresa de email\" este afișat, dar blocat. Sub el scrie \"Contactați suportul pentru schimbarea adresei de email.\". Scrie la contact@edinio.com dacă ai nevoie de schimbare." },
            { titlu: "Ce nu schimbi din acest card", text: "Aici modifici numele persoanei care deține contul, nu numele magazinului văzut de clienți." },
          ],
          termeni: ["profil", "date personale", "nume complet", "schimbare email", "setări cont"],
        },
        {
          slug: "cum-iti-schimbi-parola-din-cont",
          titlu: "Cum îți schimbi parola din contul tău",
          rezumat: "Din Setări, secțiunea Securitate, setezi o parolă nouă fără să ți se ceară cea veche.",
          pasi: [
            "Intră în panoul de administrare > \"Setări\".",
            "Din lista din stânga alege \"Securitate\".",
            "În cardul \"Schimbă parola\" completează \"Parolă nouă\".",
            "Completează \"Confirmă parola nouă\" cu aceeași parolă.",
            "Apasă \"Schimbă parola\". Cât timp lucrează, butonul scrie \"Se schimbă...\".",
            "Apare confirmarea \"Parola a fost schimbată cu succes.\" și câmpurile se golesc.",
          ],
          detalii: [
            { titlu: "Nu ți se cere parola veche", text: "Schimbarea se face doar din contul deja deschis. Înseamnă și că cine ajunge la o sesiune deschisă a ta îți poate schimba parola, deci nu lăsa contul conectat pe un calculator străin." },
            { titlu: "Ce se verifică aici", text: "Se verifică doar lungimea, minim 8 caractere. Litera mare și cifra nu sunt cerute în acest ecran, deși la înregistrare sunt obligatorii. Alege oricum o parolă cu literă mare și cifră." },
            { titlu: "Mesaje care pot apărea", text: "\"Parolele nu coincid.\" dacă cele două câmpuri diferă, \"Parola trebuie să aibă cel puțin 8 caractere.\" dacă e prea scurtă și \"Nu am putut schimba parola.\" la o problemă tehnică. Butonul rămâne inactiv până completezi ambele câmpuri." },
          ],
          nota: "Dacă nu îți amintești parola și nu ești conectat, folosește \"Ai uitat parola?\" din pagina de conectare.",
          termeni: ["securitate", "parolă nouă", "schimbare parolă", "setări", "cont protejat"],
        },
        {
          slug: "cum-activezi-verificarea-in-doi-pasi",
          titlu: "Cum activezi verificarea în doi pași",
          rezumat: "Activezi 2FA din Setări, secțiunea Securitate, confirmând un cod primit pe email.",
          pasi: [
            "Intră în panoul de administrare > \"Setări\" > \"Securitate\".",
            {
              text: "Găsește cardul \"Autentificare în doi pași (2FA)\". Caseta de sub explicație îți arată adresa pe care va veni codul.",
              captura: { alt: "Cardul Autentificare în doi pași, cu adresa de email pe care va veni codul.", raport: 16 / 10 },
            },
            "Apasă \"Activează 2FA\". Cât timp trimite codul, butonul scrie \"Se trimite codul...\".",
            "Deschide emailul și ia codul de 6 cifre.",
            "Scrie codul în câmpul \"Cod de verificare\". Poți apăsa Enter în loc de buton.",
            "Apasă \"Verifică și activează\".",
            "Apare confirmarea că verificarea a fost activată, iar în colțul cardului apare eticheta \"Activ\".",
          ],
          detalii: [
            { titlu: "Ce se schimbă la conectare", text: "După ce introduci emailul și parola, ajungi pe ecranul \"Verificare în doi pași\" și scrii codul primit pe email. Fără cod nu intri în panou." },
            { titlu: "Cât e valabil codul", text: "Zece minute. După ce expiră vezi \"Codul a expirat. Încearcă din nou.\", apeși din nou \"Activează 2FA\" și primești un cod nou. La cod greșit apare \"Cod incorect sau expirat.\"." },
            { titlu: "Butoanele din card", text: "\"Verifică și activează\" rămâne inactiv până introduci 6 cifre. Cu \"Anulează\" renunți oricând, iar 2FA rămâne oprită." },
            { titlu: "Codul vine doar pe email", text: "Nu există aplicație de autentificare și nici SMS. Activează verificarea doar dacă ai acces sigur la casuța de email a contului." },
          ],
          termeni: ["2FA", "securitate cont", "cod pe email", "autentificare în doi pași", "protecție"],
        },
        {
          slug: "cum-dezactivezi-verificarea-in-doi-pasi",
          titlu: "Cum dezactivezi verificarea în doi pași",
          rezumat: "Oprirea 2FA se face tot cu un cod primit pe email, din Setări, secțiunea Securitate.",
          pasi: [
            "Intră în panoul de administrare > \"Setări\" > \"Securitate\".",
            "În cardul \"Autentificare în doi pași (2FA)\" vezi că funcția e activă și pe ce adresă vine codul.",
            "Apasă \"Dezactivează 2FA\". Cât timp trimite codul, butonul scrie \"Se trimite codul...\".",
            "Deschide emailul și ia codul de 6 cifre.",
            "Scrie codul în câmpul \"Cod de verificare\".",
            "Apasă \"Confirmă dezactivarea\". Apare confirmarea că verificarea a fost dezactivată.",
          ],
          detalii: [
            { titlu: "De ce se cere un cod și la oprire", text: "Verificarea nu se oprește dintr-un simplu comutator. Codul confirmă că cel care oprește protecția are acces la casuța de email a contului." },
            { titlu: "Butoanele din card", text: "\"Confirmă dezactivarea\" rămâne inactiv până introduci 6 cifre. Cu \"Anulează\" te oprești, iar 2FA rămâne activă." },
            { titlu: "Ce se schimbă după", text: "La următoarea conectare intri direct cu email și parolă, fără ecranul cu cod." },
          ],
          nota: "Dacă nu mai ai acces la casuța de email a contului, nu poți parcurge acest pas.",
          termeni: ["oprire 2FA", "dezactivare", "cod pe email", "securitate", "setări"],
        },
        {
          slug: "cum-iesi-din-cont",
          titlu: "Cum ieși din cont",
          rezumat: "Deconectarea se face din meniul de cont, din colțul din dreapta sus al panoului.",
          pasi: [
            "În panoul de administrare apasă pe cercul cu inițialele tale din colțul din dreapta sus. Pe ecrane late apare lângă el și numele tău, sau \"Contul meu\" dacă nu ai completat un nume.",
            "În meniul care se deschide vezi numele și planul tău.",
            "Apasă \"Deconectează-te\".",
            "Ajungi înapoi pe pagina de conectare.",
          ],
          detalii: [
            { titlu: "Ce mai găsești în meniu", text: "Singura altă opțiune este \"Setări cont\", care te duce în pagina de setări." },
            { titlu: "Pe telefon", text: "În sertarul de meniu de pe ecrane mici există doar iconița de ieșire, fără text scris lângă ea." },
            { titlu: "De pe ecranul de reactivare", text: "Când contul e blocat pe ecranul de reactivare, butonul \"Deconectează-te\" se află în josul acelei pagini." },
          ],
          termeni: ["logout", "deconectare", "ies din cont", "schimb utilizator", "meniu cont"],
        },
        {
          slug: "cum-reactivezi-contul-dupa-expirare",
          titlu: "Cum reactivezi contul după expirarea testării sau a abonamentului",
          rezumat: "Alegi un plan plătit din ecranul de reactivare și accesul la panou revine după plată.",
          pasi: [
            "Când testarea sau abonamentul a expirat, în locul panoului vezi ecranul cu titlul \"Perioada de testare a expirat\" sau \"Abonamentul tău a expirat\".",
            "Alege intervalul de facturare: \"Lunar\" sau \"Anual\".",
            {
              text: "Alege unul dintre planurile plătite: \"Basic\", \"Premium\" sau \"Ultra\".",
              captura: { alt: "Ecranul de reactivare, cu cele trei planuri plătite și comutatorul de facturare.", raport: 16 / 10 },
            },
            "Apasă \"Reactivează și plătește\". Cât timp lucrează, butonul scrie \"Redirecționare către plată...\".",
            "Plătește cu cardul pe pagina de plată.",
            "Te întorci pe ecranul \"Se activează abonamentul...\", care se reîmprospătează singur până se deschide accesul.",
            "Când accesul e gata intri în panoul de administrare. Dacă durează, apare și linkul \"Mergi la dashboard\".",
          ],
          detalii: [
            { titlu: "Ce se întâmplă cu datele tale", text: "Pe ecran scrie \"Datele tale (produse, comenzi, setări) sunt păstrate integral.\". Produsele, comenzile și setările rămân acolo unde le-ai lăsat." },
            { titlu: "Aici nu poți alege testarea gratuită", text: "Ecranul afișează doar planuri plătite. Planul propus este cel pe care îl aveai, iar dacă nu era unul plătit, apare preselectat \"Premium\"." },
            { titlu: "Cât se reîmprospătează pagina după plată", text: "Se reîncarcă la fiecare 3 secunde, de cel mult 20 de ori, adică în jur de un minut. Dacă tot nu intri, reîncarcă pagina din browser." },
            { titlu: "Dacă plata nu pornește", text: "Vezi \"Eroare la inițializarea plății.\" sau \"Eroare de rețea. Încearcă din nou.\". Mai apasă o dată butonul, iar dacă se repetă, scrie la contact@edinio.com." },
            { titlu: "Ce mai poți face din acest ecran", text: "Din josul paginii poți apăsa \"Deconectează-te\" sau poți cere ajutor la contact@edinio.com." },
          ],
          nota: "Ecranul apare doar cât timp contul e inactiv. Când abonamentul este activ, ești trimis direct în panoul de administrare.",
          termeni: ["trial expirat", "abonament expirat", "blocat", "plată", "reactivare cont"],
        },
        {
          slug: "cum-stergi-definitiv-contul",
          titlu: "Cum ștergi definitiv contul",
          rezumat: "Ștergerea se cere din Setări, secțiunea Securitate, și se confirmă scriind adresa ta de email.",
          pasi: [
            "Intră în panoul de administrare > \"Setări\" > \"Securitate\".",
            "Coboară la cardul \"Zona periculoasă\" și citește avertizarea de la \"Șterge contul\".",
            "Apasă butonul \"Șterge contul\".",
            "În caseta \"Confirmă ștergerea contului\" scrie adresa ta de email exact cum apare pe cont.",
            "Apasă \"Confirmă ștergerea\". Cât timp lucrează, butonul scrie \"Se șterge...\".",
            "Ești scos din cont și dus la pagina de conectare.",
          ],
          detalii: [
            { titlu: "Ce se șterge", text: "În casetă scrie \"Această acțiune va șterge permanent contul tău, magazinele, produsele și toate comenzile. Nu poate fi anulată.\". Se pierde tot ce ține de cont, nu doar accesul." },
            { titlu: "De ce butonul stă inactiv", text: "\"Confirmă ștergerea\" se activează abia când textul scris coincide exact cu adresa de email a contului. Scrie adresa fără spații în plus." },
            { titlu: "Cum renunți", text: "Butonul \"Anulează\" închide caseta și nu se șterge nimic." },
            { titlu: "Dacă ștergerea nu merge", text: "Poți vedea \"Ștergerea contului nu este disponibilă momentan. Contactați suportul.\" sau \"Eroare la ștergerea contului. Încearcă din nou.\". Reîncearcă, iar dacă se repetă, scrie la contact@edinio.com." },
          ],
          nota: "Ștergerea este definitivă și nu poate fi anulată după confirmare.",
          termeni: ["închidere cont", "zona periculoasă", "ștergere date", "renunț la Edinio", "anulare cont"],
        },
      ],
    },
    {
      titlu: "Panoul principal",
      ghiduri: [
        {
          slug: "cum-deschizi-panoul-principal",
          titlu: "Cum deschizi Panoul principal",
          rezumat: "Unde găsești Panoul principal pe desktop și pe telefon și ce condiții trebuie îndeplinite ca să îl poți vedea.",
          intro: "Panoul principal este prima pagină din panoul de administrare, la adresa /dashboard.",
          pasi: [
            {
              text: "Pe desktop, în meniul lateral apasă primul element, \"Panou principal\".",
              captura: { alt: "Meniul lateral cu elementul \"Panou principal\" marcat activ, în partea de sus a listei.", raport: 16 / 10 },
            },
            "Pe telefon, apasă \"Acasă\" în bara de jos.",
            "Tot pe telefon, poți deschide meniul cu butonul de meniu (eticheta pentru cititoarele de ecran este \"Deschide meniu\") și apoi apasă \"Panou principal\".",
            "Verifică adresa paginii: trebuie să fie /dashboard.",
          ],
          detalii: [
            { titlu: "Ce trebuie să fie în regulă ca să intri", text: "Trebuie să fii autentificat, altfel ești trimis la /login. Onboarding-ul trebuie finalizat, altfel ești trimis la /onboarding/details. Și trebuie să existe cel puțin un magazin pe cont, altfel ajungi tot la /onboarding/details." },
            { titlu: "Când tot panoul este blocat", text: "Dacă abonamentul nu mai este activ, nu intri deloc în panou și ești trimis la /reactivare. Se întâmplă când perioada de testare gratuită a expirat, când perioada de grație a unui abonament plătit a expirat, sau când un plan plătit are data de expirare mai veche de 45 de zile și nu are dată de suspendare. Conturile cu rol de administrator fac excepție." },
            { titlu: "Panoul arată un singur magazin", text: "Toate datele din Panoul principal, statistici, grafic, comenzi recente, stoc scăzut, sunt ale unui singur magazin: cel creat cel mai recent pe cont. În această zonă nu există un selector prin care să schimbi magazinul afișat." },
            { titlu: "Când se aprinde elementul din meniu", text: "\"Panou principal\" apare marcat ca activ doar când adresa este exact /dashboard. Dacă ești pe o subpagină, de exemplu /dashboard/products, elementul nu mai este evidențiat." },
          ],
          nota: "Panoul arată datele unui singur magazin, cel creat cel mai recent. Nu poți schimba magazinul din această zonă.",
          termeni: ["dashboard", "acasa", "prima pagina", "meniu lateral", "reactivare", "onboarding", "redirect login"],
        },
        {
          slug: "cum-publici-magazinul-din-bara-de-status",
          titlu: "Cum publici magazinul din bara de status a Panoului principal",
          rezumat: "Publici magazinul direct din capul Panoului principal, fără să intri în editor.",
          pasi: [
            "Intră în Panou principal.",
            "În capul paginii, dacă magazinul nu este publicat, vezi mesajul \"Site-ul tău nu este publicat. Clienții nu îl pot vedea.\"",
            {
              text: "Apasă \"Publică acum\".",
              captura: { alt: "Bara de status din capul paginii, cu mesajul că site-ul nu este publicat și butonul \"Publică acum\" în dreapta.", raport: 16 / 10 },
            },
            "Se deschide fereastra \"Publici magazinul?\". Citește textul și apasă \"Publică magazinul\".",
            "Dacă te răzgândești, apasă \"Anulează\".",
            "Când publicarea reușește apare mesajul \"Magazinul a fost publicat! Este vizibil public.\", iar bara trece în starea publicată.",
          ],
          detalii: [
            { titlu: "Ce scrie în fereastra de confirmare", text: "Textul este: adresa magazinului tău va deveni vizibilă public și clienții vor putea plasa comenzi. Poți opri publicarea oricând din editor. Adresa afișată în fereastră este chiar adresa publică a magazinului tău." },
            { titlu: "Ce se întâmplă cât se salvează", text: "În timpul salvării, butoanele \"Anulează\" și \"Publică magazinul\" sunt dezactivate, iar fereastra nu se închide dacă apeși pe fundal. Așteaptă până se termină." },
            { titlu: "Dacă publicarea nu reușește", text: "Când salvarea eșuează apare mesajul \"Nu am putut salva modificările.\" Încearcă din nou. Dacă vezi \"Nu ești autentificat.\", sesiunea ta a expirat: intră din nou în cont și reia publicarea." },
            { titlu: "Oprirea publicării", text: "Din bara de status se poate doar publica. Ca să scoți magazinul de la publicare, intră în Editează magazinul." },
            { titlu: "Când nu vezi această bară", text: "Bara cu \"Publică acum\" apare doar cât timp magazinul este nepublicat. După publicare, în locul ei apare eticheta \"Publicat\" cu adresa magazinului." },
          ],
          nota: "Din bara de status poți doar publica. Oprirea publicării se face din editor.",
          termeni: ["publicare site", "magazin vizibil", "publica acum", "site nepublicat", "activare magazin"],
        },
        {
          slug: "cum-copiezi-si-deschizi-linkul-magazinului",
          titlu: "Cum copiezi linkul magazinului și îl deschizi din Panoul principal",
          rezumat: "Din bara de status a unui magazin publicat copiezi adresa publică sau deschizi magazinul într-o filă nouă.",
          pasi: [
            "Intră în Panou principal. Magazinul trebuie să fie publicat.",
            {
              text: "În capul paginii vezi eticheta \"Publicat\" și adresa publică a magazinului.",
              captura: { alt: "Bara de status cu eticheta \"Publicat\", adresa magazinului și butoanele \"Copiază link\" și \"Vizualizează\".", raport: 16 / 10 },
            },
            "Apasă \"Copiază link\". Textul butonului devine \"Copiat!\", apoi revine.",
            "Apasă \"Vizualizează\" din dreapta barii ca să deschizi magazinul public într-o filă nouă.",
            "Poți apăsa și direct pe adresa afișată lângă eticheta \"Publicat\", care duce în aceeași pagină publică.",
          ],
          detalii: [
            { titlu: "Ce adresă se copiază", text: "Se copiază adresa publică a magazinului tău: domeniul personalizat dacă ai configurat unul, altfel adresa de forma site/slugul magazinului." },
            { titlu: "Cât ține confirmarea", text: "\"Copiat!\" rămâne pe buton 2 secunde, apoi textul revine la \"Copiază link\". Dacă ai ratat momentul, linkul este oricum deja în clipboard." },
            { titlu: "De ce adresa apare fără https", text: "În bară adresa se afișează fără prefixul http sau https, ca să fie mai scurtă. Linkul copiat și cel deschis duc la aceeași pagină publică." },
            { titlu: "Când nu vezi această bară", text: "Eticheta \"Publicat\" și butoanele apar doar când magazinul este publicat. Cât timp nu este publicat, în capul paginii apare mesajul de nepublicat și butonul \"Publică acum\"." },
          ],
          termeni: ["link magazin", "adresa publica", "copiaza link", "vizualizeaza", "domeniu personalizat", "slug"],
        },
        {
          slug: "cum-parcurgi-lista-configureaza-ti-magazinul",
          titlu: "Cum parcurgi lista \"Configurează-ți magazinul\"",
          rezumat: "Cei patru pași de pornire din Panoul principal, ce face fiecare buton și când se bifează fiecare pas.",
          intro: "Sub bara de status găsești cardul \"Configurează-ți magazinul\", cu un contor de forma bifate/total și o bară de progres.",
          pasi: [
            {
              text: "Intră în Panou principal și uită-te la cardul \"Configurează-ți magazinul\".",
              captura: { alt: "Cardul \"Configurează-ți magazinul\" cu bara de progres și cei patru pași, unul bifat și marcat \"Gata\".", raport: 16 / 10 },
            },
            "Pasul \"Adaugă primul produs\": apasă \"Adaugă\" și ajungi în formularul de produs nou, la /dashboard/products/new.",
            "Pasul \"Personalizează magazinul\": apasă \"Personalizează\" și ajungi în /dashboard/editor.",
            "Pasul \"Publică magazinul\": apasă \"Publică\" și ajungi tot în /dashboard/editor.",
            "Pasul \"Primește prima comandă\": apasă \"Distribuie\" și linkul magazinului se copiază.",
          ],
          detalii: [
            { titlu: "Ce scrie la fiecare pas", text: "\"Adaugă primul produs\" are descrierea \"Fără produse, clienții nu au ce cumpăra.\". \"Personalizează magazinul\" are \"Adaugă logo, culori și detaliile magazinului tău.\". \"Publică magazinul\" are \"Fă magazinul vizibil pentru clienții tăi.\". \"Primește prima comandă\" are \"Distribuie link-ul pe WhatsApp și rețele sociale.\"." },
            { titlu: "Când se bifează fiecare pas", text: "Primul pas se bifează când există cel puțin un produs pe magazin, activ sau nu. Al doilea se bifează fie când magazinul are logo încărcat, fie când ai intrat o dată în pagina Editează magazinul. Al treilea se bifează când magazinul este publicat. Al patrulea se bifează când există cel puțin o comandă pe magazin, în orice stare." },
            { titlu: "Butonul \"Publică\" nu publică din listă", text: "La pasul \"Publică magazinul\", butonul te duce în editor. Dacă vrei să publici dintr-un singur clic, folosește \"Publică acum\" din bara de status a Panoului principal." },
            { titlu: "Pasul 2 se ține minte în browserul curent", text: "Bifarea prin vizitarea editorului este salvată local, în browserul de pe care ai intrat. Pe alt calculator sau în alt browser pasul poate apărea din nou nebifat, dacă magazinul nu are logo încărcat." },
            { titlu: "Cum arată un pas terminat", text: "Un pas bifat apare tăiat și are eticheta \"Gata\". Primul pas nebifat este evidențiat și are butonul plin, ca să știi de unde continui." },
            { titlu: "Ce se întâmplă când bifezi tot", text: "Pe un plan plătit, cardul dispare complet din panou după ce toți cei patru pași sunt bifați. Pe plan gratuit sau trial, în locul lui apare cardul cu îndemnul de a alege un plan." },
          ],
          termeni: ["checklist", "lista de activare", "primii pasi", "progres magazin", "gata", "configurare initiala"],
        },
        {
          slug: "cum-distribui-linkul-din-primeste-prima-comanda",
          titlu: "Cum distribui linkul magazinului din pasul \"Primește prima comandă\"",
          rezumat: "Butonul \"Distribuie\" copiază adresa publică a magazinului ca să o poți trimite mai departe.",
          pasi: [
            "Intră în Panou principal, la cardul \"Configurează-ți magazinul\".",
            {
              text: "La pasul \"Primește prima comandă\" apasă \"Distribuie\".",
              captura: { alt: "Pasul \"Primește prima comandă\" cu butonul \"Distribuie\" în dreapta.", raport: 16 / 10 },
            },
            "Linkul public al magazinului se copiază și apare mesajul \"Link-ul magazinului a fost copiat!\".",
            "Lipește linkul unde vrei să îl trimiți, de exemplu într-o conversație pe WhatsApp sau într-o postare.",
          ],
          detalii: [
            { titlu: "Dacă linkul nu se copiază", text: "Apare mesajul \"Nu am putut copia link-ul. Copiază-l manual din bara de sus.\" Se întâmplă când browserul nu dă voie la clipboard. În acest caz ia adresa din bara de status din capul paginii." },
            { titlu: "Butonul doar copiază", text: "\"Distribuie\" nu deschide WhatsApp și nu postează nimic automat nicăieri. Trimiterea mai departe o faci tu." },
            { titlu: "Când dispare butonul", text: "Pasul se bifează în momentul în care magazinul are cel puțin o comandă, în orice stare. După bifare, butonul \"Distribuie\" nu mai apare. Linkul rămâne disponibil în bara de status, la \"Copiază link\"." },
          ],
          termeni: ["distribuie", "share", "whatsapp", "copiaza adresa magazinului", "trimite link clienti"],
        },
        {
          slug: "cum-restrangi-cardul-de-configurare",
          titlu: "Cum restrângi și extinzi cardul \"Configurează-ți magazinul\"",
          rezumat: "Ascunzi lista de pași și păstrezi doar antetul cu progresul.",
          pasi: [
            {
              text: "În Panou principal, la cardul \"Configurează-ți magazinul\", apasă butonul cu săgeată din colțul din dreapta.",
              captura: { alt: "Colțul din dreapta al cardului, cu butonul cu săgeată pentru restrângere.", raport: 16 / 10 },
            },
            "Lista de pași se ascunde, iar antetul cu titlul și progresul rămâne vizibil.",
            "Apasă din nou pe același buton ca să aduci lista înapoi.",
          ],
          detalii: [
            { titlu: "Cum se numește butonul", text: "Butonul nu are text vizibil. Eticheta pentru cititoarele de ecran este \"Restrânge\" când cardul e deschis și \"Extinde\" când e închis." },
            { titlu: "Unde se ține minte alegerea", text: "Starea restrânsă se salvează local, în browserul de pe care lucrezi. Nu se sincronizează între dispozitive, deci pe telefon sau pe alt calculator cardul poate apărea deschis." },
            { titlu: "Licărirea de la reîncărcarea paginii", text: "Cardul își amintește starea restrânsă la reîncărcare. Poate licări o clipă deschis, înainte să se restrângă singur." },
          ],
          termeni: ["restrange", "extinde", "ascunde lista", "sageata card", "colapsare"],
        },
        {
          slug: "cum-alegi-un-plan-din-panoul-principal",
          titlu: "Cum alegi un plan din cardul afișat după configurarea completă",
          rezumat: "După ce bifezi toți pașii, pe plan gratuit sau trial apare un card care te duce la secțiunea de abonament din Setări.",
          pasi: [
            "Bifează toți cei patru pași din \"Configurează-ți magazinul\".",
            {
              text: "Dacă ești pe plan gratuit sau trial, în locul listei apare cardul \"Felicitări, magazinul tău e complet configurat!\".",
              captura: { alt: "Cardul de final, cu titlul de felicitare și butonul \"Alege un plan\".", raport: 16 / 10 },
            },
            "Apasă \"Alege un plan\". Ajungi în Setări, direct la secțiunea de abonament, la /dashboard/settings#abonament.",
            "Alege planul și continuă plata din Setări.",
          ],
          detalii: [
            { titlu: "Ce scrie sub titlu", text: "Dacă planul tău are o dată de expirare, textul este \"Alege un plan ca să rămâi online după data respectivă. Anulezi oricând, prețul rămâne fix pe viață.\". Dacă nu există o dată de expirare, textul este \"Alege un plan ca să deblochezi tot potențialul magazinului. Anulezi oricând, prețul rămâne fix pe viață.\"." },
            { titlu: "Cum arată data", text: "Data afișată este data de expirare a planului tău, scrisă ca zi și lună, de exemplu 3 septembrie." },
            { titlu: "Când nu apare cardul", text: "Pe un plan plătit cardul nu apare deloc. Acolo, după bifarea tuturor pașilor, zona dispare complet din panou." },
            { titlu: "Unde se face plata", text: "Din panou doar ajungi la abonament. Alegerea planului și plata se fac în pagina Setări." },
          ],
          termeni: ["abonament", "upgrade", "plan platit", "trial", "felicitari", "settings abonament"],
        },
        {
          slug: "cum-rezolvi-alerta-stoc-scazut",
          titlu: "Cum vezi și rezolvi alerta \"Stoc scăzut\"",
          rezumat: "Caseta de sub lista de configurare îți arată produsele care sunt pe terminate și te duce la pagina de produse.",
          pasi: [
            {
              text: "Intră în Panou principal. Dacă ai produse pe terminate, sub cardul de configurare apare caseta \"Stoc scăzut\".",
              captura: { alt: "Caseta \"Stoc scăzut\" cu lista de produse și butonul \"Gestionează\" în dreapta.", raport: 16 / 10 },
            },
            "Citește lista: fiecare rând arată numele produsului și cantitatea rămasă, de forma numele produsului urmat de câte bucăți mai ai.",
            "Apasă \"Gestionează\" din dreapta casetei. Ajungi în lista de produse, la /dashboard/products.",
            "Deschide produsul și actualizează stocul.",
          ],
          detalii: [
            { titlu: "Ce produse ajung în listă", text: "Produsul trebuie să fie activ, să aibă urmărirea stocului pornită și să aibă stocul cel mult 5 bucăți. Dacă un produs nu are urmărirea stocului pornită sau este inactiv, nu apare aici, oricât de mic ar fi stocul." },
            { titlu: "Câte produse se afișează", text: "Cel mult 5 produse, cele cu stocul cel mai mic primele. Dacă ai mai multe sub prag, restul le vezi în pagina de produse." },
            { titlu: "Când lipsește caseta", text: "Dacă niciun produs nu este sub prag, caseta nu apare deloc în panou. Nu înseamnă că ceva nu funcționează." },
            { titlu: "Stocul nu se modifică din casetă", text: "Caseta este doar o avertizare. Modificarea cantității se face în pagina produsului, unde intri prin \"Gestionează\"." },
          ],
          nota: "Pragul folosit de panou este de 5 bucăți.",
          termeni: ["stoc", "inventar", "produse pe terminate", "cantitate", "gestioneaza", "alerta stoc"],
        },
        {
          slug: "cum-citesti-cardurile-de-statistici",
          titlu: "Cum citești cardurile de statistici din Panoul principal",
          rezumat: "Cele patru carduri de sub alerte, ce număr arată fiecare și unde te duc.",
          pasi: [
            {
              text: "Cardul \"Comenzi azi\" arată câte comenzi ai azi, iar sub cifră vezi variația față de ziua precedentă, cu textul \"vs. ieri\". Apasă cardul ca să mergi la /dashboard/orders.",
              captura: { alt: "Rândul cu cele patru carduri de statistici, fiecare cu titlu, cifră și legătura \"Vezi detalii\".", raport: 16 / 10 },
            },
            "Cardul \"Vânzări luna aceasta\" arată suma încasată în luna curentă, în lei, cu variația față de \"vs. luna trecută\". Apasă cardul ca să mergi tot la /dashboard/orders.",
            "Cardul \"Produse active\" arată câte produse sunt active. Apasă cardul ca să mergi la /dashboard/products.",
            "Cardul \"În așteptare\" arată câte comenzi sunt în starea \"În așteptare\". Apasă cardul ca să mergi la lista deja filtrată, /dashboard/orders?status=pending.",
            "În colțul din dreapta jos al fiecărui card ai și legătura \"Vezi detalii\".",
          ],
          detalii: [
            { titlu: "Când vezi procentul de variație", text: "Procentul apare doar dacă perioada de comparație a avut o valoare mai mare decât zero: ieri pentru comenzi, luna trecută pentru vânzări. Altfel, în locul procentului scrie \"Actualizat acum\"." },
            { titlu: "Când valoarea este zero", text: "Dacă numărul de pe card este zero, cifra apare estompată și nu se afișează nicio variație, ci tot \"Actualizat acum\"." },
            { titlu: "Ce nu numără \"Comenzi azi\"", text: "Comenzile anulate și cele rambursate nu intră în numărătoarea de azi și nici în cea de ieri, cu care se face comparația." },
            { titlu: "Cardurile fără procent", text: "\"Produse active\" și \"În așteptare\" nu au niciodată procent de variație. Sub cifră scrie mereu \"Actualizat acum\"." },
            { titlu: "Cum se socotește ziua", text: "Ziua de azi și cea de ieri se calculează pe fus orar UTC, nu pe ora locală. Comenzile primite noaptea târziu pot intra în ziua următoare față de ce arată ceasul tău." },
            { titlu: "Ce înseamnă \"Actualizat acum\"", text: "Este un text fix, nu momentul real al ultimei actualizări. Nu îl citi ca pe o oră de sincronizare." },
          ],
          termeni: ["statistici", "vanzari", "comenzi azi", "produse active", "in asteptare", "pending", "procent", "vezi detalii"],
        },
        {
          slug: "cum-citesti-graficul-de-vanzari",
          titlu: "Cum citești graficul \"Vânzări - ultimele 7 zile\"",
          rezumat: "Graficul din stânga, sub statistici, arată încasările și numărul de comenzi pe fiecare din ultimele șapte zile.",
          pasi: [
            "Intră în Panou principal și derulează până sub cardurile de statistici.",
            "În cardul din stânga vezi titlul \"Vânzări - ultimele 7 zile\". Sub titlu apare totalul pe perioadă, de forma 1.250 lei total, iar în dreapta numărul total de comenzi din perioadă.",
            {
              text: "Treci cu mouse-ul peste o coloană. Apare o etichetă cu ziua, de exemplu mie. 19, suma încasată în acea zi și numărul de comenzi din acea zi.",
              captura: { alt: "Graficul pe șapte zile, cu eticheta care apare la trecerea cu mouse-ul peste o coloană.", raport: 16 / 10 },
            },
          ],
          detalii: [
            { titlu: "Când nu ai vânzări", text: "În locul graficului scrie \"Nu există vânzări în ultimele 7 zile\"." },
            { titlu: "Perioada este fixă", text: "Graficul arată mereu ultimele 7 zile, inclusiv ziua curentă. Intervalul nu se poate schimba din panou." },
            { titlu: "Cum se grupează zilele", text: "Zilele sunt grupate pe fus orar UTC, la fel ca la cardurile de statistici. O comandă de la limita zilei poate apărea pe ziua următoare față de ora ta locală." },
            { titlu: "Cum se citește axa verticală", text: "Valorile sunt afișate în mii, cu sufixul k, de exemplu 2k. Zero se afișează ca 0." },
            { titlu: "Etichetele zilelor", text: "Sub grafic zilele sunt scrise scurt, în română: ziua din săptămână prescurtată și numărul zilei." },
          ],
          termeni: ["grafic", "incasari", "ultimele 7 zile", "raport vanzari", "chart", "total lei"],
        },
        {
          slug: "cum-deschizi-o-comanda-din-comenzi-recente",
          titlu: "Cum deschizi o comandă din lista \"Comenzi recente\"",
          rezumat: "Cardul din dreapta graficului îți arată ultimele comenzi și te duce direct în comandă.",
          pasi: [
            "Intră în Panou principal și uită-te în dreapta graficului, la cardul \"Comenzi recente\".",
            {
              text: "Fiecare rând arată numărul comenzii, numele clientului, totalul în lei și o etichetă de stare colorată.",
              captura: { alt: "Cardul \"Comenzi recente\" cu câteva rânduri și etichetele de stare colorate.", raport: 16 / 10 },
            },
            "Apasă pe un rând ca să deschizi comanda respectivă.",
            "Ca să vezi toate comenzile, apasă \"Vezi toate\" din antetul cardului. Ajungi la /dashboard/orders.",
          ],
          detalii: [
            { titlu: "Ce stări poți vedea", text: "Etichetele posibile sunt \"În așteptare\", \"Confirmat\", \"În procesare\", \"Expediat\", \"Livrat\", \"Anulat\" și \"Rambursat\". O stare pe care sistemul nu o recunoaște este afișată ca \"În așteptare\"." },
            { titlu: "Câte comenzi apar", text: "Cel mult 5 comenzi, cele mai recente primele. Restul le vezi în pagina de comenzi." },
            { titlu: "Lista nu este filtrată", text: "Aici apar și comenzile anulate sau rambursate, spre deosebire de cardurile de vânzări, care le lasă afară. Dacă numărul de comenzi de pe card nu se potrivește cu ce vezi în listă, aceasta este explicația." },
            { titlu: "Starea nu se schimbă din card", text: "Din \"Comenzi recente\" doar intri în comandă. Schimbarea stării se face în pagina comenzii." },
            { titlu: "Când nu ai comenzi", text: "În card scrie \"Nu există comenzi încă\"." },
          ],
          termeni: ["comenzi", "ultimele comenzi", "stare comanda", "anulat", "rambursat", "vezi toate"],
        },
        {
          slug: "cum-citesti-anuntul-din-noutati",
          titlu: "Cum citești anunțul din secțiunea \"Noutăți\"",
          rezumat: "Jos în Panoul principal apare ultimul anunț publicat de echipa Edinio.",
          pasi: [
            "Intră în Panou principal și derulează până jos, sub grafic și sub comenzile recente.",
            {
              text: "Dacă există un anunț publicat, vezi titlul de secțiune \"Noutăți\" și anunțul sub el.",
              captura: { alt: "Secțiunea \"Noutăți\" din josul panoului, cu imaginea de copertă și titlul anunțului.", raport: 16 / 10 },
            },
            "Citește anunțul. Dacă are butoane, apasă butonul dorit: linkul se deschide într-o filă nouă.",
          ],
          detalii: [
            { titlu: "Ce poate conține un anunț", text: "O imagine de copertă, eticheta \"Important\", data publicării, titlul, un rezumat și blocuri de conținut: titluri, text, imagini cu legendă, video, butoane și linii despărțitoare." },
            { titlu: "Se afișează un singur anunț", text: "Panoul arată doar cel mai recent anunț publicat. Când echipa publică unul nou, cele anterioare sunt scoase de la publicare și nu mai apar aici." },
            { titlu: "Ce înseamnă eticheta \"Important\"", text: "Apare doar pe anunțurile fixate de administratorii platformei." },
            { titlu: "Anunțul este doar de citit", text: "Nu îl poți edita, ascunde sau marca drept citit din panou." },
            { titlu: "Când secțiunea lipsește", text: "Dacă nu există niciun anunț publicat, secțiunea \"Noutăți\" nu apare deloc în pagină." },
          ],
          termeni: ["noutati", "anunt", "important", "comunicat", "update platforma"],
        },
        {
          slug: "cum-cauti-din-bara-de-sus",
          titlu: "Cum cauți produse din bara de sus a panoului",
          rezumat: "Câmpul de căutare din bara de sus te duce în lista de produse cu termenul aplicat.",
          pasi: [
            {
              text: "Apasă în câmpul de căutare din bara de sus. Textul sugestiv este \"Caută produse, comenzi...\".",
              captura: { alt: "Bara de sus cu câmpul de căutare și textul sugestiv.", raport: 16 / 10 },
            },
            "Scrie termenul căutat.",
            "Apasă Enter.",
            "Ajungi în lista de produse cu termenul aplicat, la /dashboard/products cu parametrul search.",
          ],
          detalii: [
            { titlu: "Căutarea duce mereu la produse", text: "Deși textul sugestiv menționează și comenzile, trimiterea formularului te duce de fiecare dată în pagina de produse, cu termenul aplicat ca filtru. Pentru comenzi, intră în Comenzi și caută acolo." },
            { titlu: "Căutarea goală nu face nimic", text: "Dacă apeși Enter cu câmpul gol sau cu doar spații, nu se întâmplă nimic și rămâi pe pagina curentă." },
            { titlu: "Câmpul se sincronizează cu adresa", text: "Dacă ești deja în lista de produse cu un termen aplicat, câmpul din bara de sus afișează acel termen. Îl poți modifica direct acolo și trimite din nou." },
          ],
          termeni: ["cautare", "search", "filtru produse", "bara de sus", "gaseste produs"],
        },
        {
          slug: "cum-verifici-notificarile-din-clopotel",
          titlu: "Cum verifici notificările din clopoțelul barii de sus",
          rezumat: "Clopoțelul adună comenzile în așteptare și anunțurile platformei, cu filtre și marcare ca citite.",
          pasi: [
            "Apasă butonul cu clopoțel din bara de sus. Eticheta pentru cititoarele de ecran este \"Notificări\", iar pe buton apare numărul de necitite.",
            {
              text: "În panoul deschis vezi titlul \"Notificări\" și, dacă ai necitite, eticheta cu numărul de notificări noi.",
              captura: { alt: "Panoul de notificări deschis, cu filtrele și o notificare de comandă nouă.", raport: 16 / 10 },
            },
            "Filtrează cu butoanele \"Toate\", \"Comenzi\" și \"Anunțuri\".",
            "Apasă pe o notificare de comandă, de forma \"Comandă nouă de la numele clientului\", ca să deschizi comanda.",
            "Apasă \"Marchează ca citite\" ca să ștergi toate punctele de necitit.",
            "Jos în panou, apasă \"Vezi toate comenzile\" ca să mergi la /dashboard/orders.",
          ],
          detalii: [
            { titlu: "Ce arată numărul de pe clopoțel", text: "Numărul total de notificări necitite. Când trece de 9, pe buton scrie 9+." },
            { titlu: "De unde vin notificările de comandă", text: "Doar din comenzile aflate în starea în așteptare. O comandă confirmată sau livrată nu mai generează o notificare aici. Fiecare rând arată clientul, suma și cât timp a trecut." },
            { titlu: "Cât se încarcă", text: "Se aduc cel mult 20 de comenzi în așteptare și cel mult 20 de notificări de platformă." },
            { titlu: "Cum se citește vechimea", text: "Scurt: acum, apoi în minute cu m, în ore cu h și în zile cu z." },
            { titlu: "Anunțurile nu se deschid", text: "Un anunț din listă se marchează citit când apeși pe el, dar nu duce nicăieri. Conținutul lui îl citești în secțiunea \"Noutăți\" din josul Panoului principal." },
            { titlu: "Butoane care apar doar în anumite cazuri", text: "\"Marchează ca citite\" apare doar când ai cel puțin o notificare necitită. Butoanele de filtrare apar doar când ai cel puțin o notificare. \"Vezi toate comenzile\" apare doar când există comenzi în listă." },
            { titlu: "Când nu ai nimic", text: "În panou scrie \"Nicio notificare\" și, sub, \"Comenzile și anunțurile vor apărea aici\"." },
          ],
          termeni: ["notificari", "clopotel", "comanda noua", "necitite", "marcheaza ca citite", "9+"],
        },
        {
          slug: "cum-deschizi-meniul-de-cont-si-iesi-din-cont",
          titlu: "Cum deschizi meniul de cont și cum ieși din cont",
          rezumat: "Din dreapta sus ajungi la Setări cont și te deconectezi, iar pe telefon butonul de ieșire este doar o iconiță.",
          pasi: [
            "Pe desktop, apasă pe inițialele sau pe numele tău din dreapta sus. Dacă nu ai numele completat, scrie \"Contul meu\".",
            {
              text: "În meniu vezi numele tău și eticheta planului curent.",
              captura: { alt: "Meniul de cont deschis, cu numele, eticheta de plan, \"Setări cont\" și \"Deconectează-te\".", raport: 16 / 10 },
            },
            "Apasă \"Setări cont\" ca să mergi la /dashboard/settings.",
            "Apasă \"Deconectează-te\" ca să ieși din cont.",
            "Pe telefon, deschide meniul cu butonul de meniu și, jos, lângă numele tău, apasă iconița de ieșire din dreapta.",
          ],
          detalii: [
            { titlu: "Ce etichete de plan poți vedea", text: "\"Gratuit (15 zile)\" pentru conturile gratuite și pentru perioada de testare, apoi \"Basic\", \"Premium\", \"Ultra\" și \"Domeniu\". Dacă pe cont este un plan pe care sistemul nu îl recunoaște, se afișează denumirea lui ca atare." },
            { titlu: "Aici doar vezi planul", text: "Numele și eticheta de plan sunt informative. Schimbarea planului se face în Setări, la secțiunea de abonament." },
            { titlu: "Ieșirea din cont pe telefon", text: "În meniul mobil nu există un rând scris \"Deconectează-te\". Este un buton cu iconiță de ieșire, în dreapta numelui tău. Eticheta pentru cititoarele de ecran este \"Deconectează-te\"." },
          ],
          termeni: ["logout", "deconectare", "iesire din cont", "contul meu", "setari cont", "plan curent"],
        },
        {
          slug: "cum-reactionezi-la-bannerele-de-abonament",
          titlu: "Cum reacționezi la bannerele de abonament din capul panoului",
          rezumat: "Cele patru benzi colorate care pot apărea deasupra panoului și ce buton apeși la fiecare.",
          pasi: [
            {
              text: "Uită-te la banda colorată din capul paginii, deasupra conținutului panoului.",
              captura: { alt: "Banda colorată din capul panoului, cu mesajul de abonament și butonul de acțiune în dreapta.", raport: 16 / 10 },
            },
            "Dacă ești în perioada de testare, bannerul îți spune câte zile mai ai. Apasă \"Alege un plan\" ca să mergi la /dashboard/settings#abonament.",
            "Dacă testarea a expirat, scrie \"Perioada de testare a expirat. Magazinul tău nu mai este vizibil clienților.\". Apasă \"Alege un plan acum\".",
            "Dacă ai abonament plătit și plata a eșuat, scrie \"Plata abonamentului a eșuat și abonamentul a expirat. Reia plata ca să îți păstrezi magazinul activ.\". Apasă \"Reia plata\", care te duce la factura restantă.",
            "Dacă ești în perioada de grație, bannerul îți spune în câte zile va fi suspendat magazinul. Apasă \"Actualizează plata\". Dacă magazinul este deja suspendat, butonul se numește \"Reactivează acum\". Ambele duc la /dashboard/settings.",
          ],
          detalii: [
            { titlu: "Textul exact al bannerului de testare", text: "Când mai ai cel mult 3 zile, mesajul devine urgent, cu altă culoare, și scrie \"Doar 1 zi rămasă din testarea gratuită!\" sau \"Doar 5 zile rămase din testarea gratuită!\", după caz. Peste 3 zile, mesajul este de forma \"7 zile rămase din testarea gratuită\", fără semnul de exclamare." },
            { titlu: "Când nu vezi bannerul de testare", text: "Nu se afișează dacă mai ai peste 15 zile din perioada de testare. Apare doar pe planul gratuit și doar dacă există o dată de expirare setată pe cont." },
            { titlu: "Textul bannerului de grație", text: "\"Plata abonamentului a eșuat. Magazinul tău va fi suspendat în câteva zile dacă nu actualizezi metoda de plată.\", cu numărul de zile în text. Când mai este o singură zi, scrie că magazinul va fi suspendat mâine. Dacă magazinul este deja suspendat, mesajul devine \"Magazinul tău este suspendat și nu mai este vizibil clienților. Actualizează metoda de plată pentru a-l reactiva.\"." },
            { titlu: "Când apare fiecare banner", text: "Bannerul de plată eșuată apare doar pe un plan plătit, fără magazin suspendat, și doar când pe cont există o marcă de plată eșuată. Bannerul de grație apare doar când magazinul are o dată de suspendare setată." },
            { titlu: "Dacă \"Reia plata\" nu deschide nimic", text: "Cât timp se încarcă, pe buton scrie \"Se deschide...\". Dacă nu reușește, apare \"Eroare la deschiderea portalului de plată.\" sau, la probleme de rețea, \"Eroare de rețea. Încearcă din nou.\" Încearcă din nou după câteva momente sau intră în Setări, la secțiunea de abonament." },
            { titlu: "Bannerele nu se pot închide", text: "Nu există buton de închidere. Banda dispare când situația care a generat-o este rezolvată." },
          ],
          termeni: ["banner", "trial expirat", "plata esuata", "perioada de gratie", "suspendat", "reia plata", "reactiveaza"],
        },
        {
          slug: "cum-navighezi-din-meniul-lateral",
          titlu: "Cum navighezi din meniul lateral al panoului",
          rezumat: "Ce secțiuni are meniul lateral, cum apar subpaginile și ce diferă pe telefon.",
          pasi: [
            "Pe desktop, meniul lateral conține, în ordine: \"Panou principal\", \"Editează magazinul\", \"Pagini\", \"Integrări\", \"Produse\", \"Comenzi\", \"Clienți\", \"Coșuri abandonate\", \"Discounturi\", \"Oferte\", \"Statistici\".",
            "Sub meniul principal găsești \"Suport\" și \"Setări\". Conturile de administrator au în plus \"Panou Admin\".",
            {
              text: "Intră într-o secțiune ca să îi vezi subpaginile: \"Editează magazinul\" are \"Design magazin\", \"Design secțiuni\" și \"Bibliotecă Media\", \"Pagini\" are \"Toate paginile\", \"Formulare\" și \"Mesaje\", \"Produse\" are \"Toate produsele\", \"Categorii\" și \"Pachete\", \"Comenzi\" are \"Toate comenzile\" și \"Retururi\".",
              captura: { alt: "Meniul lateral cu o secțiune activă și subpaginile ei deschise dedesubt.", raport: 16 / 10 },
            },
            "Pe telefon, aceleași secțiuni sunt în meniul care se deschide cu butonul de meniu din bara de sus. În bara de jos ai \"Acasă\", \"Editor\", \"Produse\" și \"Comenzi\".",
          ],
          detalii: [
            { titlu: "Etichetele de lângă secțiuni", text: "\"Integrări\" este marcat \"Nou\", iar \"Oferte\" și subpagina \"Design secțiuni\" sunt marcate \"Beta\"." },
            { titlu: "Submeniurile apar doar când ești în secțiune", text: "Subpaginile se văd sub secțiunea părinte doar cât timp ești în ea. Dacă pleci în altă secțiune, lista se închide." },
            { titlu: "Ce înseamnă cifra de pe \"Comenzi\"", text: "Bulina verde de pe \"Comenzi\" din meniul lateral arată retururile necitite, nu comenzile noi. Comenzile noi le vezi în clopoțelul din bara de sus." },
            { titlu: "\"SMS Marketing\" și \"Panou Admin\"", text: "\"SMS Marketing\" apare în meniu doar dacă integrarea SMS este activată din setările magazinului. \"Panou Admin\" apare doar pentru conturile cu rol de administrator." },
            { titlu: "Caseta de plan din josul meniului", text: "Pe plan gratuit, jos în meniu apare caseta \"Plan Gratuit\", cu textul \"Upgrade la Pro pentru funcții avansate și suport prioritar.\" și butonul \"Upgrade acum\", care duce la secțiunea de abonament din Setări." },
            { titlu: "Ce lipsește din meniul de pe telefon", text: "În meniul care se deschide din bara de sus nu apar \"Oferte\" și subpagina \"Design secțiuni\". Nici \"Comenzi\" nu are acolo subpagini: este un singur element, fără \"Toate comenzile\" și \"Retururi\"." },
            { titlu: "Bara de jos de pe telefon", text: "Conține \"Acasă\", \"Editor\", \"Produse\" și \"Comenzi\", plus \"Admin\" pentru conturile de administrator. Bara dispare complet cât timp ești în formularul de produs nou sau de editare a unui produs." },
          ],
          termeni: ["meniu", "navigare", "sidebar", "submeniu", "bara de jos", "panou admin", "sms marketing", "retururi"],
        },
      ],
    },
  ],
};
