import { Settings } from "lucide-react";
import type { CategorieAjutor } from "../ajutor-tipuri";

/**
 * Categoria „Setări” din centrul de ajutor.
 *
 * ⚠ TEXTELE SUNT CIORNĂ, scrise dintr-un audit al codului panoului, nu din cap.
 * Vezi `../ajutor.ts` pentru cum s-a făcut auditul și ce reguli de scriere se
 * aplică. Clientul le corectează.
 */
export const SETARI: CategorieAjutor = {
  slug: "setari",
  titlu: "Setări",
  descriere: "Datele magazinului, domeniu, SEO, email, notificări și politici.",
  icon: Settings,
  grupuri: [
    {
      titlu: "Magazin, domeniu și SEO",
      ghiduri: [
        {
          slug: "cum-intri-in-setari-si-te-muti-intre-sectiuni",
          titlu: "Cum intri în Setări și te muți între secțiuni",
          rezumat: "Setările se deschid din meniul lateral și grupează paisprezece secțiuni, de la General până la Securitate.",
          pasi: [
            "În meniul lateral, jos de tot, apasă \"Setări\".",
            "Pe ecran mic, deschide meniul din bara de sus și apasă \"Setări\". Din meniul de utilizator, dreapta sus, ai și \"Setări cont\".",
            {
              text: "În pagină, alege secțiunea din coloana din stânga, sub titlul \"Setări\".",
              captura: { alt: "Pagina Setări cu coloana de secțiuni din stânga și secțiunea General deschisă în dreapta.", raport: 16 / 10 },
            },
            "Pe telefon și tabletă, alege secțiunea din banda orizontală lipită sub bara de sus.",
          ],
          detalii: [
            { titlu: "Ce secțiuni există", text: "General, Tip magazin, Plan, Facturare, Livrare, Taxe, Metode de plată, Domeniu, SEO, Email, Notificări, Politici, Banner Cookies, Securitate. Secțiunea aleasă se deschide în dreapta, fără să pleci din pagină." },
            { titlu: "Pe ecrane mici", text: "Coloana de secțiuni din stânga se vede doar pe ecrane mari. Sub acest prag, aceleași denumiri apar într-o bandă orizontală derulabilă." },
            { titlu: "Deschizi o secțiune direct din adresă", text: "Adresa /dashboard/settings acceptă ancore. #seo deschide SEO, #domeniu deschide Domeniu, #securitate deschide Securitate. Pentru Plan merg atât #abonament, cât și #plan, iar #facturare deschide Facturare." },
            { titlu: "Când te întorci de la o plată", text: "Dacă adresa conține ?plan_success=1, se deschide automat secțiunea Plan. Dacă are ?domain_success=1, se deschide automat Domeniu." },
          ],
          nota: "Setările cer cont autentificat. Fără sesiune activă, pagina te trimite la autentificare.",
          termeni: ["panou de administrare", "navigare", "meniu lateral", "dashboard settings", "unde sunt setările"],
        },
        {
          slug: "cum-schimbi-numele-contului",
          titlu: "Cum schimbi numele contului",
          rezumat: "Numele tău de utilizator se editează în Setări > General, în cardul \"Contul tău\".",
          pasi: [
            "Intră în Setări > General.",
            {
              text: "În cardul \"Contul tău\", scrie numele în câmpul \"Numele complet\".",
              captura: { alt: "Cardul \"Contul tău\" cu câmpul \"Numele complet\" și emailul blocat dedesubt.", raport: 16 / 10 },
            },
            "Apasă \"Salvează contul\". Cât timp se salvează, butonul scrie \"Se salvează...\".",
          ],
          detalii: [
            { titlu: "Adresa de email nu se editează de aici", text: "Câmpul \"Adresa de email\" arată emailul contului, dar este blocat. Sub el scrie \"Contactați suportul pentru schimbarea adresei de email.\", deci schimbarea se face prin suport." },
            { titlu: "Ce salvează butonul", text: "\"Salvează contul\" salvează doar numele complet. Datele firmei din cardul de dedesubt au alt buton, \"Salvează setările generale\"." },
            { titlu: "Mesajele pe care le vezi", text: "Dacă a mers, apare \"Profilul a fost actualizat.\". Dacă nu, apare \"Nu am putut salva modificările.\" și poți încerca din nou." },
          ],
          nota: "\"Numele complet\" este numele tău de utilizator, nu numele afișat al magazinului.",
          termeni: ["nume utilizator", "profil", "cont", "email cont"],
        },
        {
          slug: "cum-completezi-datele-legale-ale-magazinului",
          titlu: "Cum completezi datele legale ale magazinului",
          rezumat: "Denumirea firmei, CUI, Registrul Comerțului și datele de contact se completează în Setări > General, în cardul \"Datele magazinului\".",
          intro: "Aceste date apar pe documente, pe facturi și în footer-ul magazinului.",
          pasi: [
            "Intră în Setări > General.",
            {
              text: "Completează câmpurile din cardul \"Datele magazinului\".",
              captura: { alt: "Cardul \"Datele magazinului\" cu toate câmpurile completate.", raport: 16 / 10 },
            },
            "Coboară la baza secțiunii și apasă \"Salvează setările generale\". Cât timp se salvează, butonul scrie \"Se salvează...\".",
          ],
          detalii: [
            { titlu: "Ce se cere în fiecare câmp", text: "Denumirea firmei, marcată cu *, este folosită pentru datele legale și pentru facturare (exemplu: SC Firma Mea SRL). CUI / CIF apare pe facturile emise către tine (exemplu: RO12345678). Nr. Registrul Comerțului se afișează public în footer-ul magazinului și este cerut de procesatorii de plăți, de exemplu Netopia (exemplu: J40/1234/2017). Adresa, Oraș, Județ, Telefon și Email contact completează restul datelor firmei." },
            { titlu: "Ce este obligatoriu", text: "Doar \"Denumirea firmei\" este obligatorie. Dacă o lași goală, la salvare apare \"Denumirea firmei este obligatorie.\" și restul nu se salvează." },
            { titlu: "Un buton pentru două carduri", text: "Câmpurile nu au buton propriu. \"Salvează setările generale\" salvează în același timp datele magazinului și formatul numărului de comandă, deci verifică ambele carduri înainte să apeși." },
            { titlu: "Numele afișat în magazin e altceva", text: "Sub câmpul de denumire scrie: \"Folosită pentru date legale și facturare. Numele afișat în magazin se editează din Editează magazinul.\"" },
            { titlu: "Dacă salvarea nu reușește", text: "Pe lângă mesajul despre denumirea firmei, serverul poate răspunde \"Eroare la salvarea datelor magazinului.\", \"Eroare la salvarea setărilor.\" sau \"Magazin negăsit\". Reia salvarea, iar dacă mesajul se repetă, scrie la suport. Când totul merge, apare \"Setările au fost salvate.\"" },
          ],
          nota: "Dacă nu ai un magazin asociat contului, butonul \"Salvează setările generale\" este blocat.",
          termeni: ["date firmă", "CUI", "registrul comerțului", "facturare", "footer magazin", "date legale"],
        },
        {
          slug: "cum-completezi-automat-datele-firmei-din-anaf",
          titlu: "Cum completezi automat datele firmei din ANAF",
          rezumat: "Scrii CUI-ul în Setări > General și butonul \"Completează automat\" aduce datele firmei din ANAF.",
          pasi: [
            "Intră în Setări > General, la cardul \"Datele magazinului\".",
            "Scrie codul fiscal în câmpul \"CUI / CIF\". Prefixul RO este acceptat.",
            {
              text: "Apasă \"Completează automat\". Cât durează interogarea, butonul scrie \"Se caută...\".",
              captura: { alt: "Câmpul \"CUI / CIF\" cu butonul \"Completează automat\" alături.", raport: 16 / 10 },
            },
            "Verifică datele aduse și apasă \"Salvează setările generale\".",
          ],
          detalii: [
            { titlu: "Ce completează și ce nu", text: "Se completează denumirea firmei, județul, orașul, adresa și Nr. Registrul Comerțului. Telefonul și emailul de contact rămân pe seama ta." },
            { titlu: "Datele nu se salvează singure", text: "După ce câmpurile se umplu, apare \"Date completate automat din ANAF.\", dar modificarea rămâne nesalvată până apeși \"Salvează setările generale\"." },
            { titlu: "Butonul este blocat", text: "Cât timp câmpul \"CUI / CIF\" este gol, butonul nu poate fi apăsat. Dacă totuși pornești căutarea fără cod, apare \"Introdu CUI-ul mai întâi.\"" },
            { titlu: "Dacă ANAF nu returnează firma", text: "Vezi \"CUI negăsit în ANAF.\", iar de la server pot veni \"CUI negăsit în baza de date ANAF.\" sau \"Date incomplete în ANAF pentru acest CUI.\". Verifică cifrele codului fiscal și încearcă din nou. Dacă tot nu apar, completează manual câmpurile." },
            { titlu: "Dacă serviciul nu răspunde", text: "Mesajele posibile sunt \"Serviciul ANAF nu răspunde. Încearcă din nou.\", \"Serviciul ANAF nu răspunde (timeout).\" și \"Eroare la interogarea ANAF.\". Datele vin de la ANAF, care este un serviciu extern. Edinio doar întreabă acolo, așa că atunci când ANAF e picat singura variantă este să reiei mai târziu sau să scrii datele de mână." },
          ],
          termeni: ["cod fiscal", "preluare date firmă", "lookup ANAF", "completare automată"],
        },
        {
          slug: "cum-alegi-formatul-numarului-de-comanda",
          titlu: "Cum alegi formatul numărului de comandă",
          rezumat: "În Setări > General alegi între numerotare secvențială și cod aleatoriu pentru comenzi.",
          pasi: [
            "Intră în Setări > General și coboară la cardul \"Formatul numărului de comandă\".",
            {
              text: "Bifează \"Secvențial\" sau \"Random\".",
              captura: { alt: "Cardul \"Formatul numărului de comandă\" cu cele două variante și exemplele lor.", raport: 16 / 10 },
            },
            "Apasă \"Salvează setările generale\".",
          ],
          detalii: [
            { titlu: "Secvențial", text: "Comenzile primesc numere în ordine crescătoare. Exemplele afișate în card sunt #0001, #0002, #0003." },
            { titlu: "Random", text: "Comenzile primesc un cod unic generat aleatoriu. Exemplele afișate sunt X8SAD-213F, A2KMP-991C, Z7TRQ-445B." },
            { titlu: "Se salvează împreună cu datele firmei", text: "Cardul nu are buton propriu. \"Salvează setările generale\" trimite și formatul comenzii, și câmpurile din \"Datele magazinului\"." },
          ],
          nota: "Sunt doar aceste două variante și poate fi activă o singură dată.",
          termeni: ["numerotare comenzi", "cod comandă", "secvențial", "random"],
        },
        {
          slug: "cum-activezi-one-product-store",
          titlu: "Cum transformi magazinul în One Product Store",
          rezumat: "Din Setări > Tip magazin, magazinul poate afișa un singur produs, iar pagina principală devine landing page-ul acelui produs.",
          pasi: [
            "Intră în Setări > Tip magazin.",
            "Pornește comutatorul de lângă \"Afișează un singur produs\".",
            {
              text: "Din lista \"Produsul principal *\" alege produsul.",
              captura: { alt: "Cardul One Product Store cu comutatorul pornit și lista \"Produsul principal\" deschisă.", raport: 16 / 10 },
            },
            "Apasă \"Salvează\". Cât timp se salvează, butonul scrie \"Se salvează...\".",
          ],
          detalii: [
            { titlu: "Ce se schimbă în magazin", text: "În antetul cardului scrie: \"Transformă magazinul într-o pagină dedicată unui singur produs. Pagina principală devine landing page-ul produsului ales, iar catalogul, categoriile și căutarea sunt ascunse.\" Lângă comutator scrie \"Afișează un singur produs\", iar dedesubt \"Când e activ, vizitatorii ajung direct pe produsul principal.\"" },
            { titlu: "Lista de produse apare după comutator", text: "Câmpul \"Produsul principal *\" se vede numai după ce pornești comutatorul. Prima opțiune din listă este \"Alege un produs...\", apoi urmează produsele active ale magazinului, cu cele evidențiate primele." },
            { titlu: "Dacă nu ai produse active", text: "În locul listei apare: \"Nu ai încă niciun produs activ. Adaugă un produs din Produse ca să poți activa acest mod.\" Până când marchezi un produs ca activ, modul nu poate fi pornit." },
            { titlu: "Dacă salvezi fără produs ales", text: "Salvarea este refuzată cu mesajul \"Alege produsul principal înainte de a activa modul One Product Store.\"" },
            { titlu: "Dacă produsul ales anterior a fost dezactivat", text: "Apare avertismentul \"Produsul selectat anterior nu mai este activ. Alege altul din listă.\" și trebuie să selectezi alt produs din listă." },
            { titlu: "Unde editezi conținutul paginii", text: "În card scrie: \"Conținutul paginii (descriere, beneficii, FAQ, variante) se editează din Produse, la produsul ales. Comanda se face direct, fără coș.\"" },
            { titlu: "Cum revii la catalog", text: "Oprești comutatorul și apeși \"Salvează\". Mesajul de confirmare este \"Magazinul afișează catalogul cu toate produsele.\", iar la activare este \"Magazinul afișează acum un singur produs.\"" },
          ],
          nota: "Se poate alege un singur produs principal. Fără un magazin asociat contului, comutatorul și butonul sunt blocate.",
          termeni: ["landing page", "un singur produs", "tip magazin", "produs principal", "fără coș"],
        },
        {
          slug: "cum-cauti-un-domeniu-liber",
          titlu: "Cum cauți un domeniu și vezi dacă e liber",
          rezumat: "În Setări > Domeniu scrii numele dorit și vezi dacă este disponibil pe .ro și pe .com.",
          pasi: [
            "Intră în Setări > Domeniu.",
            "Rămâi pe tabul \"Cumpără domeniu\", care este activ implicit.",
            "Scrie numele dorit în câmpul de căutare, cel cu lupa și textul \"Caută un domeniu (ex: magazinul-meu)\".",
            {
              text: "Așteaptă verificarea și citește starea afișată sub fiecare extensie.",
              captura: { alt: "Rezultatele căutării, cu .ro marcat Disponibil și .com marcat Indisponibil.", raport: 16 / 10 },
            },
          ],
          detalii: [
            { titlu: "Ce se poate scrie în câmp", text: "Minim 2 caractere, doar litere, cifre și cratimă. Altfel apare \"Minim 2 caractere (litere, cifre, cratimă).\" Dacă scrii și extensia, de exemplu suplio.ro, extensia este scoasă și se caută eticheta suplio." },
            { titlu: "Verificarea pornește singură", text: "Nu există buton de căutare. Verificarea începe la scurt timp după ce te oprești din tastat." },
            { titlu: "Extensiile oferite", text: "Se oferă două extensii: .ro la 60 lei/an și .com la 99 lei/an. Prețurile sunt scrise fix în aplicație." },
            { titlu: "Stările pe care le poți vedea", text: "\"Se verifică...\" cât durează interogarea, \"Disponibil\" dacă numele e liber, \"Indisponibil\" dacă e luat, iar \"Verifică disponibilitatea\" atunci când răspunsul nu este concludent. Pentru un domeniu indisponibil rândul se estompează și butonul \"Comandă\" nu mai apare." },
          ],
          nota: "Fără un magazin activ, câmpul de căutare este blocat și sus apare \"Nu ai un magazin activ. Finalizează onboarding-ul mai întâi.\"",
          termeni: ["disponibilitate domeniu", "verificare domeniu", ".ro", ".com", "preț domeniu"],
        },
        {
          slug: "cum-comanzi-un-domeniu-prin-edinio",
          titlu: "Cum comanzi un domeniu prin Edinio",
          rezumat: "După ce găsești un domeniu liber, apeși \"Comandă\", completezi datele titularului și plătești cu cardul prin Stripe.",
          pasi: [
            "În Setări > Domeniu, caută numele dorit și apasă \"Comandă\" pe extensia liberă.",
            "Alege \"Perioada de înregistrare\": 1 an, 2 ani sau 3 ani. Sub fiecare variantă scrie prețul total.",
            "La \"Date titular\" alege \"Persoană fizică\" sau \"Persoană juridică\".",
            {
              text: "Completează câmpurile marcate cu *.",
              captura: { alt: "Fereastra de comandă cu perioada aleasă și câmpurile de titular completate.", raport: 16 / 10 },
            },
            "Verifică \"Total\" din josul ferestrei și apasă butonul de plată. Cât se pregătește plata, scrie \"Redirectare la plată...\".",
            "Finalizează plata cu cardul, în pagina Stripe.",
          ],
          detalii: [
            { titlu: "Ce completezi la persoană fizică", text: "Nume complet și CNP. CNP-ul trebuie să aibă exact 13 cifre, câmpul acceptă doar cifre și taie la 13. Dacă nu are 13 cifre, apare \"CNP invalid: trebuie să aibă 13 cifre.\"" },
            { titlu: "Ce completezi la persoană juridică", text: "CUI și Denumire firmă. Lângă CUI ai butonul \"Completează automat\", care preia datele firmei din ANAF. În fereastră scrie: \"Introdu CUI-ul și apasă Completează automat pentru a prelua datele firmei din ANAF.\"" },
            { titlu: "Câmpurile comune", text: "Email, Telefon (exemplu: 07XXXXXXXX), Adresă (exemplu: Strada, nr.), Oraș și Județ sunt obligatorii. Codul poștal este marcat opțional. Țara este fixată pe România și nu se poate schimba." },
            { titlu: "Dacă lipsesc date", text: "Apare \"Completează toate câmpurile marcate cu *.\" sau un mesaj punctual: \"Completează numele complet.\", \"Completează CUI-ul firmei.\", \"Completează denumirea firmei (sau apasă Completează automat).\"" },
            { titlu: "Dacă plata nu pornește", text: "Pot apărea \"Nu am putut iniția plata.\" sau \"Eroare de rețea. Încearcă din nou.\". Reia comanda. Plata se procesează prin Stripe, deci pașii de card se fac în pagina lor." },
            { titlu: "Ce urmează după plată", text: "În fereastră scrie: \"După finalizarea plății, domeniul va fi înregistrat și conectat automat la magazinul tău în maximum 24 de ore. Plata se procesează securizat prin Stripe.\" La întoarcerea în Setări apare un mesaj că plata a fost procesată și că domeniul va fi activat în maximum 24 de ore." },
          ],
          nota: "Perioada maximă oferită este de 3 ani. Butonul \"Anulează\" închide fereastra fără să plaseze comanda.",
          termeni: ["cumpărare domeniu", "plată card", "Stripe", "titular domeniu", "CNP", "perioadă înregistrare"],
        },
        {
          slug: "cum-urmaresti-comenzile-si-domeniile-tale",
          titlu: "Cum urmărești comenzile de domenii și domeniile tale",
          rezumat: "Sub căutarea din Setări > Domeniu apar comenzile în curs, domeniile magazinului și istoricul comenzilor.",
          pasi: [
            "Intră în Setări > Domeniu.",
            "Rămâi pe tabul \"Cumpără domeniu\".",
            {
              text: "Citește cardurile de sub căutare: \"Comenzi în curs\", \"Domeniile tale\", \"Istoric comenzi domenii\".",
              captura: { alt: "Cardurile \"Comenzi în curs\" și \"Domeniile tale\" din tabul Cumpără domeniu.", raport: 16 / 10 },
            },
          ],
          detalii: [
            { titlu: "Ce intră în \"Comenzi în curs\"", text: "Doar comenzile cu starea \"În așteptare\" și \"Se procesează\". Sub listă scrie: \"Domeniul va fi activat în maximum 24 de ore de la plasarea comenzii.\"" },
            { titlu: "Ce intră în \"Istoric comenzi domenii\"", text: "Restul stărilor: \"Finalizată\", \"Anulată\", \"Rambursată\"." },
            { titlu: "Ce arată \"Domeniile tale\"", text: "Lista conține domeniile înregistrate pe magazinul tău. Data de expirare apare ca \"Expiră: ...\" doar când există o dată salvată. Eticheta \"Activ\" apare doar pentru domeniile cu starea activă. Pentru orice altă stare se afișează starea așa cum e salvată." },
            { titlu: "Dacă lista e goală", text: "Mesajul \"Nu ai niciun domeniu\" și \"Introdu numele domeniului dorit mai sus pentru a plasa o comandă.\" apare când nu ai domenii, nu ai comenzi în curs și nu ai scris încă un nume valid în câmpul de căutare. Dacă ai doar comenzi vechi, poți vedea în același timp și istoricul, și acest mesaj." },
          ],
          nota: "Din această listă nu poți reînnoi, transfera sau anula un domeniu. Nu există butoane pentru asta.",
          termeni: ["stare comandă domeniu", "expirare domeniu", "istoric comenzi", "domenii înregistrate"],
        },
        {
          slug: "cum-conectezi-un-domeniu-de-la-alt-registrar",
          titlu: "Cum conectezi un domeniu cumpărat de la alt registrar",
          rezumat: "Dacă ai deja un domeniu în altă parte, îl adaugi din tabul \"Conectează domeniu\" și apoi îi setezi DNS-ul.",
          pasi: [
            "Intră în Setări > Domeniu și apasă tabul \"Conectează domeniu\".",
            {
              text: "Scrie domeniul în câmpul cu exemplul \"ex: magazinul-tău.ro\".",
              captura: { alt: "Tabul \"Conectează domeniu\" cu câmpul de domeniu completat.", raport: 16 / 10 },
            },
            "Apasă \"Salvează\".",
            "Urmează instrucțiunile din cardul \"Configurează domeniul\", care apare după conectare.",
          ],
          detalii: [
            { titlu: "Ce spune secțiunea", text: "\"Ai deja un domeniu cumpărat de la alt registrar? Introdu-l mai jos, apoi conectează-l fie prin înregistrări DNS, fie modificând direct nameserverele la registrarul tău.\"" },
            { titlu: "Cum se scrie domeniul", text: "Un prefix www. tastat este scos automat, deci se păstrează forma fără www." },
            { titlu: "Un singur domeniu conectat", text: "Magazinul reține un singur domeniu propriu. Dacă mai conectezi unul, cel vechi este scos." },
            { titlu: "Mesajele pe care le vezi", text: "La reușită: \"Domeniu conectat cu succes. Configurează DNS-ul conform instrucțiunilor.\" Dacă nu merge: \"Nu am putut conecta domeniul.\" sau \"Eroare de rețea. Încearcă din nou.\" Verifică forma domeniului și reia salvarea." },
          ],
          nota: "Domeniul trebuie să fie deja cumpărat la registrarul tău. Edinio îl conectează la magazin, dar contul de la registrar rămâne al tău. Fără un magazin activ, câmpul și butonul sunt blocate.",
          termeni: ["domeniu extern", "registrar", "conectare domeniu propriu", "www"],
        },
        {
          slug: "cum-configurezi-dns-ul-domeniului-conectat",
          titlu: "Cum configurezi DNS-ul domeniului conectat",
          rezumat: "După conectare, alegi între schimbarea nameserverelor și adăugarea a două înregistrări DNS la registrarul tău.",
          pasi: [
            "În Setări > Domeniu > \"Conectează domeniu\", mergi la cardul \"Configurează domeniul\".",
            {
              text: "Alege metoda: \"Nameservere\", marcată Recomandat, sau \"Înregistrări DNS\".",
              captura: { alt: "Cardul \"Configurează domeniul\" cu cele două metode și valorile de copiat.", raport: 16 / 10 },
            },
            "Copiază valorile cu butonul de copiere de lângă fiecare rând.",
            "Aplică-le la registrarul unde ai cumpărat domeniul.",
            "Verifică propagarea prin linkul DNSChecker din josul cardului.",
          ],
          detalii: [
            { titlu: "Metoda cu nameservere", text: "Înlocuiești nameserverele domeniului la registrar cu ns1.vercel-dns.com și ns2.vercel-dns.com. În card apare avertismentul: \"Atenție: schimbarea nameserverelor mută întregul DNS al domeniului. Dacă folosești email pe acest domeniu, alege în schimb metoda „Înregistrări DNS”, care păstrează setările existente.\"" },
            { titlu: "Metoda cu înregistrări DNS", text: "Păstrezi nameserverele actuale și adaugi două înregistrări în panoul DNS al registrarului: tip A, nume @, valoare 216.150.1.1, și tip CNAME, nume www, valoare cname.vercel-dns.com. În card scrie: \"Păstrează nameserverele actuale și adaugă doar aceste două înregistrări în panoul DNS al registrarului.\"" },
            { titlu: "Butoanele de copiere", text: "Lângă fiecare nameserver și fiecare înregistrare este un buton doar cu pictograma de copiere. După apăsare apare o notificare că textul a fost copiat." },
            { titlu: "Cât durează", text: "În card scrie: \"Propagarea poate dura până la 48 de ore. Verifică statusul pe DNSChecker.\" Până atunci, domeniul poate răspunde diferit de la o rețea la alta." },
          ],
          nota: "Cardul apare doar dacă ai deja un domeniu conectat. Modificările se fac în panoul registrarului tău, nu din Edinio, iar de aici nu se pot configura alte înregistrări în afara acestor două.",
          termeni: ["nameservere", "înregistrări A", "CNAME", "propagare", "DNSChecker", "vercel-dns"],
        },
        {
          slug: "cum-deconectezi-domeniul-propriu",
          titlu: "Cum deconectezi domeniul propriu",
          rezumat: "Domeniul se scoate dintr-o singură apăsare, din bannerul de sus al secțiunii Domeniu.",
          pasi: [
            "Intră în Setări > Domeniu.",
            {
              text: "În bannerul de sus, \"Domeniu conectat\", apasă butonul cu X din dreapta. La trecerea cu mausul apare titlul \"Deconectează domeniul\".",
              captura: { alt: "Bannerul \"Domeniu conectat\" cu butonul X din dreapta.", raport: 16 / 10 },
            },
          ],
          detalii: [
            { titlu: "Nu există pas de confirmare", text: "Deconectarea se face la o singură apăsare, fără fereastră de confirmare, deci apasă X doar când chiar vrei să scoți domeniul." },
            { titlu: "Celălalt buton din banner", text: "Lângă X se află un buton care deschide magazinul pe domeniul respectiv, într-o filă nouă." },
            { titlu: "Mesajele pe care le vezi", text: "La reușită apare \"Domeniu deconectat.\". Dacă nu merge, apare \"Nu am putut deconecta domeniul.\" sau \"Eroare de rețea.\". Dacă nu există niciun domeniu conectat, serverul răspunde \"Niciun domeniu de deconectat\"." },
          ],
          nota: "Deconectarea scoate domeniul din magazin. Domeniul rămâne la registrarul tău, iar înregistrările DNS setate acolo rămân până le schimbi tu.",
          termeni: ["scoate domeniu", "anulează conectarea", "banner domeniu conectat"],
        },
        {
          slug: "cum-scrii-titlul-si-descrierea-pentru-google",
          titlu: "Cum scrii titlul și descrierea cu care apare magazinul în Google",
          rezumat: "Titlul și descrierea meta se completează în Setări > SEO, cu previzualizare pentru rezultatul din Google.",
          pasi: [
            "Intră în Setări > SEO.",
            "Completează \"Titlu meta\" și urmărește numărătoarea de caractere din dreapta.",
            "Completează \"Descriere meta\".",
            {
              text: "Vezi cum arată rezultatul în \"Previzualizare în Google\".",
              captura: { alt: "Câmpurile Titlu meta și Descriere meta, cu blocul \"Previzualizare în Google\" dedesubt.", raport: 16 / 10 },
            },
            "Apasă \"Salvează SEO\", jos în dreapta. Cât timp se salvează, butonul scrie \"Se salvează...\".",
          ],
          detalii: [
            { titlu: "Ce lungime se recomandă", text: "La titlu scrie \"Recomandat până în 60 de caractere. Apare ca titlu albastru în Google și în tab-ul browserului.\" La descriere scrie \"Recomandat 150-160 de caractere. Nu schimbă direct poziția, dar crește rata de click.\"" },
            { titlu: "Numărătoarea de caractere", text: "Numărătorul devine verde de la 50 de caractere la titlu și de la 140 la descriere, apoi roșu peste 60, respectiv 160. Nu te oprește din scris, doar semnalează." },
            { titlu: "Dacă lași câmpurile goale", text: "În capul secțiunii scrie: \"Controlează cum apare pagina principală a magazinului în Google și la distribuirea pe rețele sociale. Dacă lași câmpurile goale, folosim automat numele și descrierea magazinului.\" Titlul gol cade pe numele magazinului, iar descrierea goală pe sloganul sau descrierea magazinului." },
            { titlu: "Unde se aplică valorile", text: "Textul din interfață vorbește despre pagina principală, dar titlul și descrierea se pun pe magazin la nivel de layout. Subpaginile care nu își declară propriul titlu îl moștenesc, sub forma titlu de pagină urmat de numele magazinului." },
          ],
          nota: "Fără un magazin activ, câmpurile sunt blocate și apare \"Nu ai un magazin activ. Finalizează onboarding-ul mai întâi.\". La reușită apare \"Setările SEO au fost salvate.\"",
          termeni: ["meta title", "meta description", "rezultat Google", "previzualizare", "optimizare"],
        },
        {
          slug: "cum-pui-imaginea-la-distribuire",
          titlu: "Cum pui imaginea care apare la distribuirea magazinului",
          rezumat: "Imaginea afișată pe Facebook sau WhatsApp se încarcă din Setări > SEO, în cardul \"Imagine la distribuire\".",
          pasi: [
            "Intră în Setări > SEO și coboară la \"Imagine la distribuire\".",
            {
              text: "Apasă zona punctată \"Încarcă imagine (rec. 1200×630px)\" și alege fișierul. Cât durează, scrie \"Se încarcă...\".",
              captura: { alt: "Cardul \"Imagine la distribuire\" cu zona de încărcare și câmpul de URL.", raport: 16 / 10 },
            },
            "Sau lipește o adresă în câmpul de dedesubt, \"sau lipește un URL\".",
            "Apasă \"Salvează SEO\".",
          ],
          detalii: [
            { titlu: "La ce folosește", text: "În card scrie: \"Apare când cineva distribuie magazinul pe Facebook, WhatsApp etc. Dacă lipsește, folosim coperta magazinului. Ideal 1200×630px.\"" },
            { titlu: "Cum o scoți", text: "După încărcare, imaginea se șterge cu butonul X din colțul ei. Poți pune o singură imagine." },
            { titlu: "Cele două variante", text: "Fie încarci un fișier din calculator, fie lipești adresa unei imagini care există deja online. Ambele ajung în același loc și se salvează cu \"Salvează SEO\"." },
          ],
          nota: "Este nevoie de un magazin activ.",
          termeni: ["open graph", "imagine social media", "share", "copertă", "1200x630"],
        },
        {
          slug: "cum-ascunzi-magazinul-din-google",
          titlu: "Cum ascunzi magazinul din Google",
          rezumat: "O casetă din Setări > SEO scoate magazinul din motoarele de căutare.",
          pasi: [
            "Intră în Setări > SEO.",
            {
              text: "Bifează \"Ascunde magazinul din Google (noindex)\".",
              captura: { alt: "Caseta \"Ascunde magazinul din Google (noindex)\" cu textul de avertizare.", raport: 16 / 10 },
            },
            "Apasă \"Salvează SEO\".",
          ],
          detalii: [
            { titlu: "Când se folosește", text: "În interfață scrie: \"Opțiune avansată. Activează doar dacă NU vrei ca pagina principală să apară în motoarele de căutare. Lasă dezactivat pentru SEO normal.\" Implicit, caseta este nebifată." },
            { titlu: "Acoperă și paginile de politici", text: "Cât timp această casetă e bifată, politicile nu apar în Google oricât ar fi bifate în cardul \"Paginile de politici în Google\". În interfață scrie: \"Cât timp magazinul e ascuns din Google (mai sus), politicile nu apar nici ele, oricât ar fi bifate aici.\"" },
            { titlu: "Cum revii", text: "Debifezi caseta și apeși din nou \"Salvează SEO\"." },
          ],
          nota: "Caseta este blocată fără un magazin activ.",
          termeni: ["noindex", "scoate din căutare", "motoare de căutare", "indexare"],
        },
        {
          slug: "cum-alegi-ce-politici-intra-in-google",
          titlu: "Cum alegi ce pagini de politici intră în Google",
          rezumat: "În Setări > SEO bifezi care pagini de politici apar în Google și în sitemap.",
          pasi: [
            "Intră în Setări > SEO și coboară la \"Paginile de politici în Google\".",
            {
              text: "Bifează paginile care să apară în Google și debifează-le pe celelalte.",
              captura: { alt: "Lista celor șase politici cu casetele de bifare.", raport: 16 / 10 },
            },
            "Apasă \"Salvează SEO\".",
          ],
          detalii: [
            { titlu: "Ce pagini poți bifa", text: "Termeni și condiții, Politica de livrare, Politica de retur, Politica de confidențialitate, GDPR, Politica de anulare a comenzii. Toate sunt bifate implicit." },
            { titlu: "Ce înseamnă debifarea", text: "Pagina iese din Google și din sitemap. Recomandarea din interfață: \"Bifate, apar în Google și în sitemap. Google Merchant Center cere politica de retur și termenii indexabili ca să valideze contul, deci lasă-le bifate dacă faci reclamă la produse.\"" },
            { titlu: "Bifa nu ajunge dacă politica e oprită", text: "În interfață scrie: \"O politică stinsă din Editează magazinul nu apare în Google chiar dacă e bifată: pagina ei nu are ce arăta.\" Comutatorul care oprește o politică este în Setări > Politici. Fiecare politică are acolo comutatorul ei, iar când e oprit apare eticheta \"Dezactivată\" și editorul dispare. În capul acelei secțiuni scrie că politicile dezactivate nu vor fi vizibile clienților." },
            { titlu: "Opțiunea care le anulează pe toate", text: "Dacă este bifat \"Ascunde magazinul din Google (noindex)\", bifele de aici nu mai contează." },
          ],
          nota: "Casetele sunt blocate fără un magazin activ.",
          termeni: ["sitemap", "termeni și condiții", "retur", "GDPR", "Merchant Center", "indexare politici"],
        },
        {
          slug: "cum-conectezi-magazinul-la-google-search-console",
          titlu: "Cum conectezi magazinul la Google Search Console",
          rezumat: "Din Setări > SEO copiezi adresa magazinului, lipești codul de verificare de la Google și trimiți sitemap-ul.",
          pasi: [
            "Intră în Setări > SEO și coboară la \"Google Search Console\".",
            "Copiază adresa magazinului cu butonul \"Copiază\" de lângă primul câmp, apoi adaugă în Search Console o proprietate de tip Prefix URL cu ea.",
            {
              text: "La verificare alege metoda Etichetă HTML, copiază codul de la Google și lipește-l în câmpul de verificare.",
              captura: { alt: "Cardul Google Search Console cu cei trei pași și câmpul pentru codul de verificare.", raport: 16 / 10 },
            },
            "Apasă \"Salvează SEO\", apoi apasă Verifică în Search Console.",
            "După verificare, copiază adresa sitemap-ului cu al doilea buton \"Copiază\" și adaug-o la secțiunea Sitemaps din Search Console.",
          ],
          detalii: [
            { titlu: "Ce e în fiecare câmp", text: "Primul câmp arată adresa magazinului și este doar de citit. Al doilea este cel în care lipești codul de verificare, iar exemplul afișat este eticheta completă. Al treilea arată adresa sitemap-ului, adică adresa magazinului urmată de /sitemap.xml, și este tot doar de citit." },
            { titlu: "Ce accepți la lipire", text: "Câmpul acceptă atât eticheta meta întreagă, cât și doar codul. La salvare se păstrează doar codul: se scot caracterele care nu sunt litere, cifre, liniuță sau underline, iar textul se taie la 200 de caractere." },
            { titlu: "Metoda de verificare", text: "Din acest ecran se poate folosi metoda Etichetă HTML. Celelalte metode de verificare ale Google nu sunt susținute de aici. După salvare, codul se adaugă automat în pagina magazinului, apoi apeși Verifică în Search Console." },
            { titlu: "Ce adresă se folosește", text: "Dacă ai domeniu propriu, verificarea și sitemap-ul folosesc acea adresă. Dacă magazinul este încă pe adresa edinio.com, în interfață scrie: \"Magazinul e pe adresa edinio.com. Dacă vrei domeniul tău propriu în Google, conectează-l din Setări, secțiunea Domeniu, apoi reia pașii cu noua adresă.\"" },
            { titlu: "Butoanele de copiere", text: "Aici butoanele au text, \"Copiază\", iar după apăsare apare mesajul \"Copiat.\"" },
          ],
          nota: "Search Console este serviciul Google. Edinio pune codul în pagina magazinului și îți dă adresa sitemap-ului, dar contul Google și proprietatea din Search Console sunt ale tale.",
          termeni: ["GSC", "verificare site", "meta google-site-verification", "sitemap.xml", "indexare"],
        },
        {
          slug: "cum-schimbi-parola-contului",
          titlu: "Cum schimbi parola contului",
          rezumat: "Parola se schimbă din Setări > Securitate, fără să introduci parola veche.",
          pasi: [
            "Intră în Setări > Securitate.",
            {
              text: "Scrie noua parolă în câmpul \"Parolă nouă\".",
              captura: { alt: "Cardul \"Schimbă parola\" cu cele două câmpuri.", raport: 16 / 10 },
            },
            "Repet-o în \"Confirmă parola nouă\".",
            "Apasă \"Schimbă parola\". Cât durează, butonul scrie \"Se schimbă...\".",
          ],
          detalii: [
            { titlu: "Ce cere parola", text: "Minim 8 caractere, așa cum scrie și în câmp. Dacă scrii mai puține, apare \"Parola trebuie să aibă cel puțin 8 caractere.\"" },
            { titlu: "Când butonul e blocat", text: "Butonul rămâne blocat cât timp unul dintre cele două câmpuri este gol." },
            { titlu: "Dacă cele două nu coincid", text: "Apare \"Parolele nu coincid.\" Rescrie a doua parolă și încearcă din nou." },
            { titlu: "Mesajele finale", text: "La reușită apare \"Parola a fost schimbată cu succes.\" și cele două câmpuri se golesc. Dacă nu merge, apare \"Nu am putut schimba parola.\"" },
          ],
          nota: "Nu se cere parola veche, deci oricine are sesiunea ta deschisă poate schimba parola. Ține contul închis pe calculatoarele străine.",
          termeni: ["parolă nouă", "securitate cont", "resetare parolă"],
        },
        {
          slug: "cum-activezi-autentificarea-in-doi-pasi",
          titlu: "Cum activezi autentificarea în doi pași (2FA)",
          rezumat: "2FA pe email se pornește din Setări > Securitate, cu un cod de 6 cifre trimis pe adresa contului.",
          pasi: [
            "Intră în Setări > Securitate.",
            "În cardul \"Autentificare în doi pași (2FA)\" apasă \"Activează 2FA\". Cât se trimite codul, butonul scrie \"Se trimite codul...\".",
            "Deschide emailul contului și citește codul de 6 cifre.",
            {
              text: "Scrie codul în câmpul \"Cod de verificare\".",
              captura: { alt: "Cardul 2FA cu câmpul \"Cod de verificare\" și butonul \"Verifică și activează\".", raport: 16 / 10 },
            },
            "Apasă \"Verifică și activează\" sau tasta Enter.",
          ],
          detalii: [
            { titlu: "Ce se schimbă la autentificare", text: "În antetul cardului scrie: \"La autentificare vei primi un cod de verificare pe email.\" În card scrie că la fiecare autentificare primești un cod de 6 cifre pe adresa contului tău." },
            { titlu: "Codul", text: "Are 6 cifre și expiră în 10 minute. Câmpul acceptă doar cifre, maximum 6, iar butonul \"Verifică și activează\" rămâne blocat până când ai introdus toate cele șase." },
            { titlu: "Dacă codul nu mai merge", text: "Apar \"Codul a expirat. Încearcă din nou.\" sau \"Cod incorect sau expirat.\". Apasă din nou \"Activează 2FA\" ca să primești alt cod." },
            { titlu: "Când e gata", text: "Apare \"Autentificarea în doi pași a fost activată.\" și în antetul cardului apare eticheta \"Activ\". Butonul \"Anulează\" renunță și golește codul." },
          ],
          nota: "Se poate doar 2FA pe email. Nu există opțiune de aplicație de autentificare sau SMS în acest ecran, deci ai nevoie de acces permanent la căsuța de email a contului.",
          termeni: ["doi factori", "cod pe email", "two factor", "protecție cont"],
        },
        {
          slug: "cum-dezactivezi-autentificarea-in-doi-pasi",
          titlu: "Cum dezactivezi autentificarea în doi pași (2FA)",
          rezumat: "Oprirea 2FA cere tot un cod trimis pe emailul contului.",
          pasi: [
            "Intră în Setări > Securitate.",
            "Apasă \"Dezactivează 2FA\". Cât se trimite codul, butonul scrie \"Se trimite codul...\".",
            "Citește codul primit pe emailul contului.",
            {
              text: "Scrie-l în \"Cod de verificare\" și apasă \"Confirmă dezactivarea\" sau tasta Enter.",
              captura: { alt: "Cardul 2FA în timpul dezactivării, cu butonul \"Confirmă dezactivarea\".", raport: 16 / 10 },
            },
          ],
          detalii: [
            { titlu: "Nu se poate opri fără email", text: "Și dezactivarea cere codul trimis pe adresa contului. Fără acces la acea căsuță, 2FA nu poate fi oprit din acest ecran." },
            { titlu: "Butonul de confirmare", text: "Rămâne blocat până când codul are 6 cifre. \"Anulează\" renunță și golește câmpul." },
            { titlu: "Ce scrie pe ecran", text: "Cât timp 2FA e activ: \"Contul tău este protejat. La autentificare vei primi un cod pe adresa ta.\" După trimiterea codului: \"Am trimis un cod de verificare la adresa ta. Introdu-l mai jos pentru a dezactiva 2FA.\"" },
            { titlu: "Când e gata", text: "Apare \"Autentificarea în doi pași a fost dezactivată.\" Dacă codul a expirat, primești \"Codul a expirat. Încearcă din nou.\" sau \"Cod incorect sau expirat.\" și poți cere altul." },
          ],
          nota: "Codul are 6 cifre și expiră în 10 minute.",
          termeni: ["oprește 2FA", "scoate verificarea", "cod email"],
        },
        {
          slug: "cum-stergi-definitiv-contul-setari-magazin",
          titlu: "Cum ștergi definitiv contul",
          rezumat: "Ștergerea contului se face din Setări > Securitate, din \"Zona periculoasă\", și nu poate fi anulată.",
          pasi: [
            "Intră în Setări > Securitate și coboară la \"Zona periculoasă\".",
            "Apasă \"Șterge contul\".",
            "Citește avertismentul din \"Confirmă ștergerea contului\".",
            {
              text: "Scrie adresa de email a contului în câmpul cerut. Eticheta arată exact adresa care trebuie tastată.",
              captura: { alt: "Fereastra \"Confirmă ștergerea contului\" cu câmpul de email și butonul blocat.", raport: 16 / 10 },
            },
            "Apasă \"Confirmă ștergerea\". Cât durează, butonul scrie \"Se șterge...\".",
          ],
          detalii: [
            { titlu: "Ce se șterge", text: "Textele afișate spun: \"Această acțiune este ireversibilă. Toate datele tale, inclusiv magazinele și comenzile, vor fi șterse definitiv.\" și \"Această acțiune va șterge permanent contul tău, magazinele, produsele și toate comenzile. Nu poate fi anulată.\"" },
            { titlu: "Confirmarea prin email", text: "Butonul \"Confirmă ștergerea\" rămâne blocat până când adresa tastată este identică cu cea a contului. Butonul \"Anulează\" închide confirmarea și golește câmpul." },
            { titlu: "Ce se întâmplă după", text: "Ești deconectat și trimis la pagina de autentificare." },
            { titlu: "Dacă apare o eroare", text: "Poți primi \"Ștergerea contului nu este disponibilă momentan. Contactați suportul.\" sau \"Eroare la ștergerea contului. Încearcă din nou.\". În primul caz, scrie la suport. În al doilea, reia pașii." },
          ],
          nota: "La ștergere nu se cere parola și nici cod 2FA, doar tastarea adresei de email. Înainte să confirmi, descarcă din panoul de administrare tot ce îți mai trebuie.",
          termeni: ["închide contul", "zona periculoasă", "ștergere date", "dezactivare cont"],
        },
      ],
    },
    {
      titlu: "Email, notificări și politici",
      ghiduri: [
        {
          slug: "cum-deschizi-setarile-email-notificari-politici-cookies",
          titlu: "Cum deschizi secțiunile Email, Notificări, Politici și Banner Cookies din Setări",
          rezumat: "Unde găsești cele patru secțiuni în panoul de administrare și cum treci de la una la alta.",
          pasi: [
            "În meniul din stânga al panoului de administrare, jos de tot, apeși „Setări”.",
            {
              text: "În coloana din stânga a ecranului de setări, sub titlul „SETĂRI”, apeși secțiunea dorită: „Email”, „Notificări”, „Politici” sau „Banner Cookies”.",
              captura: { alt: "Coloana din stânga a ecranului de setări, cu secțiunea Email selectată.", raport: 16 / 10 },
            },
            "Titlul mare din capul paginii se schimbă în numele secțiunii alese și conținutul ei apare în dreapta.",
          ],
          detalii: [
            { titlu: "Toate secțiunile din listă", text: "Coloana din stânga are, în ordine: General, Tip magazin, Plan, Facturare, Livrare, Taxe, Metode de plată, Domeniu, SEO, Email, Notificări, Politici, Banner Cookies, Securitate." },
            { titlu: "Pe telefon și pe ecrane mici", text: "Lista din stânga dispare. Aceleași nume apar într-o bară orizontală, lipită sub bara de sus, pe care o derulezi lateral până ajungi la secțiunea căutată." },
            { titlu: "Link direct către o secțiune", text: "Poți intra direct pe secțiune dacă adresa se termină în #email, #notificari, #politici sau #cookies. Când apeși pe o secțiune din listă, adresa din bara browserului nu se schimbă, deci nu poți salva un link către ea doar dând click." },
            { titlu: "Când vii dintr-o plată", text: "Dacă tocmai ai plătit un plan sau un domeniu, pagina de setări se deschide forțat pe „Plan”, respectiv „Domeniu”, iar terminația de adresă pe care ai pus-o tu este ignorată." },
          ],
          nota: "Trebuie să fii autentificat. Fără sesiune activă, pagina de setări te trimite la pagina de autentificare.",
          termeni: ["unde sunt setarile", "panou de administrare", "meniu lateral", "dashboard settings", "sectiuni setari"],
        },
        {
          slug: "cum-conectezi-emailul-propriu-smtp",
          titlu: "Cum trimiți emailurile magazinului de pe adresa ta (SMTP propriu)",
          rezumat: "Conectezi contul tău de email ca emailurile către clienți să plece de pe domeniul tău, nu de pe Edinio.",
          intro: "Implicit, emailurile către clienți pleacă de pe Edinio. Dacă vrei ca ele să plece de pe adresa ta, conectezi serverul SMTP al furnizorului tău de email. Este opțional: dacă nu configurezi nimic, totul rămâne cum e acum.",
          pasi: [
            "Intri în Setări > Email.",
            "Pui pe pornit comutatorul „Trimite de pe emailul meu”.",
            {
              text: "La eticheta „Furnizor” apeși butonul furnizorului tău: „Google Workspace / Gmail”, „Microsoft 365 / Outlook”, „Zoho Mail” sau „Alt server (cPanel / hosting propriu)”.",
              captura: { alt: "Butoanele de furnizor din secțiunea Email, cu câmpurile de server și port completate automat.", raport: 16 / 10 },
            },
            "Completezi „Utilizator (email)” cu adresa contului și „Parola” cu parola SMTP sau parola de aplicație.",
            "Completezi „Nume expeditor” și „Email expeditor”. Dacă vrei răspunsurile clienților pe altă adresă, completezi și „Reply-to (opțional)”.",
            "Apeși „Salvează”. Cât timp lucrează, butonul scrie „Se salvează...”.",
            "Dacă datele sunt bune, apare mesajul „Email propriu conectat.”",
          ],
          detalii: [
            { titlu: "Ce completează singură presetarea de furnizor", text: "Presetarea pune doar serverul, portul și tipul de securitate.\n„Google Workspace / Gmail”: smtp.gmail.com, portul 465, SSL.\n„Microsoft 365 / Outlook”: smtp.office365.com, portul 587, STARTTLS.\n„Zoho Mail”: smtp.zoho.eu, portul 465, SSL.\n„Alt server (cPanel / hosting propriu)”: lasă serverul gol și pune portul 465 cu SSL, deci scrii tu adresa serverului primită de la găzduire.\nPresetarea nu salvează nimic singură. Salvarea se face tot cu butonul „Salvează”." },
            { titlu: "Câmpurile, pe rând", text: "„Server (host)”: adresa serverului de trimitere, de exemplu smtp.gmail.com.\n„Port”: numărul portului, de exemplu 465.\n„Securitate”: alegi „SSL / TLS (465)” sau „STARTTLS (587)”, potrivit cu portul.\n„Utilizator (email)”: adresa cu care te autentifici la furnizor, de exemplu comenzi@domeniul-tau.ro.\n„Parola”: parola SMTP sau parola de aplicație.\n„Nume expeditor”: numele pe care îl vede clientul, de exemplu Magazinul meu.\n„Email expeditor”: adresa de pe care pleacă emailurile.\n„Reply-to (opțional)”: adresa la care primești răspunsurile, dacă e alta decât expeditorul." },
            { titlu: "Parola și ce se întâmplă cu ea", text: "La Gmail cu verificare în 2 pași ai nevoie de o parolă de aplicație, nu de parola contului. Panoul îți spune asta când alegi presetarea Google.\nDupă salvare, parola nu se mai afișează niciodată înapoi. Câmpul rămâne gol și scrie că îl poți lăsa gol ca să păstrezi parola actuală. Dacă vrei să o schimbi, scrii una nouă peste." },
            { titlu: "Ce se întâmplă la salvare", text: "Cu comutatorul pornit, Edinio testează conexiunea înainte să activeze ceva. Dacă testul nu trece, primești „Conexiunea SMTP a eșuat: ” urmat de mesajul serverului tău și nimic nu se activează.\nDacă lipsește un câmp obligatoriu, primești „Completează toate câmpurile (server, port, utilizator, parolă, email expeditor).”\nDacă portul e gol sau scris greșit, se salvează 465.\nAlte mesaje posibile: „Neautorizat”, „Magazin negăsit”, „Eroare la salvare.”" },
            { titlu: "Dacă lași comutatorul oprit", text: "Butonul „Salvează” doar memorează datele și afișează „Setări salvate.”. Emailurile continuă să plece de pe Edinio până când pornești comutatorul și salvezi din nou." },
            { titlu: "Dacă serverul tău nu răspunde la o trimitere", text: "Când SMTP-ul tău cade în momentul trimiterii, emailul pleacă automat prin Edinio, ca să ajungă totuși la client." },
          ],
          nota: "Contul de email cu acces SMTP este al tău, la furnizorul tău. Edinio face conectarea, dar adresa, parola și contractul cu Gmail, Microsoft 365, Zoho sau găzduirea ta rămân în grija ta. Fără magazin creat apare „Nu ai un magazin activ. Finalizează onboarding-ul mai întâi.” și câmpurile sunt blocate.",
          termeni: ["smtp", "email propriu", "gmail app password", "office365 smtp", "zoho", "trimitere emailuri de pe domeniul meu"],
        },
        {
          slug: "cum-trimiti-email-de-test-prin-smtp",
          titlu: "Cum trimiți un email de test prin serverul tău SMTP",
          rezumat: "Verifici că emailurile pleacă prin serverul tău, după ce ai salvat configurarea SMTP.",
          pasi: [
            "Intri în Setări > Email.",
            "Te asiguri că ai comutatorul „Trimite de pe emailul meu” pornit și configurarea deja salvată cu „Salvează”.",
            {
              text: "Apeși „Trimite email de test”.",
              captura: { alt: "Butonul Trimite email de test din secțiunea Email, lângă butonul Salvează.", raport: 16 / 10 },
            },
            "Dacă reușește, apare mesajul „Email de test trimis. Verifică-ți inboxul.”",
          ],
          detalii: [
            { titlu: "Unde ajunge emailul", text: "Testul pleacă spre adresa scrisă în câmpul „Email expeditor”. Nu poți alege altă destinație din acest ecran." },
            { titlu: "Testul folosește doar ce e salvat", text: "Sunt citite datele din contul tău, nu ce ai tastat și n-ai salvat încă. Dacă tocmai ai schimbat serverul sau parola, apeși întâi „Salvează”, apoi „Trimite email de test”." },
            { titlu: "Mesaje pe care le poți primi", text: "„Configurează și salvează SMTP-ul mai întâi.” apare dacă nu ai salvat configurarea sau dacă ai comutatorul oprit.\n„Trimiterea a eșuat: ” apare urmat de mesajul serverului tău. De obicei e vorba de parolă greșită, de o parolă de aplicație lipsă la conturile cu verificare în 2 pași sau de un port care nu se potrivește cu tipul de securitate ales." },
          ],
          nota: "Emailul de test din secțiunea Notificări este altceva: acela pleacă întotdeauna de pe Edinio, nu prin serverul tău.",
          termeni: ["test smtp", "verifica emailul", "email de proba", "nu primesc emailuri"],
        },
        {
          slug: "cum-schimbi-logo-si-culoare-emailuri",
          titlu: "Cum schimbi logo-ul și culoarea din emailurile către clienți",
          rezumat: "Pui alt logo și altă culoare de accent doar pentru emailuri, fără să atingi magazinul online.",
          intro: "Implicit, emailurile folosesc logo-ul și culoarea magazinului. Le poți schimba separat, din cardul „Brandingul emailurilor”.",
          pasi: [
            "Intri în Setări > Email și cobori la cardul „Brandingul emailurilor”.",
            "Apeși „Schimbă logo”. Poți da click și direct pe logo, în previzualizarea unui șablon deschis.",
            {
              text: "În fereastra care se deschide alegi tab-ul „Bibliotecă” și o imagine deja încărcată, sau tab-ul „Încarcă” și apeși „Apasă pentru a încărca fișiere”.",
              captura: { alt: "Fereastra de alegere a imaginii, cu tab-urile Bibliotecă și Încarcă.", raport: 16 / 10 },
            },
            "Apeși butonul „Adaugă”. După ce ai selectat o imagine, pe buton apare și numărul selecției, „Adaugă (1)”.",
            "Pentru culoare, apeși pătratul de lângă eticheta „Culoare” și alegi nuanța dorită.",
            "Închizi selectorul de culoare. Apare mesajul „Branding email salvat.” și previzualizările se actualizează.",
          ],
          detalii: [
            { titlu: "Se salvează singur", text: "Logo-ul și culoarea se salvează pe loc, fără buton separat. Butonul „Salvează” din partea de sus a secțiunii este pentru datele serverului SMTP, nu pentru branding." },
            { titlu: "Unde se aplică", text: "Logo-ul și culoarea puse aici merg la toate cele patru șabloane de email. Magazinul online rămâne neschimbat, cu logo-ul și culoarea lui." },
            { titlu: "Cum revii la varianta magazinului", text: "Pentru logo apeși „Elimină (folosește logo magazin)”. Pentru culoare apeși „Reset”. Ambele butoane apar numai dacă ai pus ceva separat pentru emailuri." },
            { titlu: "Ce acceptă fereastra de alegere a imaginii", text: "Doar imagini, iar fișierele încărcate de aici ajung în spațiul de logo-uri. Se folosește o singură imagine, prima selectată. În bibliotecă ai și un câmp de căutare, iar dacă nu ai încă nimic încărcat vezi mesajul care te trimite la tab-ul „Încarcă”." },
          ],
          nota: "Fără magazin creat, butonul „Schimbă logo” este inactiv.",
          termeni: ["logo email", "culoare email", "branding emailuri", "antet email"],
        },
        {
          slug: "cum-modifici-textele-unui-sablon-de-email",
          titlu: "Cum modifici textele unui șablon de email",
          rezumat: "Schimbi subiectul, titlul, mesajul și butonul unui email, scriind direct pe previzualizare.",
          pasi: [
            "Intri în Setări > Email și cobori la cardul „Șabloane de email”.",
            "Apeși pe rândul șablonului pe care vrei să îl modifici ca să îl deschizi.",
            "Scrii textul dorit în câmpul „Subiect”.",
            {
              text: "Sub textul „Editează direct pe email (apasă pe titlu, text, buton sau logo)” dai click în previzualizare pe titlu, pe paragraf sau pe buton și scrii peste.",
              captura: { alt: "Previzualizarea unui email cu titlul selectat pentru editare.", raport: 16 / 10 },
            },
            "Apeși „Salvează șablonul”. Apare mesajul „Șablon salvat.” și rândul primește eticheta „Personalizat”.",
          ],
          detalii: [
            { titlu: "Cele patru șabloane", text: "„Confirmare comandă”, emailul primit de client imediat după ce plasează o comandă. Subiect standard: „Comanda ta {{numar_comanda}} a fost primită”, titlu standard: „Comanda ta a fost plasată”.\n„Actualizare status comandă”, emailul primit de client când comanda își schimbă statusul. Subiect standard: „Actualizare comandă {{numar_comanda}}”.\n„Coș abandonat”, emailul de recuperare pentru clienții care au lăsat produse în coș. Subiect standard: „Ai uitat ceva în coș la {{nume_magazin}}”, titlu standard: „Ți-au rămas produse în coș”.\n„Comandă nouă (către tine)”, notificarea pe care o primești tu. Subiect standard: „Comandă nouă {{numar_comanda}} - {{nume_client}}”, titlu standard: „Comandă nouă”." },
            { titlu: "Ce se poate edita și ce nu", text: "Se editează subiectul, titlul și mesajul. Text de buton are doar „Coș abandonat”, unde butonul standard scrie „Finalizează comanda”.\nLa „Actualizare status comandă” titlul nu se poate edita, pentru că șablonul nu are un titlu propriu. Acolo schimbi doar subiectul și mesajul, chiar dacă textul de deasupra previzualizării vorbește despre titlu.\nTabelul cu produse, caseta de comandă și statusul din previzualizare se generează automat și nu se pot edita. Produsele și numărul comenzii pe care le vezi acolo sunt doar un exemplu." },
            { titlu: "Detalii de scriere", text: "La titlu și la textul butonului, tasta Enter nu face rând nou.\nDacă lași un text identic cu cel standard, el nu se salvează ca personalizare.\nFiecare șablon are butonul lui de salvare. Modificările dintr-un șablon nu se salvează odată cu altul." },
            { titlu: "Șablonul Coș abandonat", text: "Textul se poate edita pe orice plan, dar trimiterea automată a emailurilor de recuperare rulează pe planurile Premium și Ultra." },
          ],
          nota: "Fără magazin creat, câmpurile și butonul de salvare sunt inactive.",
          termeni: ["sabloane email", "personalizare email", "subiect email", "confirmare comanda", "cos abandonat"],
        },
        {
          slug: "cum-folosesti-variabilele-din-emailuri",
          titlu: "Cum folosești variabilele din șabloanele de email",
          rezumat: "Copiezi variabile de tipul {{nume_client}} și le pui în subiect sau în text ca să se completeze automat la trimitere.",
          pasi: [
            "Intri în Setări > Email > Șabloane de email și deschizi șablonul dorit.",
            {
              text: "Sub previzualizare, la textul „Variabile disponibile (apasă ca să copiezi):”, apeși eticheta variabilei.",
              captura: { alt: "Lista de variabile disponibile sub previzualizarea unui șablon.", raport: 16 / 10 },
            },
            "Primești confirmarea „Copiat” împreună cu variabila.",
            "O lipești în câmpul „Subiect” sau în textul din previzualizare, acolo unde vrei să apară datele clientului.",
            "Apeși „Salvează șablonul”.",
          ],
          detalii: [
            { titlu: "Ce variabile are fiecare șablon", text: "„Confirmare comandă”: {{nume_client}}, {{nume_magazin}}, {{numar_comanda}}, {{total}}.\n„Actualizare status comandă”: {{nume_client}}, {{nume_magazin}}, {{numar_comanda}}, {{status}}.\n„Coș abandonat”: {{nume_client}} și {{nume_magazin}}.\n„Comandă nouă (către tine)”: {{nume_magazin}}, {{numar_comanda}}, {{nume_client}}, {{total}}." },
            { titlu: "Cum arată la trimitere", text: "Textele cu acolade se înlocuiesc cu datele reale ale comenzii și ale clientului. În previzualizare rămân ca exemplu, la fel ca produsele și numărul comenzii afișate acolo." },
            { titlu: "Dacă scrii o variabilă greșit", text: "O variabilă scrisă cu altă ortografie sau care nu aparține șablonului respectiv se înlocuiește cu text gol la trimitere, deci clientul vede un spațiu în loc de informație. De aceea e mai sigur să le copiezi din listă decât să le scrii de mână." },
          ],
          termeni: ["variabile email", "placeholder", "nume client in email", "numar comanda in email"],
        },
        {
          slug: "cum-resetezi-un-sablon-de-email",
          titlu: "Cum readuci un șablon de email la textul standard",
          rezumat: "Ștergi personalizarea unui email și revii la varianta implicită din Edinio.",
          pasi: [
            "Intri în Setări > Email > Șabloane de email.",
            "Deschizi șablonul care are eticheta „Personalizat”.",
            {
              text: "În stânga jos apeși „Resetează la standard”.",
              captura: { alt: "Butonul Resetează la standard, în stânga jos a unui șablon personalizat.", raport: 16 / 10 },
            },
            "Textele revin la cele standard și apare mesajul „Revenit la șablonul standard.”",
          ],
          detalii: [
            { titlu: "Ce se șterge", text: "Resetarea șterge dintr-o dată subiectul, titlul, mesajul și textul de buton personalizate ale acelui șablon. Nu se poate reveni doar la subiect sau doar la titlu." },
            { titlu: "Un șablon pe rând", text: "Nu există un buton care să reseteze toate șabloanele deodată. Fiecare se resetează din interiorul lui." },
            { titlu: "Când nu apare butonul", text: "„Resetează la standard” apare doar la șabloanele modificate, adică la cele cu eticheta „Personalizat”. La un șablon nemodificat nu ai ce reseta." },
          ],
          termeni: ["reseteaza sablon", "revin la textul initial", "sterg personalizarea emailului"],
        },
        {
          slug: "cum-setezi-adresa-pentru-notificari",
          titlu: "Cum setezi adresa pe care primești notificările magazinului",
          rezumat: "Alegi adresa de email unde ajung anunțurile despre activitatea magazinului tău.",
          pasi: [
            "Intri în Setări > Notificări.",
            {
              text: "În cardul „Adresă de email pentru notificări” scrii adresa pe care vrei să primești anunțurile.",
              captura: { alt: "Cardul Adresă de email pentru notificări, cu adresa completată.", raport: 16 / 10 },
            },
            "Apeși „Salvează notificările”. Cât timp lucrează, butonul scrie „Se salvează...”.",
            "Apare mesajul „Setările de notificări au fost salvate.”",
          ],
          detalii: [
            { titlu: "Ce se verifică la salvare", text: "Câmpul e obligatoriu. Dacă îl lași gol primești „Adresa de email este obligatorie.”, iar dacă adresa nu are semnul @ și un punct primești „Adresa de email nu este validă.”" },
            { titlu: "O singură adresă", text: "Se poate pune o singură adresă. Dacă vrei ca notificările să ajungă la mai multe persoane, folosești o adresă care redistribuie mai departe, configurată la furnizorul tău de email." },
            { titlu: "Ce se întâmplă dacă rămâne goală", text: "Dacă în cont nu există nicio adresă salvată, notificările pleacă pe emailul contului de proprietar. În câmp apare, ca exemplu, chiar adresa contului tău." },
            { titlu: "Unde se mai folosește adresa", text: "Aceeași adresă primește și anunțul de cerere de retur, dacă nu ai pus altă adresă în setările de retururi." },
            { titlu: "Ce mai salvează butonul", text: "„Salvează notificările” salvează dintr-o apăsare și adresa, și comutatorul „Comandă nouă”. Mesaje posibile de eroare: „Nu există un magazin asociat.”, „Neautorizat”, „Magazin negăsit”, „Eroare la salvare.”" },
          ],
          nota: "Fără magazin creat apare „Nu ai un magazin activ. Finalizează onboarding-ul mai întâi.” și câmpul este blocat.",
          termeni: ["email notificari", "unde primesc anunturi", "adresa comenzi noi"],
        },
        {
          slug: "cum-pornesti-sau-opresti-notificarea-comanda-noua",
          titlu: "Cum pornești sau oprești emailul de comandă nouă",
          rezumat: "Alegi dacă primești un email de fiecare dată când un client plasează o comandă.",
          pasi: [
            "Intri în Setări > Notificări și cobori la cardul „Evenimente”.",
            {
              text: "Pe rândul „Comandă nouă” muți comutatorul din dreapta pe pornit sau pe oprit.",
              captura: { alt: "Cardul Evenimente, cu rândul Comandă nouă și comutatorul lui.", raport: 16 / 10 },
            },
            "Apeși „Salvează notificările”.",
          ],
          detalii: [
            { titlu: "Ce înseamnă fiecare stare", text: "Pornit: primești un email imediat ce intră o comandă. Implicit, comutatorul este pornit.\nOprit: nu mai primești tu emailul de comandă nouă. Clientul primește în continuare confirmarea comenzii lui, pentru că sunt două emailuri diferite." },
            { titlu: "Ce nu oprește comutatorul", text: "Emailul de cerere de retur ajunge la tine și cu acest comutator oprit. „Comandă nouă” este singurul eveniment din listă, deci de aici nu se pot regla alte tipuri de notificări." },
            { titlu: "Salvarea", text: "Modificarea comutatorului intră în vigoare doar după ce apeși „Salvează notificările”. Același buton salvează și adresa de email de mai sus." },
          ],
          nota: "Fără magazin creat, comutatorul este blocat.",
          termeni: ["notificare comanda", "nu mai primesc emailuri la comenzi", "alerta comanda noua"],
        },
        {
          slug: "cum-testezi-notificarile",
          titlu: "Cum trimiți un email de test pentru notificări",
          rezumat: "Verifici că adresa de notificări primește emailuri, fără să aștepți o comandă reală.",
          pasi: [
            "Intri în Setări > Notificări și cobori la cardul „Testează notificările”.",
            "Apeși „Trimite email de test”. Cât timp lucrează, butonul scrie „Se trimite...”.",
            {
              text: "Citești caseta de rezultat care apare sub buton.",
              captura: { alt: "Caseta verde de rezultat după un email de test trimis cu succes.", raport: 16 / 10 },
            },
          ],
          detalii: [
            { titlu: "Cum arată rezultatul", text: "La reușită apare o casetă verde cu „Succes” și textul „Email trimis cu succes către” urmat de adresă, plus o linie cu expeditorul și cu ID-ul mesajului. La eșec apare o casetă roșie cu „Eroare” și motivul." },
            { titlu: "Ce adresă folosește testul", text: "Adresa tastată în câmpul de mai sus, chiar dacă nu ai apăsat încă „Salvează notificările”. Dacă ai lăsat câmpul gol, testul pleacă spre emailul contului tău." },
            { titlu: "Testul nu trece prin SMTP-ul tău", text: "Emailul de test pentru notificări pleacă întotdeauna de pe Edinio, cu subiectul „Test notificare Edinio”, chiar dacă ai conectat un server propriu în Setări > Email. Ca să verifici serverul tău, folosești butonul de test din secțiunea Email." },
            { titlu: "Mesaje de eroare posibile", text: "„Adresa de email lipsește.” înseamnă că nu s-a trimis nicio adresă, deci completezi câmpul și încerci din nou.\n„Eroare rețea:” apare când cererea nu a ajuns la server, deci merită o a doua încercare.\nDacă vezi un mesaj despre cheia Resend care nu este setată sau un mesaj care începe cu „Resend error:”, problema este la trimiterea de pe partea Edinio, nu la datele tale, și se rezolvă cu suportul." },
          ],
          nota: "Fără magazin creat, butonul este inactiv.",
          termeni: ["test notificari", "nu primesc email de test", "verific notificari"],
        },
        {
          slug: "cum-completezi-politicile-magazinului",
          titlu: "Cum completezi politicile obligatorii ale magazinului",
          rezumat: "Scrii sau modifici cele șase politici care apar în subsolul magazinului tău.",
          intro: "Conform legislației române, magazinul trebuie să afișeze aceste politici. Edinio îți pune în editor un model generat din datele firmei tale, pe care îl completezi și îl adaptezi.",
          pasi: [
            "Intri în Setări > Politici.",
            "Găsești cardul politicii dorite și citești textul deja completat în editorul din el.",
            {
              text: "Modifici sau rescrii textul direct în editor.",
              captura: { alt: "Cardul unei politici cu editorul deschis și bara de formatare.", raport: 16 / 10 },
            },
            "Folosești butoanele din bara editorului pentru formatare, liste, aliniere, link sau pentru codul HTML.",
            "Apeși „Salvează politicile”. Cât timp lucrează, butonul scrie „Se salvează...”.",
            "Apare mesajul „Politicile au fost salvate.” și magazinul public se actualizează.",
          ],
          detalii: [
            { titlu: "Cele șase politici", text: "Termeni și condiții, Politica de livrare, Politica de retur, Politica de confidențialitate, GDPR, Politica de anulare a comenzii. Sunt fixe, nu poți adăuga altele din acest ecran. În subsolul magazinului, ultima apare sub numele „Politica de anulare”." },
            { titlu: "Completează întâi datele firmei", text: "Modelul generat ia datele din Setări > General. Dacă firma nu e completată, în text rămân locuri de completat de tipul „[Denumire Firmă]”, „[CUI/CIF]” sau „[completați]”. Le vezi direct în editor și le poți înlocui manual." },
            { titlu: "Bara editorului", text: "Butoanele din bara de sus sunt doar iconițe. Numele lor, „Aldin”, „Cursiv”, „Subliniat”, „Tăiat”, „Cod inline”, „Titlu mare”, „Titlu mediu”, „Titlu mic”, „Listă cu puncte”, „Listă numerotată”, cele trei de aliniere, „Adaugă link” și „Sursă HTML”, apar ca text când treci cu mouse-ul peste ele." },
            { titlu: "Cum pui un link", text: "Selectezi textul și apeși butonul de link. Se deschide o casetă a browserului cu „Introdu URL-ul:”. Scrii adresa și confirmi. Dacă lași caseta goală, linkul se scoate de pe textul selectat." },
            { titlu: "Ce văd clienții până salvezi", text: "Modelul pre-completat nu există doar în editor. Cât timp politica este activă și textul ei e gol în baza magazinului, pagina publică arată același model. Deci clienții nu rămân fără text, dar merită să îl citești și să îl potrivești pe magazinul tău." },
            { titlu: "Un buton pentru tot", text: "„Salvează politicile” salvează toate cele șase texte și stările lor de activare dintr-o apăsare. Mesaje posibile de eroare: „Nu există un magazin asociat.”, „Neautorizat”, „Magazin negăsit”, „Eroare la salvare.”" },
          ],
          nota: "Fără magazin creat apare „Nu ai un magazin activ. Finalizează onboarding-ul mai întâi.” și editoarele sunt blocate.",
          termeni: ["termeni si conditii", "gdpr", "politica de retur", "politica de livrare", "confidentialitate", "subsol magazin"],
        },
        {
          slug: "cum-dezactivezi-o-politica",
          titlu: "Cum dezactivezi sau reactivezi o politică",
          rezumat: "Oprești afișarea unei politici pe magazin, fără să pierzi textul scris.",
          pasi: [
            "Intri în Setări > Politici.",
            "În capul cardului politicii muți comutatorul din dreapta pe oprit.",
            {
              text: "Cardul primește eticheta „Dezactivată”, iar editorul dispare din card.",
              captura: { alt: "Cardul unei politici cu eticheta Dezactivată și editorul ascuns.", raport: 16 / 10 },
            },
            "Apeși „Salvează politicile”.",
          ],
          detalii: [
            { titlu: "Textul rămâne salvat", text: "Cât timp politica e oprită nu poți edita textul, pentru că editorul se ascunde. Textul scris rămâne în cont și reapare exact cum era când muți comutatorul înapoi pe pornit și salvezi." },
            { titlu: "Ce văd clienții", text: "Legătura către politică rămâne în subsolul magazinului, iar pagina ei există în continuare. Clientul care o deschide vede mesajul „Această politică nu este disponibilă momentan.”" },
            { titlu: "Legătura cu Google", text: "O politică oprită nu mai are conținut de arătat, deci nu mai are ce ajunge în Google. Dacă vrei să reglezi indexarea paginilor de politici, controlul este în Setări > SEO, la „Paginile de politici în Google”." },
          ],
          nota: "Fără magazin creat, comutatorul este blocat.",
          termeni: ["ascunde politica", "dezactivez termeni si conditii", "politica dezactivata"],
        },
        {
          slug: "cum-configurezi-bannerul-de-cookie-uri",
          titlu: "Cum activezi bannerul de cookie-uri și alegi unde apare",
          rezumat: "Pornești sau oprești bannerul GDPR de pe magazin și îi alegi poziția pe ecran.",
          intro: "Bannerul de cookie-uri este obligatoriu prin lege. Apare automat pe magazin, în culoarea magazinului, și cere acordul vizitatorilor înainte să încarce instrumentele de analiză și marketing.",
          pasi: [
            "Intri în Setări > Banner Cookies.",
            "În cardul „Afișează bannerul de cookie-uri” muți comutatorul pe pornit sau pe oprit.",
            {
              text: "În cardul „Poziționare” apeși una dintre cele patru variante. Varianta aleasă primește o bifă.",
              captura: { alt: "Cardul Poziționare cu cele patru variante, una dintre ele bifată.", raport: 16 / 10 },
            },
            "Apeși „Salvează bannerul”. Cât timp lucrează, butonul scrie „Se salvează...”.",
            "Apare mesajul „Bannerul de cookie-uri a fost salvat.” și magazinul public se actualizează.",
          ],
          detalii: [
            { titlu: "Cele patru poziții", text: "„Bară jos (subtil)”: bară discretă pe toată lățimea, jos. Ocupă minim de spațiu și este poziția implicită.\n„Card stânga-jos”: card compact în colțul din stânga jos.\n„Card dreapta-jos”: card compact în colțul din dreapta jos.\n„Modal centrat”: fereastră centrată cu fundal întunecat, cu vizibilitate maximă." },
            { titlu: "Ce vede vizitatorul", text: "La „Bară jos (subtil)” apar butoanele „Setări”, „Refuză” și „Acceptă”, iar detaliile se deschid ca fereastră centrată.\nLa celelalte trei poziții, panoul „Preferințe cookie-uri” are „Refuză tot”, „Salvează alegerea” și „Acceptă tot”." },
            { titlu: "Ce se întâmplă dacă oprești bannerul", text: "Apare avertismentul „Instrumentele de marketing se încarcă fără consimțământ”. Pixelii Facebook și TikTok și Google Analytics se încarcă pentru toți vizitatorii, fără să le ceară acordul. Pixelul devine vizibil imediat în Pixel Helper, dar răspunderea pentru conformitatea GDPR îți aparține.\nCardul „Poziționare” rămâne vizibil, dar estompat și fără efect." },
            { titlu: "Linkul din subsolul magazinului", text: "Linkul „Setări cookie-uri” din subsol apare doar după ce vizitatorul a făcut o alegere în banner. Dacă stingi bannerul, vizitatorii care aleseseră deja continuă să vadă linkul, dar el nu mai deschide nimic." },
            { titlu: "Ce se poate schimba și ce nu", text: "Din acest ecran se reglează doar starea pornit sau oprit și poziția. Textele și culoarea bannerului vin din magazin, iar categoriile se deduc automat din integrările tale active." },
          ],
          nota: "Fără magazin creat poți muta comutatorul și alege poziția, dar nu poți salva: butonul „Salvează bannerul” este inactiv și apare „Nu ai un magazin activ. Finalizează onboarding-ul mai întâi.”",
          termeni: ["cookie banner", "gdpr consimtamant", "pixel facebook", "pozitie banner", "accept cookies"],
        },
        {
          slug: "cum-verifici-categoriile-de-cookie-uri",
          titlu: "Cum verifici ce categorii de cookie-uri le arăți vizitatorilor",
          rezumat: "Citești ce categorii apar în bannerul magazinului tău și de ce depind ele.",
          pasi: [
            "Intri în Setări > Banner Cookies.",
            "Cobori la cardul „Categorii afișate în banner”.",
            {
              text: "Citești etichetele afișate acolo.",
              captura: { alt: "Cardul Categorii afișate în banner, cu etichetele active.", raport: 16 / 10 },
            },
          ],
          detalii: [
            { titlu: "Nu este o setare", text: "Categoriile nu se bifează, nu se adaugă și nu se scot din acest card. Ele se adaptează automat la integrările pe care le ai active, iar butonul „Salvează bannerul” nu le salvează, pentru că sunt deduse." },
            { titlu: "Ce etichete pot apărea", text: "„Esențiale (mereu active)” apare întotdeauna.\n„Analiză (Google)” apare dacă ai o integrare de analiză activă.\n„Marketing (Facebook, TikTok)” apare dacă ai un pixel activ." },
            { titlu: "Dacă nu ai nicio integrare", text: "În card apare un text care spune că bannerul informează doar despre cookie-urile esențiale și că, la activarea Facebook Pixel, TikTok Pixel sau Google Analytics, categoriile apar automat aici și în banner. Textul trimite la „Funcții”, iar în meniul din stânga ecranul respectiv apare cu numele „Integrări”." },
            { titlu: "Cum arată pentru vizitator", text: "În panoul de pe magazin, categoriile se numesc „Esențiale”, „Analiză” și „Marketing”, fără parantezele din panoul de administrare, și au fiecare descrierea ei." },
          ],
          termeni: ["categorii cookie", "analiza marketing cookie", "integrari pixel", "preferinte cookie"],
        },
      ],
    },
  ],
};
